(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var h1=function(a){a.W("cardstatechange",a.Ug()&&a.yj()?1:0)},i1=function(a,b){var c=g.La(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},EGa=function(a){var b=g.vg(a);
a=g.Bg(a);return new g.ag(b.x,b.y,a.width,a.height)},FGa=function(a){return Math.pow(a,3)},GGa=function(a){return 3*a*a-2*a*a*a},l1=function(a){a=g.Oa(a);
delete j1[a];g.Pb(j1)&&k1&&k1.stop()},IGa=function(){k1||(k1=new g.J(function(){HGa()},20));
var a=k1;a.isActive()||a.start()},HGa=function(){var a=g.Ra();
g.Bb(j1,function(b){JGa(b,a)});
g.Pb(j1)||IGa()},m1=function(a,b,c,d){g.xn.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.i=a;this.J=b;this.duration=c;this.C=d;this.coords=[];this.progress=this.G=0;this.B=null},JGa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.G=1E3/(b-a.B);a.B=b;KGa(a,a.progress);1==a.progress?(a.eb=0,l1(a),a.onFinish(),a.nt()):a.qc()&&a.Cy()},KGa=function(a,b){"function"===typeof a.C&&(b=a.C(b));
a.coords=Array(a.i.length);for(var c=0;c<a.i.length;c++)a.coords[c]=(a.J[c]-a.i[c])*b+a.i[c]},LGa=function(a,b){g.Hl.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.G;this.state=b.eb},n1=function(a,b,c,d,e){m1.call(this,b,c,d,e);
this.element=a},o1=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
n1.call(this,a,b,c,d,e)},p1=function(a){g.F.call(this);
this.l=a||window;this.i=[]},q1=function(a){return a.baseUrl||null},r1=function(a,b){return g.Ke(g.Pc(a,b,void 0),function(c){return!!c})},MGa=function(a,b,c){function d(Ua){var Jb,sd,Cg,db=Ua.hovercardButton;
if(!db)return null;db=db.subscribeButtonRenderer;if(!db)return null;var Ne=f(db.unsubscribedButtonText),Dc=f(db.subscribedButtonText);if(db.subscribed){var xl=f(db.subscriberCountWithUnsubscribeText);var Lj=f(db.subscriberCountText)}else xl=f(db.subscriberCountText),Lj=f(db.subscriberCountWithSubscribeText);var Sf=null;return Ua.signinEndpoint&&(Sf=i1(Ua,"signinEndpoint","webNavigationEndpointData","url"),Sf||(Sf=null===(Cg=null===(sd=null===(Jb=db.signInEndpoint)||void 0===Jb?void 0:Jb.commandMetadata)||
void 0===sd?void 0:sd.webCommandMetadata)||void 0===Cg?void 0:Cg.url),!Sf)?null:Ne&&(Dc||Sf)?{subscribed:db.subscribed,subscribeText:Ne,subscribeCount:xl,unsubscribeText:Dc,unsubscribeCount:Lj,enabled:db.enabled,signinUrl:Sf,classic:Ua.useClassicSubscribeButton}:null}
function e(Ua){if(Ua){var Jb=[],sd=Ua.videoId;sd&&Jb.push("v="+sd);(sd=Ua.playlistId)&&Jb.push("list="+sd);(Ua=Ua.startTimeSeconds)&&Jb.push("t="+Ua);return"/watch?"+Jb.join("&")}}
function f(Ua){if(!Ua)return null;var Jb=Ua.simpleText;return Jb?Jb:Ua.runs?g.Pc(Ua.runs,function(sd){return sd.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=null,r=null,t=null,u=null,x=!1,y=null,B=null,H=null,E=null,I=null;if("VIDEO"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,r=f(b.videoDuration);else if("PLAYLIST"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,t=f(b.playlistLength);else if("CHANNEL"===h){if(x=i1(l,"browseEndpoint","browseId"))u=x,m="/channel/"+u;n=!1;p="new";(x=!!b.isSubscribe)?y=d(b):B=f(b.subscribersText)}else"WEBSITE"===
h?((H=i1(l,"urlEndpoint","url"))&&(m=H),n=!0,p="new",H=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(E=f(b.productPrice)),b.additionalFeesText&&(I=f(b.additionalFeesText)),(n=i1(l,"urlEndpoint","url"))&&(m=n),n=!0,p="new");a=i1(b,"title","accessibility","accessibilityData","label");var Q=b.endpoint?b.endpoint.clickTrackingParams:null,ha="";if(b.metadata){var Da=f(b.metadata);Da&&(ha=Da)}return{id:"element-"+c,type:h,title:f(b.title),metadata:ha,callToAction:f(b.callToAction),
vF:b.image,iconUrl:H,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,playlistLength:t,channelId:u,subscribeButton:y,subscribersText:B,isSubscribe:x,targetUrl:m||null,fO:n,Hd:Q?{itct:Q}:null,GS:p,Cr:a?a:null,iO:b.isPlaceholder,impressionUrls:r1(b.impressionUrls||[],q1),XN:r1(b.hovercardShowUrls||[],q1),clickUrls:r1(l.loggingUrls||[],q1),visualElement:g.Bu(b.trackingParams),
productPrice:E,additionalFeesText:I}},s1=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:r1(a.impressionUrls||[],q1),elements:r1(a.elements||[],function(d,e){return MGa(b,d,e)})};
a.trackingParams&&(c.visualElement=g.Bu(a.trackingParams));return c},t1=function(a){g.fM.call(this,a);
this.u=this.endscreen=null;this.i={};this.C={};this.B=this.l=null;this.J=[];this.V=!0;this.G=0;a=a.T();this.L=g.DD(a)||g.HD(a);this.events=new g.VL(this);g.G(this,this.events);this.events.N(this.player,g.$v("creatorendscreen"),this.qd);this.events.N(this.player,g.aw("creatorendscreen"),this.qf);this.events.N(this.player,"resize",this.ob);this.events.N(window,"focus",this.LR);this.load();var b=g.Fe("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.Hi(this,function(){g.Je(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},NGa=function(a){return a.player.getVideoData().C?"current":a.L?"new":"current"},u1=function(a){return"creator-endscreen-editor"===a.player.T().playerStyle},OGa=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.u&&a.u.abort();c={method:"POST",onFinish:function(e){var f=a.u=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=s1(f,NGa(a))));v1(a,f)},
urlParams:{v:c},withCredentials:!0};a.L&&(c.urlParams.ptype="embedded");var d=b.hn;d&&(c.postParams={ad_tracking:d});if(b=g.aja(b))if(b=g.Ic(b),b=g.Ec(b))a.u=g.wp(b,c)},v1=function(a,b,c){c=void 0===c?!0:c;
a.player.Ue("creatorendscreen");a.l&&(a.l.dispose(),a.l=null,a.B.dispose(),a.B=null);for(var d=g.q(Object.values(a.i)),e=d.next();!e.done;e=d.next())e.value.dispose();a.i={};a.C={};0<a.J.length&&(a.J.forEach(function(l){l.dispose()}),a.J.length=0);
a.G=0;if((a.endscreen=b)&&b.elements){c&&PGa(a);c=[];d=new g.Xv(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.T().i||(a.l=new g.V({D:"div",K:"ytp-ce-shadow"}),g.TL(a.player,a.l.element,4),a.B=new g.LK(a.l,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=QGa(a,e);if(f){a.i[e.id]=f;a.C[e.id]=e;g.TL(a.player,f.element,4);var h=new g.Xv(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);RGa(a,f,e)}else g.Tu(new g.Cs("buildEndscreenElement null",
e))}a.player.xd(c);a.ob()}},PGa=function(a){var b=g.Fu(),c=g.Hu();
c&&b&&a.endscreen.visualElement&&g.gv(c,b,a.endscreen.visualElement)},QGa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c=a.player.Z("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];a={D:"div",Ca:["ytp-ce-element","ytp-ce-video"],U:{tabindex:"0","aria-label":b.Cr||"","aria-hidden":"true"},S:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-covering-image",U:w1(b)},{D:"div",K:"ytp-ce-covering-shadow-top"},{D:"a",K:"ytp-ce-covering-overlay",U:{href:x1(a,b.targetUrl),tabindex:"-1"},S:[{D:"div",Ca:["ytp-ce-video-title"].concat(g.ma(c)),U:{dir:g.Dn(b.title||
"")},oa:b.title},{D:"div",K:"ytp-ce-video-duration",oa:b.videoDuration||void 0}]}]};c=new g.V(a);break;case "PLAYLIST":c=a.player.Z("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];a={D:"div",Ca:["ytp-ce-element","ytp-ce-playlist"],U:{tabindex:"0","aria-label":b.Cr||"","aria-hidden":"true"},S:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-covering-image",U:w1(b)},{D:"div",K:"ytp-ce-covering-shadow-top"},{D:"a",K:"ytp-ce-covering-overlay",U:{href:x1(a,
b.targetUrl),tabindex:"-1"},S:[{D:"div",Ca:["ytp-ce-playlist-title"].concat(g.ma(c)),U:{dir:g.Dn(b.title||"")},oa:b.title},{D:"div",K:"ytp-ce-playlist-count",S:[{D:"div",K:"ytp-ce-playlist-icon"},{D:"div",K:"ytp-ce-playlist-count-text",oa:b.playlistLength||void 0}]}]}]};c=new g.V(a);break;case "CHANNEL":c={D:"div",Ca:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],U:{tabindex:"0","aria-label":b.Cr||"","aria-hidden":"true"},S:[{D:"div",K:"ytp-ce-element-shadow"},
{D:"div",K:"ytp-ce-expanding-overlay",S:[{D:"div",K:"ytp-ce-expanding-overlay-hider"},{D:"div",K:"ytp-ce-expanding-overlay-background"},{D:"div",K:"ytp-ce-expanding-overlay-content",S:[{D:"div",K:"ytp-ce-expanding-overlay-body",S:[{D:"div",K:"ytp-ce-expanding-overlay-body-padding",S:[{D:"a",Ca:["ytp-ce-channel-title","ytp-ce-link"],U:{href:x1(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Dn(b.title||"")},oa:b.title},b.subscribeButton?{D:"div",K:"ytp-ce-subscribe-container",S:[{D:"div",K:"ytp-ce-channel-subscribe"}]}:
"",b.subscribersText?{D:"div",K:"ytp-ce-channel-subscribers-text",oa:b.subscribersText}:"",b.metadata?{D:"div",Ca:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],oa:b.metadata}:""]}]}]}]},{D:"div",K:"ytp-ce-expanding-image",U:w1(b)}]};c=new g.V(c);var d=g.re(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.K(d,"ytp-ce-subscribe-button");if(a.player.T().i){var e=null;var f=b.Hd.itct}else e="endscreen",f=null;e=new g.hN(b.subscribeButton.subscribeText,
b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.J.push(e)}break;case "WEBSITE":a={D:"div",Ca:["ytp-ce-element","ytp-ce-website"],U:{tabindex:"0","aria-label":b.Cr||"","aria-hidden":"true"},S:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-expanding-overlay",S:[{D:"div",K:"ytp-ce-expanding-overlay-hider"},
{D:"div",K:"ytp-ce-expanding-overlay-background"},{D:"div",K:"ytp-ce-expanding-overlay-content",S:[{D:"div",K:"ytp-ce-expanding-overlay-body",S:[{D:"div",K:"ytp-ce-expanding-overlay-body-padding",S:[{D:"div",K:"ytp-ce-website-title",U:{dir:g.Dn(b.title||"")},oa:b.title},{D:"div",K:"ytp-ce-website-metadata",oa:b.metadata},{D:"a",Ca:["ytp-ce-website-goto","ytp-ce-link"],U:{href:x1(a,b.targetUrl),target:"_blank",tabindex:"-1"},oa:b.callToAction}]}]}]}]},{D:"div",K:"ytp-ce-expanding-image",U:w1(b)},{D:"div",
K:"ytp-ce-expanding-icon",U:SGa(b.iconUrl)}]};c=new g.V(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={D:"div",K:"ytp-ce-merchandise-price-container",S:[{D:"div",K:"ytp-ce-merchandise-price",oa:b.productPrice}]},b.additionalFeesText&&c.S.push({D:"div",K:"ytp-ce-merchandise-additional-fees",oa:b.additionalFeesText})),a={D:"div",Ca:["ytp-ce-element","ytp-ce-merchandise"],U:{tabindex:"0","aria-label":b.Cr||"","aria-hidden":"true"},S:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-expanding-overlay",
S:[{D:"div",K:"ytp-ce-expanding-overlay-hider"},{D:"div",K:"ytp-ce-expanding-overlay-background"},{D:"div",K:"ytp-ce-expanding-overlay-content",S:[{D:"div",K:"ytp-ce-expanding-overlay-body",S:[{D:"div",K:"ytp-ce-expanding-overlay-body-padding",S:[{D:"div",K:"ytp-ce-merchandise-title",U:{dir:g.Dn(b.title||"")},oa:b.title},c,{D:"div",K:"ytp-ce-merchandise-metadata",oa:b.metadata},{D:"a",Ca:["ytp-ce-merchandise-goto","ytp-ce-link"],U:{href:x1(a,b.targetUrl),target:"_blank",tabindex:"-1"},oa:b.callToAction}]}]}]}]},
{D:"div",K:"ytp-ce-expanding-image",U:w1(b)},{D:"div",K:"ytp-ce-merchandise-invideo-cta-container",S:[{D:"div",K:"ytp-ce-merchandise-invideo-cta",oa:b.callToAction||void 0}]}]},c=new g.V(a)}b.iO&&g.K(c.element,"ytp-ce-placeholder");return c},w1=function(a){if(a.vF)var b=a.vF.thumbnails;
return SGa(b?b[b.length-1].url:null)},SGa=function(a){return a?{style:"background-image: url("+a+")"}:{}},RGa=function(a,b,c){function d(m){m&&(b.Oa("blur",function(){"none"!=m.style.display&&a.V&&m.focus()}),b.N(m,"focus",f),b.N(m,"blur",h))}
function e(m){a.G+=m;0<a.G?(g.K(b.element,"ytp-ce-force-expand"),y1(a,c.id,!0)):(g.un(b.element,"ytp-ce-force-expand"),g.un(b.element,"ytp-ce-element-hover"),y1(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Oa("mouseenter",function(){z1(a,b,c)});
b.Oa("mouseleave",function(){A1(a,b,c)});
a.player.T().i||b.Oa("click",function(){g.K(b.element,"ytp-ce-element-hover")});
b.Oa("click",function(m){TGa(a,c,m)});
b.Oa("keypress",function(m){TGa(a,c,m)});
b.Oa("focus",function(){z1(a,b,c)});
b.Oa("blur",function(){A1(a,b,c)});
b.Oa("touchstart",function(){z1(a,b,c)});
var l=g.te("ytp-ce-expanding-overlay-hider",b.element);l&&b.N(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.un(b.element,"ytp-ce-element-hover");g.un(b.element,"ytp-ce-force-expand")});
b.Oa("keydown",function(m){a.V=9===m.keyCode&&!m.shiftKey});
d(g.te("ytp-sb-subscribe",b.element));d(g.te("ytp-sb-unsubscribe",b.element));b.Oa("focus",f);b.Oa("blur",h)},TGa=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.sn(d,"ytp-ce-element");){g.sn(d,"subscribe-label")&&B1(a,b);
if(g.sn(d,"ytp-ce-channel-subscribe"))return;d=g.Le(d)}if(!d||g.sn(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.i[b.id])A1(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.GS)B1(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Ic(x1(a,b.targetUrl)),c=g.Ec(c),g.NI(c,void 0,b.Hd);else{var e=a.player.getVideoData().C,f=function(){var h=x1(a,b.targetUrl),l=b.Hd,m=g.cp(h);e&&m&&(m.v||m.list)?a.player.aj(m.v,l,m.list,!1):g.MI(h,l)};
B1(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},x1=function(a,b){a=a.player.T();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.lE(a)+b}else return"";return b},z1=function(a,b,c){g.sn(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.K(b.element,"ytp-ce-element-hover"):a.player.T().i?(new g.J(function(){g.K(b.element,"ytp-ce-element-hover")},200)).start():g.K(b.element,"ytp-ce-element-hover"),C1(a,c.XN),y1(a,c.id,!0))},A1=function(a,b,c){g.un(b.element,"ytp-ce-element-hover");
g.un(b.element,"ytp-ce-force-expand");y1(a,c.id,!1)},y1=function(a,b,c){a.l&&(c?a.B.show():a.B.hide());
for(var d=g.q(Object.keys(a.i)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.L(a.i[e].element,"ytp-ce-element-shadow-show",c)},C1=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||u1(a))c&&c();else{b=UGa(a,b);var e=0,f=!1,h=new g.J(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.Nq(b[a],d)}},B1=function(a,b,c){C1(a,b.clickUrls,c);
(a=g.Hu())&&b.fO&&g.jv(a,b.visualElement)},UGa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(VGa(b[d],c));return a},VGa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},WGa=function(a){return Array.isArray(a)&&a.length?a[0]:a},D1=function(a){return"string"===typeof a?a:""},E1=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},XGa=function(a){this.externalId=a},YGa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.i=d},F1=function(a){return a.value?a.value:null},G1=function(a){if(!a)return null;
var b=g.Ic(D1(a.value));b=g.Ec(b);if(!b)return null;var c=E1(a.target,ZGa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new YGa(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},$Ga=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},cHa=function(a){if(!a)return null;
var b=E1(a.type,aHa),c=E1(a.trigger,bHa),d=WGa(a.url);d=G1(d?d:null);a=WGa(a.subscribeData);var e=a?a:null;e?(a=D1(e.external_user_id),e=D1(e.subscription_token),a=a&&e?new XGa(a):null):a=null;return b?new $Ga(b,c,d,a):null},dHa=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},fHa=function(a){return(a=eHa(a,function(b){return"openUrl"===b.type&&null!=b.url}))?a.url:null},eHa=function(a,b){return g.bb(a.action,b,void 0)},gHa=function(a,b){this.context=a;
this.i=b},I1=function(a){return a.customMessage?H1("div","iv-card-message",a.customMessage):""},J1=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{D:"div",K:"iv-card-image",U:{style:a},S:c}},K1=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.q(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(H1("li","",c.value));return{D:"ul",K:"iv-card-meta-info",S:b}},H1=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Dn(c);return{D:a,U:b,oa:c}},hHa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.Lu&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.Lu+");");c.dir=g.Dn(a.customMessage);var d=[{D:"span",oa:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({D:"span",K:"iv-card-link-icon"}));return{D:"div",Ca:b,U:c,S:d}},L1=function(a,b,c,d){if(d){b=g.q(b);
for(var e=b.next();!e.done;e=b.next())a.i(e.value,d,c.id,c.Hd,c.tracking.click,5)}},iHa=function(a,b){this.merchant=a;
this.price=b},jHa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},kHa=function(a,b){return b?b:jHa(a)?"current":"new"},M1=function(a,b){g.F.call(this);
var c=this;this.element=a;this.context=b;this.Ta=!1;this.Fa=new Map;this.La=new Map;this.context.I.addEventListener(g.$v("annotations_module"),function(d){(d=c.Fa.get(d))&&d.apply(c)});
this.context.I.addEventListener(g.aw("annotations_module"),function(d){(d=c.La.get(d))&&d.apply(c)})},N1=function(a,b,c,d,e,f,h){a.context.i.Oa(b,"click",function(l){a.Dy(c,d,e,f||[],h||0,l)});
a.context.i.Oa(b,"touchstart",function(){a.Ta=!1});
a.context.i.Oa(b,"touchmove",function(){a.Ta=!0})},lHa=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},O1=function(a,b,c){return{lG:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
iJ:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
zx:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},R1=function(a,b,c){M1.call(this,b,c);
var d=this;this.I=a;this.eventId=null;this.Ea=this.Za=this.u=this.Md=!1;this.ma=null;this.cards=[];this.Xa=this.L=this.ya=this.C=this.Da=this.i=null;this.X=[];this.J=this.Sd=this.xa=null;this.G=0;this.ra=new g.J(g.Ia,c.B.Wb?4E3:3E3);g.G(this,this.ra);this.Ua=new g.J(g.Ia);g.G(this,this.Ua);this.Y=new gHa(c,function(e,f,h,l,m,n){N1(d,e,f,h,l,m,n)});
this.V=new g.V({D:"div",K:"iv-drawer",U:{id:"iv-drawer"},S:[{D:"div",K:"iv-drawer-header",U:{"aria-role":"heading"},S:[{D:"span",K:"iv-drawer-header-text"},{D:"button",Ca:["iv-drawer-close-button","ytp-button"],U:{"aria-label":"Hide cards",tabindex:"0"}}]},{D:"div",K:"iv-drawer-content"}]});g.G(this,this.V);this.B=this.V.element;this.Na=new g.LK(this.V,330);g.G(this,this.Na);this.Ya=g.te("iv-drawer-header-text",this.B);this.l=g.te("iv-drawer-content",this.B);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Za&&P1(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Za=d.u)&&Q1(d)})},mHa=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){P1(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){Q1(a)});
var c=b.headerText;g.Re(a.Ya,c);a.L&&a.L.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.xa=g.Bu(b.trackingParams);a.J=g.Bu(b.closeTrackingParams);a.Sd=g.Bu(b.iconTrackingParams)},nHa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.G;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.G,type:"simple",teaserText:g.gw(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Hd:S1(a,c,b,d),sponsored:!1,tracking:O1(d,e,d.command),Ck:d.trackingParams?g.Bu(d.trackingParams):null,Yh:e.trackingParams?
g.Bu(e.trackingParams):null,Sd:f&&f.trackingParams?g.Bu(f.trackingParams):null,imageUrl:T1(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.gw(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,Lu:null,title:d.title?g.gw(d.title):"",customMessage:d.callToAction?g.gw(d.callToAction):"",url:d.command.urlEndpoint.url?G1({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.command.urlEndpoint.url}):null};U1(a,b)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.G,type:"collaborator",teaserText:g.gw(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Hd:S1(a,c,b,d),sponsored:!1,tracking:O1(d,e,d.endpoint),Ck:d.trackingParams?g.Bu(d.trackingParams):null,Yh:e.trackingParams?g.Bu(e.trackingParams):null,Sd:f&&f.trackingParams?g.Bu(f.trackingParams):
null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.gw(d.customText):null,qI:T1(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.gw(d.channelName):"",metaInfo:[d.subscriberCountText?g.gw(d.subscriberCountText):""],url:G1({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};U1(a,b)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.G,type:"playlist",teaserText:g.gw(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Hd:S1(a,c,b,d),sponsored:!1,tracking:O1(d,e,d.action),Ck:d.trackingParams?g.Bu(d.trackingParams):null,Yh:e.trackingParams?g.Bu(e.trackingParams):null,Sd:f&&f.trackingParams?g.Bu(f.trackingParams):
null,Xt:T1(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.gw(d.customMessage):null,playlistVideoCount:g.gw(d.playlistVideoCount),title:d.playlistTitle?g.gw(d.playlistTitle):"",metaInfo:[d.channelName?g.gw(d.channelName):"",d.videoCountText?g.gw(d.videoCountText):""],url:G1({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:lHa(d.action)})};U1(a,b)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;
e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.G,type:"video",teaserText:g.gw(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Hd:S1(a,c,b,d),sponsored:!1,tracking:O1(d,e,d.action),Ck:d.trackingParams?g.Bu(d.trackingParams):null,Yh:e.trackingParams?g.Bu(e.trackingParams):null,Sd:f&&f.trackingParams?g.Bu(f.trackingParams):null,Xt:T1(d.videoThumbnail.thumbnails,
258).url,videoDuration:d.lengthString?g.gw(d.lengthString):null,customMessage:d.customMessage?g.gw(d.customMessage):null,title:d.videoTitle?g.gw(d.videoTitle):"",metaInfo:[d.channelName?g.gw(d.channelName):"",d.viewCountText?g.gw(d.viewCountText):""],isLiveNow:!!d.badge,url:G1({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:lHa(d.action)})};U1(a,b)}a.G++},T1=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},S1=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},pHa=function(a,b){if(b=oHa(a,b))b===a.i&&(a.i=null),a.I.removeCueRange(b.card.id),g.Je(b.pz),g.kb(a.cards,b),a.Nu(),V1(a)},P1=function(a,b,c){if(!a.u){a.Na.show();
a.Da=new g.J(function(){g.K(a.context.I.getRootNode(),g.mS.IV_DRAWER_OPEN)},0);
a.Da.start();a.ma=g.Vp(a.l,"mousewheel",function(h){a.ra.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.l.scrollTop+=h});
a.u=!0;var d=g.Hu();d&&a.xa&&a.J&&g.hv(d,[a.xa,a.J]);b={TRIGGER_TYPE:b};for(var e=g.q(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.QG||(f.QG=!0,qHa(a.context.logger,f.card.tracking.lG,b)),d&&g.hv(d,[f.card.Ck]);h1(a.I);c&&(a.C=new g.J(function(){a.ya=a.L;a.Xa.focus()},330),a.C.start())}},Q1=function(a){a.u&&(a.Na.hide(),g.Wp(a.ma),a.ma=null,g.un(a.context.I.getRootNode(),g.mS.IV_DRAWER_OPEN),a.u=!1,h1(a.I),a.C&&a.C.stop(),a.C=new g.J(function(){a.ya&&(a.ya.focus(),a.ya=null)},330),a.C.start())},
sHa=function(a){g.tn(a.element,[g.mS.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.TL(a.I,a.B,5);rHa(a);a.L=g.te("ytp-cards-button",a.I.getRootNode());a.Xa=g.te("iv-drawer-close-button",a.B);a.Md=!0},rHa=function(a){var b=g.te("iv-drawer-close-button",a.B);
a.context.i.Oa(b,"click",a.OM,a);a.context.i.Oa(a.l,"touchend",function(){a.ra.start()});
a.context.i.Oa(a.l,"scroll",a.aN,a);a.context.l.subscribe("onHideControls",function(){a.Ea=!0});
a.context.l.subscribe("onShowControls",function(){a.Ea=!1});
a.context.l.subscribe("onVideoAreaChange",function(){a.Ea=g.sn(a.I.getRootNode(),"ytp-autohide")});
a.X.push(g.Uq("iv-button-shown",a.pO,a));a.X.push(g.Uq("iv-button-hidden",a.oO,a));a.X.push(g.Uq("iv-teaser-shown",a.pL,a));a.X.push(g.Uq("iv-teaser-hidden",a.rO,a));a.X.push(g.Uq("iv-teaser-clicked",a.oL,a))},U1=function(a,b){a.Md||sHa(a);
pHa(a,b.id);var c=tHa(a,b);if(c){var d={card:b,pz:c.element,QG:!1},e=uHa(a,d);g.rb(a.cards,e,0,d);c.Aa(a.l,e);a.Nu();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.u||(a.i=d,V1(a),vHa(a,d),P1(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.I.getCurrentTime(),5E3>c&&c>b.startMs&&wHa(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){wHa(a,d)}),V1(a))}},tHa=function(a,b){switch(b.type){case "simple":a=a.Y;
var c=b.displayDomain?{D:"div",K:"iv-card-image-text",oa:b.displayDomain}:void 0;var d=hHa(b);c={D:"div",Ca:["iv-card"],S:[{D:"a",K:"iv-click-target",U:{href:b.url?F1(b.url)||"":""},S:[J1(b.imageUrl,c),{D:"div",K:"iv-card-content",S:[H1("h2",void 0,b.title),d]}]}]};c=new g.V(c);L1(a,g.se("iv-click-target",c.element),b,b.url);return c;case "collaborator":return a=a.Y,c={D:"div",Ca:["iv-card","iv-card-channel"],S:[{D:"a",Ca:["iv-click-target"],U:{href:F1(b.url)||"","data-ytid":b.channelId},S:[J1(b.qI),
{D:"div",K:"iv-card-content",S:[I1(b),{D:"h2",K:"iv-card-primary-link",oa:b.title},K1(b)]}]}]},c=new g.V(c),L1(a,g.se("iv-click-target",c.element),b,b.url),c;case "playlist":return a=a.Y,c={D:"div",Ca:["iv-card","iv-card-playlist"],S:[{D:"a",K:"iv-click-target",U:{href:F1(b.url)||""},S:[J1(b.Xt,{D:"div",K:"iv-card-image-overlay",S:[{D:"span",K:"iv-card-playlist-video-count",oa:b.playlistVideoCount}]}),{D:"div",K:"iv-card-content",S:[I1(b),H1("h2","iv-card-primary-link",b.title),K1(b)]}]}]},c=new g.V(c),
L1(a,g.se("iv-click-target",c.element),b,b.url),c;case "productListing":a=a.Y;var e=!g.gb(b.offers);c=["iv-card"];d="";var f=hHa(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({D:"div",K:"iv-card-offer-price",oa:f.price}),f.merchant&&e.push({D:"div",K:"iv-card-offer-merchant",oa:f.merchant}),f={D:"div",S:e});e=b.url?F1(b.url)||"":"";c={D:"div",Ca:c,U:{tabindex:"0"},S:[{D:"a",Ca:["iv-card-image","iv-click-target"],U:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{D:"div",K:"iv-card-content",S:[b.sponsored?{D:"div",K:"iv-card-sponsored",S:["Sponsored",{D:"div",K:"iv-ad-info-container",S:[{D:"div",K:"iv-ad-info",oa:"{{adInfo}}"},{D:"div",K:"iv-ad-info-icon-container",S:[{D:"div",K:"iv-ad-info-icon"},{D:"div",K:"iv-ad-info-callout"}]}]}]}:"",{D:"a",K:"iv-click-target",U:{href:e},S:[H1("h2",d,b.title),f]}]}]};c=new g.V(c);d=g.Fe("span");g.Re(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.Uc(d,"adInfo");L1(a,g.se("iv-click-target",c.element),b,b.url);return c;case "video":return a=a.Y,d=b.videoDuration?{D:"span",K:"iv-card-video-duration",oa:b.videoDuration}:void 0,f=b.isLiveNow?{D:"span",Ca:["yt-badge","yt-badge-live"],oa:"LIVE NOW"}:null,d={D:"div",Ca:["iv-card","iv-card-video"],S:[{D:"a",K:"iv-click-target",U:{href:(null===(c=b.url)||void 0===c?void 0:F1(c))||""},S:[J1(b.Xt,d),{D:"div",K:"iv-card-content",S:[I1(b),H1("h2","iv-card-primary-link",b.title),K1(b),f]}]}]},c=new g.V(d),
L1(a,g.se("iv-click-target",c.element),b,b.url),c;default:return null}},uHa=function(a,b){if(0===a.cards.length)return 0;
a=g.cb(a.cards,function(c){return b.card.startMs>c.card.startMs||b.card.startMs===c.card.startMs&&b.card.timestamp>=c.card.timestamp?!0:!1});
return-1===a?0:a+1},xHa=function(a){return a.i?"productListing"===a.i.card.type:g.jh(a.cards,function(b){return"productListing"===b.card.type})},V1=function(a){g.L(a.I.getRootNode(),"ytp-cards-shopping-active",xHa(a))},wHa=function(a,b){if(!g.sn(a.I.getRootNode(),"ytp-cards-teaser-shown")){if(a.i!==b){var c=g.Hu(),d=a.i?a.i.card.Sd:a.Sd;
c&&d&&g.iv(c,[d]);a.i=b;V1(a)}if(c="none"!=a.element.style.display)g.R(a.context.I.T().experiments,"html5_enable_single_video_vod_ivar_on_pacf")||2!==a.context.I.getPresentingPlayerType()?(c=a.context.I.getPlayerState(),d=0===c&&0===a.context.I.getCurrentTime(),c=1===c||3===c||d):c=1===a.context.I.getAdState();c&&b.card.teaserDurationMs&&a.I.Gq(!0,{teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs});a.Ua.isActive()||((!a.u||!a.ra.isActive()&&a.Ea)&&vHa(a,b),a.Ua.start(910+b.card.teaserDurationMs))}},
vHa=function(a,b){a.V.vb?(b=new m1([0,
a.l.scrollTop],[0,b.pz.offsetTop],600,GGa),a.context.u.Oa(b,"animate",function(c){a.l.scrollTop=c.y}),a.context.u.Oa(b,"finish",function(c){a.l.scrollTop=c.y}),b.play()):(g.bK(a.V,!0),a.l.scrollTop=b.pz.offsetTop,g.bK(a.V,!1))},W1=function(a){return a.i&&a.i.card?a.i.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},oHa=function(a,b){return g.bb(a.cards,function(c){return c.card.id===b})},X1=function(a,b,c){M1.call(this,a,b);
this.annotation=c;this.isActive=!1},yHa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},Y1=function(a,b,c){X1.call(this,a,b,c);
this.l=null;this.J=!1;this.u=null;this.B=!1;this.i=this.G=this.C=null},zHa=function(a,b){var c=void 0===c?0:c;
var d=EGa(b).width;g.tg(b,d);c=new o1(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,FGa);g.G(a,c);a.context.u.Oa(c,"begin",function(){g.Fg(b,!0)});
c.play()},CHa=function(a,b){if(b.channel_name){var c=a.createElement({D:"div",
Ca:["iv-branding-context-name"],oa:b.channel_name}),d=a.createElement({D:"div",Ca:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.i=new g.hN(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signinUrl,a.context.I),a.i.Aa(d));var f=a.createElement({D:"div",Ca:["iv-branding-context-subscribe-caret"]}),h=a.createElement({D:"div",Ca:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.Fg(h,!1);var l=a.createElement({D:"div",Ca:["branding-context-container-outer"]});l.appendChild(h);g.lg(l,"right",b.image_width+"px");a.element.appendChild(l);a.u=new g.J(function(){AHa(a,h,l)},500);
g.G(a,a.u);a.context.i.Oa(a.element,"mouseover",function(){BHa(a,h,l,f,b.image_height)});
a.context.i.Oa(a.element,"mouseout",function(){a.u.start()})}},BHa=function(a,b,c,d,e){a.u.stop();
if(!a.B){var f=g.Bg(b);a.i||(b.style.width=g.sg(f.width,!0),c.style.width=g.sg(f.width,!0));g.lg(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.lg(d,"right","1px");a.B=!0;g.Fg(b,!0);a.C=new g.J(function(){g.K(this.element,"iv-branding-active")},0,a);
a.C.start()}},AHa=function(a,b,c){g.un(a.element,"iv-branding-active");
a.G=new g.J(function(){g.Fg(b,!1);a.i||(c.style.width=g.sg(0,!0))},250);
a.G.start();a.B=!1},DHa=function(a,b,c,d,e,f,h){this.i=a;
this.u=b;this.B=c;this.videoData=d;this.logger=e;this.I=f;this.l=h},Z1=function(a,b,c){X1.call(this,a,b,c);
var d=this;this.L=this.isCollapsed=this.V=!1;this.G=5E3;this.l=this.u=this.i=this.B=null;this.J=this.createElement({D:"div",Ca:["iv-promo-contents"]});this.C=new g.J(function(){d.i.setAttribute("aria-hidden","true");g.Fg(d.u,!1);g.Fg(d.l,!0)},700,this);
g.G(this,this.C)},EHa=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.G=b.collapsedelay_ms||a.G;var d=["iv-promo","iv-promo-inactive"];a.element.setAttribute("aria-hidden","true");a.element.setAttribute("aria-label","Promotion");a.element.tabIndex=0;var e=fHa(a.annotation),f=b.image_url;if(f){var h=a.createElement({D:"div",Ca:["iv-promo-img","iv-click-target"]});f=a.createElement({D:"img",U:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&
!b.is_live?(f=a.createElement({D:"span",K:"iv-promo-video-duration",oa:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({D:"span",K:"iv-promo-playlist-length",oa:b.playlist_length.toString()}),h.appendChild(f));e&&N1(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({D:"a",K:"iv-promo-txt"}),g.hd(f,F1(e)),a.i=f):a.i=a.createElement({D:"div",K:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({D:"p",S:[{D:"strong",
oa:b.text_line_1}]});var m=a.createElement({D:"p",S:[{D:"span",K:"iv-promo-link",oa:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({D:"button",Ca:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({D:"button",Ca:["iv-button","iv-promo-button"],S:[{D:"span",K:"iv-button-content",oa:f}]});var p=a.createElement({D:"div",K:"iv-promo-button-container"});p.appendChild(f);e&&N1(a,a.element,e,a.annotation.id,b.session_data,void 0,c)}g.K(a.i,
"iv-click-target");e&&N1(a,a.i,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({D:"p",S:[{D:"span",oa:b.text_line_1}]}),m=a.createElement({D:"p",S:[{D:"strong",oa:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({D:"span",Ca:["yt-badge","iv-promo-badge-live"],oa:"LIVE NOW"})),g.K(a.i,"iv-click-target"),e&&N1(a,a.i,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.i.appendChild(l);m&&a.i.appendChild(m);a.J.appendChild(a.i);p&&
a.J.appendChild(p);c=a.createElement({D:"div",K:"iv-promo-actions"});a.l=a.createElement({D:"button",Ca:["iv-promo-expand","ytp-button"]});a.l.title="Expand";a.context.i.Oa(a.l,"click",function(r){$1(a,5E3,r)});
c.appendChild(a.l);g.Fg(a.l,!1);a.context.i.Oa(a.element,"mouseover",a.FN,a);a.context.i.Oa(a.element,"mouseout",a.EN,a);a.context.i.Oa(a.element,"touchend",function(r){$1(a,5E3,r)});
a.u=a.createElement({D:"button",Ca:["iv-promo-close","ytp-button"]});a.u.title="Close";a.context.i.Oa(a.u,"click","cta"===a.annotation.style&&b.text_line_3?a.BN:a.AN,a);c.appendChild(a.u);g.tn(a.element,d);h&&(a.element.appendChild(h),n&&h.appendChild(n));a.element.appendChild(a.J);a.element.appendChild(c)},$1=function(a,b,c){c.stopPropagation();
FHa(a);GHa(a,b);a.i.focus()},HHa=function(a){a.isCollapsed||a.L||a.B||(g.K(a.element,"iv-promo-collapsed"),a.isCollapsed=!0,a.C.start())},FHa=function(a){a.C.stop();
a.isCollapsed&&(g.vn(a.element,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.i&&a.i.removeAttribute("aria-hidden"),g.Fg(a.l,!1),g.Fg(a.u,!0))},GHa=function(a,b){a.B||(a.B=g.Lm(function(){a2(this);
HHa(this)},b,a))},a2=function(a){a.B&&(g.A.clearTimeout(a.B),a.B=null)},IHa=function(a){this.I=a},qHa=function(a,b,c){b&&(c?b2(a,b.map(function(d){return g.en(d,c)})):b2(a,b))},b2=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.q(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.Nq(m,f);d&&(e++,0!==d&&a.I.sendVideoStatsEngageEvent(d,f))},c2=function(a){g.fM.call(this,a);
var b=this;this.V=!1;this.loadNumber=0;this.J={};this.logger=new IHa(this.player);this.C=new g.VL(this);this.G=this.u=null;this.events=new g.VL(this);this.L=this.i=null;this.X=[];g.G(this,this.C);this.C.N(this.player,"onVideoAreaChange",function(){b.W("onVideoAreaChange")});
this.C.N(this.player,"onHideControls",function(){b.W("onHideControls")});
this.C.N(this.player,"onShowControls",function(){b.W("onShowControls")});
this.C.N(this.player,"resize",function(d){b.W("resize",d)});
this.C.N(this.player,"presentingplayerstatechange",function(d){b.W("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.qL,this);this.subscribe("resize",this.Mw,this);this.player.T().L.subscribe("vast_info_card_add",this.fI,this);g.G(this,this.events);this.Y=this.createElement({D:"div",K:"video-custom-annotations"});this.l=new g.V({D:"div",Ca:["ytp-player-content","ytp-iv-player-content"]});g.G(this,this.l);g.TL(this.player,this.l.element,4);this.l.hide();this.B=new g.V({D:"div",Ca:["ytp-iv-video-content"]});g.G(this,this.B);a=this.createElement({D:"div",K:"video-annotations"});
a.appendChild(this.Y);this.B.element.appendChild(a);this.Wo()&&this.load();var c=this.createElement({D:"style"});(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(c);g.Hi(this,function(){g.Je(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},JHa=function(a){a=a.createElement({D:"div",
Ca:["annotation","annotation-type-custom"]});g.Fg(a,!1);return a},KHa=function(a,b){b=!b.isCued()&&!g.U(b,1024);
g.bK(a.l,b);g.bK(a.B,b)},LHa=function(a,b,c){a.V=!0;
a.G=g.wp(b,c)},MHa=function(a,b){for(var c={},d=g.q(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Ma(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(MHa(a,e))}return c},PHa=function(a){var b=a.player.getVideoData();
if(b.ma){var c=a.player.T().L.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.op(h)&&h.responseXML?h.responseXML:null)&&d2(a,h)}};
g.mq()&&(d.onFinish=NHa(a,d.onFinish));d.postParams={ic_only:"1"};OHa(d,c);a.V=!0;g.wp(b.ma,d)}}},OHa=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.Nr&&(a.postParams.ic_coll=b.Nr);b.Ru&&(a.postParams.ic_xml=b.Ru);b.au&&(a.postParams.ic_track=b.au)},QHa=function(a){var b=new g.V({D:"div"});
g.Fg(b.element,!1);var c=new R1(a.player,b.element,e2(a));g.G(c,b);b.Aa(a.l.element);c.Mt();return c},e2=function(a){if(!a.L){var b=new p1(a);
g.G(a,b);var c=new g.V_(a);g.G(a,c);a.L=new DHa(b,c,a.player.T(),a.player.getVideoData(),a.logger,a.player,a.Ec)}return a.L},d2=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.Hu();if(e){var f=g.Fu();f&&g.$u(g.Qo("use_default_events_client")?void 0:g.au,e,f,[g.Bu(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=MHa(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=E1(f.type,RHa),p=E1(f.style,SHa),r=D1(f.data),t=0!==r.length?JSON.parse(r):{};var u=f.action;f=cHa;if(null==u)var x=null;else if(g.La(u)){l=[];for(var y=g.q(u),B=y.next();!B.done;B=
y.next()){var H=f(B.value);H&&l.push(H)}x=l}else{var E=f(u);x=E?[E]:[]}e=m&&n?new dHa(m,n,p,x,t):null}else e=null}catch(Jb){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var I=JHa(f),Q=null;switch(l.type){case "branding":if(f.player.T().ib)break;f.l.element.appendChild(I);Q=new Y1(I,e2(f),l);break;case "promotion":g.TL(f.player,I,4),Q=new Z1(I,e2(f),l)}Q&&Q.Mt();if(f=Q)g.G(a,f),a.J[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.i||(a.i=QHa(a),g.G(a,a.i));if("card"===e.type){c=
a.i;var ha=e&&e.data&&e.data.card_type;f=e.data;if(ha)switch(l=f.tracking||{},l={lG:l.impression,click:l.click,close:l.close,iJ:l.teaser_impression,zx:l.teaser_click},I=f.tracking_params||{},Q=null,ha){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,Hd:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Ck:I.card?g.Bu(I.card):null,Yh:I.teaser?g.Bu(I.teaser):null,
Sd:I.icon?g.Bu(I.icon):null,channelId:f.channel_id,customMessage:f.custom_message?f.custom_message:null,qI:f.image_url,title:f.title,metaInfo:f.meta_info,url:G1({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};U1(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,Hd:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Ck:I.card?
g.Bu(I.card):null,Yh:I.teaser?g.Bu(I.teaser):null,Sd:I.icon?g.Bu(I.icon):null,Xt:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:G1({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};U1(c,e);break;case "productListing":f.signin_url&&(Q=G1({target:"current",value:f.signin_url}));ha=[];for(var Da=f.offers||[],Ua=0;Ua<Da.length;Ua++)ha.push(new iHa(g.rd(Da[Ua].merchant),g.rd(Da[Ua].price)));
e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,Hd:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Ck:I.card?g.Bu(I.card):null,Yh:I.teaser?g.Bu(I.teaser):null,Sd:I.icon?g.Bu(I.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,Lu:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?
f.custom_message:null,url:G1({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),c6:Q,b6:f.signin_title?f.signin_title:void 0,a6:f.signin_message?f.signin_message:void 0,offers:ha};U1(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,Hd:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Ck:I.card?g.Bu(I.card):null,Yh:I.teaser?g.Bu(I.teaser):
null,Sd:I.icon?g.Bu(I.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,Lu:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:G1({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};U1(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||
!1,Hd:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Ck:I.card?g.Bu(I.card):null,Yh:I.teaser?g.Bu(I.teaser):null,Sd:I.icon?g.Bu(I.icon):null,Xt:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:G1({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})},U1(c,e)}}else mHa(a.i,e);c=!0}}c&&(h1(a.player),a.Mw())},THa=function(a,b){var c=!1;
a.i||(a.i=QHa(a),g.G(a,a.i));for(var d=g.q(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(nHa(a.i,e.cardRenderer),c=!0);c&&(c=a.i,d=b.headerText?g.gw(b.headerText):"",g.Re(c.Ya,d),c.L&&c.L.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.xa=b.trackingParams?g.Bu(b.trackingParams):null,c.J=b.closeButton.infoCardIconRenderer.trackingParams?g.Bu(b.closeButton.infoCardIconRenderer.trackingParams):null,c.Sd=b.icon.infoCardIconRenderer.trackingParams?
g.Bu(b.icon.infoCardIconRenderer.trackingParams):null,h1(a.player),a.Mw())},UHa=function(a,b,c,d,e){if(!a.player.T().ib){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new $Ga("openUrl","click",new YGa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0),null));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;var l;b=b.subscribeButton.subscribeButtonRenderer;var m,n;h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.gw(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.gw(b.subscriberCountText))):(b.subscriberCountText&&(e=g.gw(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.gw(b.subscriberCountWithSubscribeText)));var p=b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url?b.signInEndpoint.webNavigationEndpointData.url:(null===(n=null===(m=null===(l=b.signInEndpoint)||void 0===l?void 0:l.commandMetadata)||void 0===m?void 0:m.webCommandMetadata)||void 0===n?void 0:n.url)||"";l={subscribeText:g.gw(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.gw(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:p};d.standalone_subscribe_button_data=
l}f=new dHa(c,"branding","branding",f,d);l=JHa(a);a.l.element.appendChild(l);f=new Y1(l,e2(a),f);f.Mt();g.G(f,f);a.J[c]=f}},NHa=function(a,b){return function(c){for(var d=[],e=0;e<arguments.length;++e)d[e-0]=arguments[e];
a.Ha()||a.X.push(g.jq(function(){b.apply(null,g.ma(d))}))}},VHa=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.ML.prototype.Gq=g.ca(15,function(a,b){var c=g.rM(this.qb());c&&c.Gq(a,b)});
var j1={},k1=null;g.Sa(m1,g.xn);g.k=m1.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.eb)this.progress=0,this.coords=this.i;else if(this.qc())return!1;l1(this);this.startTime=a=g.Ra();-1==this.eb&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.B=this.startTime;this.progress||this.Kw();this.Dh("play");-1==this.eb&&this.Dh("resume");this.eb=1;var b=g.Oa(this);b in j1||(j1[b]=this);IGa();JGa(this,a);return!0};
g.k.stop=function(a){l1(this);this.eb=0;a&&(this.progress=1);KGa(this,this.progress);this.Dh("stop");this.nt()};
g.k.pause=function(){this.qc()&&(l1(this),this.eb=-1,this.Dh("pause"))};
g.k.va=function(){0==this.eb||this.stop(!1);this.Dh("destroy");m1.Id.va.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.Cy=function(){this.Dh("animate")};
g.k.Dh=function(a){this.dispatchEvent(new LGa(a,this))};
g.Sa(LGa,g.Hl);g.Sa(n1,m1);n1.prototype.u=g.Ia;n1.prototype.Cy=function(){this.u();n1.Id.Cy.call(this)};
n1.prototype.nt=function(){this.u();n1.Id.nt.call(this)};
n1.prototype.Kw=function(){this.u();n1.Id.Kw.call(this)};
g.Sa(o1,n1);o1.prototype.u=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.v(p1,g.F);p1.prototype.Oa=function(a,b,c,d){c=(0,g.C)(c,d||this.l);a=g.Vp(a,b,c);this.i.push(a);return a};
p1.prototype.WA=function(a,b,c,d){c=(0,g.C)(c,d||this.l);a=g.dq(a,b,c);this.i.push(a);return a};
p1.prototype.fc=function(a){g.Wp(a);g.kb(this.i,a)};
p1.prototype.va=function(){g.Wp(this.i);this.i.length=0;g.F.prototype.va.call(this)};g.v(t1,g.fM);g.k=t1.prototype;g.k.load=function(){g.fM.prototype.load.call(this);if(!u1(this)){var a=g.bja(this.player.getVideoData());a?(a=s1(a,NGa(this)),v1(this,a,!1)):OGa(this)}};
g.k.unload=function(){v1(this,null);this.u&&(this.u.abort(),this.u=null);g.fM.prototype.unload.call(this)};
g.k.Ke=function(a,b){return u1(this)?"loadCustomEndscreenRenderer"===a?(a=s1(b,"new"),v1(this,a),!0):null:null};
g.k.getOptions=function(){return u1(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.ob=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<WHa.length;f++){var h=Math.abs(b.width-WHa[f]);if(-1===e||d>=h)e=f,d=h}d=XHa[e];this.l&&g.lg(this.l.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.i[f],
h=this.C[f],e&&h){var l=h.width*c/h.aspectRatio;f=Math.round(l*a.height);var m=a.left+Math.round(h.left*a.width),n=a.top+Math.round(h.top*a.height);g.Ag(e.element,Math.round(h.width*a.width),f);g.tg(e.element,m,n);g.vn(e.element,YHa);m=h.left+h.width/2;h=h.top+l/2;g.K(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.vn(e.element,XHa);g.K(e.element,d);(e=g.re(document,"div","ytp-ce-expanding-overlay-body",
e.element)[0])&&g.lg(e,"height",f+"px")}}}}};
g.k.qd=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())C1(this,this.endscreen.impressionUrls),(a=g.Hu())&&this.endscreen.visualElement&&g.av(a,this.endscreen.visualElement,void 0);else{a=a.getId().substring(15);var b=this.i[a],c=this.C[a];g.K(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.K(b,"ytp-ce-shown");C1(this,c.impressionUrls);(b=g.Hu())&&g.av(b,c.visualElement,void 0);this.player.T().u&&this.player.Ma("endscreenelementshown",
a)}};
g.k.qf=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.i[a];g.un(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.un(b,"ytp-ce-shown");this.player.T().u&&this.player.Ma("endscreenelementhidden",a)}};
g.k.LR=function(a){var b=this;a.target===window&&(new g.J(function(){for(var c=g.q(Object.values(b.i)),d=c.next();!d.done;d=c.next())g.vn(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var WHa=[346,426,470,506,570,640,853,1280,1920],XHa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),YHa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var ZGa={HW:"current",d1:"new"};var aHa={CLOSE:"close",w1:"openUrl",pM:"subscribe"},bHa={zU:"click",CLOSE:"close",VX:"hidden",H2:"rollOut",I2:"rollOver",v3:"shown"};var SHa={RT:"anchored",RJ:"branding",CHANNEL:"channel",FW:"cta",YX:"highlightText",VY:"label",PLAYLIST:"playlist",e2:"popup",D3:"speech",pM:"subscribe",T3:"title",VIDEO:"video",b5:"website"},RHa={RJ:"branding",mU:"card",UW:"drawer",XX:"highlight",v_:"marker",n2:"promotion",TEXT:"text",h5:"widget"};g.v(M1,g.F);g.k=M1.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.Xv(a,b,{id:c});a.namespace="annotations_module";d&&this.Fa.set(a,d);e&&this.La.set(a,e);this.context.I.xd([a])};
g.k.Mt=function(){this.context.l.subscribe("resize",this.Nu,this)};
g.k.Dy=function(a,b,c,d,e,f){if(this.Ta)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.Je(this.element)};
g.k.Nu=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=F1(a);if(f){var h=kHa(f,a.target),l=function(){a.i&&e.context.I.pauseVideo();var m=e.context.videoData.C||!1,n=g.cp(f||"");m&&n&&(n.v||n.list)?e.context.I.aj(n.v,b,n.list,!1):g.NI(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);b2(this.context.logger,c,l,d);jHa(f)||(c=g.Hu(),d=b.itct,c&&d&&g.jv(c,g.Bu(d)))}};
g.k.va=function(){this.Fa.clear();this.La.clear();g.F.prototype.va.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.G(this,a);return a.element};g.v(R1,M1);g.k=R1.prototype;g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.I.getRootNode())?(a=g.Bg(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.Nu=function(){var a=this.isAvailable();g.Fg(this.element,a);g.L(this.context.I.getRootNode(),g.mS.IV_DRAWER_ENABLED,a);h1(this.I)};
g.k.destroy=function(){this.I.Gq(!1);try{this.I.getRootNode().removeChild(this.B)}catch(a){}g.Vq(this.X);g.Wp(this.ma);this.Da&&this.Da.dispose();this.C&&this.C.dispose();M1.prototype.destroy.call(this)};
g.k.OM=function(){if(this.u){b2(this.context.logger,W1(this).tracking.close);var a=g.Hu();a&&this.J&&g.jv(a,this.J);Q1(this)}};
g.k.aN=function(){g.L(this.B,"iv-drawer-scrolled",0<this.l.scrollTop)};
g.k.pO=function(){var a=g.Hu(),b=W1(this);b=b?b.Sd:this.Sd;a&&b&&g.hv(a,[b])};
g.k.oO=function(){var a=g.Hu(),b=W1(this);b=b?b.Sd:this.Sd;a&&b&&g.iv(a,[b])};
g.k.pL=function(){var a=W1(this);b2(this.context.logger,a.tracking.iJ);var b=g.Hu();b&&a&&g.hv(b,[a.Yh,a.Sd])};
g.k.rO=function(){var a=g.Hu(),b=W1(this);a&&b&&g.iv(a,[b.Yh])};
g.k.oL=function(a){var b=W1(this),c=g.Hu();this.i?a?(a=this.context.logger,b2(a,b.tracking.zx),a.I.sendVideoStatsEngageEvent(4,void 0),c&&b.Yh&&g.jv(c,b.Yh)):(a=this.context.logger,b2(a,b.tracking.zx),a.I.sendVideoStatsEngageEvent(4,void 0),c&&b.Sd&&g.jv(c,b.Sd)):(a=this.context.logger,b2(a,b.tracking.zx),a.I.sendVideoStatsEngageEvent(4,void 0),c&&this.Sd&&g.jv(c,this.Sd))};g.v(X1,M1);X1.prototype.Mt=function(){M1.prototype.Mt.call(this);yHa(this)};
X1.prototype.show=function(){M1.prototype.show.call(this);var a=g.Hu(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.hv(a,[g.Bu(b.itct)])};
X1.prototype.hide=function(){M1.prototype.hide.call(this);var a=g.Hu(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.iv(a,[g.Bu(b.itct)])};g.v(Y1,X1);
Y1.prototype.show=function(){if(!this.isActive){X1.prototype.show.call(this);if(!this.J){g.K(this.element,"iv-branding");var a=this.annotation.data;this.l=this.createElement({D:"img",Ca:["branding-img","iv-click-target"],U:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.Fg(this.l,!1);var b=this.createElement({D:"div",Ca:["branding-img-container"]});b.appendChild(this.l);this.element.appendChild(b);(b=fHa(this.annotation))&&N1(this,this.l,b,this.annotation.id,
a.session_data);CHa(this,a);this.J=!0}g.Fg(this.element,!0);this.isActive=!0;this.l&&zHa(this,this.l)}};
Y1.prototype.hide=function(){this.isActive&&(X1.prototype.hide.call(this),g.Fg(this.element,!1),this.isActive=!1)};
Y1.prototype.destroy=function(){this.i&&(this.i.dispose(),this.i=null);X1.prototype.destroy.call(this)};g.v(Z1,X1);g.k=Z1.prototype;g.k.show=function(){this.isActive||(X1.prototype.show.call(this),this.V||(EHa(this),this.V=!0),g.Fg(this.element,!0),g.Lm(function(){g.un(this.element,"iv-promo-inactive")},100,this),this.element.removeAttribute("aria-hidden"),this.isActive=!0,a2(this),FHa(this),GHa(this,this.G))};
g.k.hide=function(){this.isActive&&(g.K(this.element,"iv-promo-inactive"),this.isActive=!1,this.element.setAttribute("aria-hidden","true"))};
g.k.Dy=function(a,b,c,d,e,f){return this.isCollapsed?!1:X1.prototype.Dy.call(this,a,b,c,d,e,f)};
g.k.FN=function(a){this.L=!0;$1(this,500,a)};
g.k.EN=function(){this.L=!1;HHa(this)};
g.k.AN=function(a){a.stopPropagation();this.hide()};
g.k.BN=function(a){a.stopPropagation();a2(this);this.isCollapsed=!0;g.K(this.element,"iv-promo-collapsed-no-delay");this.C.start()};
g.k.destroy=function(){this.C.dispose();X1.prototype.destroy.call(this)};g.v(c2,g.fM);g.k=c2.prototype;g.k.Ke=function(a,b){if(!VHa(this.player.T().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.U_(b))&&d2(this,a),!0;case "removeCustomAnnotationById":return b&&this.i&&(pHa(this.i,b),h1(this.player)),!0}return null};
g.k.getOptions=function(){return VHa(this.player.T().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Wo=function(){var a=this.player.T(),b=this.player.getVideoData();return b.C&&a.pfpChazalUi?!1:1===(a.annotationsLoadPolicy||b.annotationsLoadPolicy)&&!b.zE||a.L.get(b.videoId)||g.yG(b)||g.zG(b)?!0:!1};
g.k.Mw=function(){if(this.B){var a=this.player.Wa().getVideoContentRect(!0);g.Ag(this.B.element,a.width,a.height);g.tg(this.B.element,a.left,a.top)}if(this.i){var b=this.player.zi();a=this.i;b=b.width;g.L(a.B,"iv-drawer-small",426>=b);g.L(a.B,"iv-drawer-big",1280<=b)}};
g.k.qL=function(a){KHa(this,a.state);g.U(a.state,2)&&(this.Ug()&&this.yj()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Gq(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.G=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.op(h)&&h.responseXML?h.responseXML:null)&&(d2(b,h),g.K(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.fM.prototype.load.call(this);KHa(this,this.player.rb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.mq()&&(a=NHa(this,a));var e={format:"XML",onFinish:a,onError:function(){b.G=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.T().L.get(d);f&&OHa(e,f);f=f&&(f.Ru||f.Nr);if(!c.xk||f)c.ma?LHa(this,c.ma,e):(this.u=function(){b.gb(e)},this.player.addEventListener("videodatachange",this.u));
g.TL(this.player,this.B.element,4);this.Mw();(f=g.yG(c))&&THa(this,f);(f=g.zG(c))&&f.featuredChannel&&UHa(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.gb=function(a){var b=this.player.getVideoData();b.ma&&(this.u&&(this.player.removeEventListener("videodatachange",this.u),this.u=null),LHa(this,b.ma,a))};
g.k.unload=function(){this.player.Ue("annotations_module");for(var a=g.q(Object.keys(this.J)),b=a.next();!b.done;b=a.next())this.J[b.value].destroy();this.L=null;this.i&&(this.i.destroy(),this.i=null,h1(this.player));this.V=!1;this.G&&(this.G.abort(),this.G=null);this.J={};this.l.hide();g.fM.prototype.unload.call(this);this.B.detach();this.u&&(this.player.removeEventListener("videodatachange",this.u),this.u=null)};
g.k.fI=function(a){a===this.player.getVideoData().videoId&&(this.loaded?PHa(this):this.load())};
g.k.Ug=function(){return!!this.i&&this.i.isAvailable()};
g.k.yj=function(){this.Ug();return!!this.i&&this.i.u};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.Ug();this.i&&(a?c?P1(this.i,c,b):P1(this.i,"YOUTUBE_DRAWER_AUTO_OPEN",b):Q1(this.i))};
g.k.Gq=function(a,b){this.player.W(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.va=function(){this.player.T().L.unsubscribe("vast_info_card_add",this.fI,this);g.un(this.player.getRootNode(),g.mS.IV_DRAWER_OPEN);for(var a=this.X,b=0,c=a.length;b<c;b++)g.nq(a[b]);this.X.length=0;g.fM.prototype.va.call(this)};
g.k.createElement=function(a){a=new g.V(a);g.G(this,a);return a.element};g.lM.annotations_module=c2;g.lM.creatorendscreen=t1;})(_yt_player);
