(function(g){var window=this;'use strict';var i2=function(a,b){return b?a.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},j2=function(a){return g.aE(a)&&a.Z("web_player_i_see_captions_3")},k2=function(a){var b={languageCode:a.languageCode,
languageName:a.languageName,displayName:g.jF(a),kind:a.kind,name:a.name,id:a.id,is_servable:a.i,is_default:a.isDefault,is_translateable:a.isTranslateable,vss_id:a.vssId};a.translationLanguage&&(b.translationLanguage=a.translationLanguage);return b},l2=function(a){return a.translationLanguage?a.translationLanguage.languageCode:a.languageCode},ZHa=function(a,b){var c=new g.iF;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.kind=a.kind;c.isDefault=!1;c.i=a.i;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;return c},$Ha=function(){this.l=[];
this.i=[]},m2=function(a,b){return b?a.i.concat(a.l):a.i},n2=function(a,b){switch(b.kind){case "asr":aIa(b,a.l);
break;default:aIa(b,a.i)}},aIa=function(a,b){g.bb(b,function(c){return c?a.toString()===c.toString():!1})||b.push(a)},o2=function(){g.F.call(this);
this.l=new $Ha;this.C=[]},p2=function(a,b,c){o2.call(this,a);
this.audioTrack=c;this.i=null;this.C=b.FF},q2=function(){this.segments=[]},bIa=function(a,b){var c=g.ub(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.jb(a.segments,c),g.jb(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.rb(a.segments,c,0,b),g.rb(a.segments,c+1,0,b)))},r2=function(a,b,c,d,e,f){g.F.call(this);
this.policy=a;this.player=b;this.X=c;this.G=d;this.C=e;this.L=f;this.V=this.player.T();this.B=new q2;this.l=this.u=this.i=null;this.J=new g.J(this.PG,1E3,this);this.events=new g.VL(this);g.G(this,this.J);g.G(this,this.events);this.events.N(b,"SEEK_COMPLETE",this.pD);this.pD();this.PG()},cIa=function(a,b){var c=g.Jz(g.jA(b,{})),d={format:"RAW",
withCredentials:!0};a.C&&(d.responseType="arraybuffer");a.l=g.Bp(c,d,3,100).then(function(e){a:{var f=e.xhr;a.Ha();if(a.u){var h=!(a.C?f.response:f.responseText)||400<=f.status;if(e=g.SB(f)){f=g.jA(a.u,{});h=a.u;g.Qz(h.l,f,e);h.requestId=f.get("req_id");cIa(a,a.u);break a}h||null==a.G||(e=a.u.i[0],a.C?a.G(f.response,1E3*(e.startTime+a.player.Lc())):a.G(f.responseText,1E3*(e.startTime+a.player.Lc())))}a.u=null;a.l=null}});
a.u=b;bIa(a.B,a.u.i[0].Ia)},s2=function(a,b){o2.call(this,b.T());
this.i=a;this.I=b;this.u=null;this.B=!1;this.G=g.dE(this.I.T())&&!this.i.isManifestless},eIa=function(a,b){var c=[],d;
for(d in a.i.i)if(a.i.i.hasOwnProperty(d)){var e=a.i.i[d];if(g.gM(e,b||null)){var f=e.info.id,h=f,l="."+f,m="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind;else{e=f;var n=g.iGa.get(e);null==n&&(n=dIa[e]||dIa[e.replace(/-/g,"_")],g.iGa.set(e,n));h=n||h}c.push(new g.iF({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},fIa=function(a,b){return null!=b&&b in a.i.i?a.i.i[b]:null},gIa=function(a,b,c){var d=
[],e;
for(e in a.i.i)if(a.i.i.hasOwnProperty(e)){var f=a.i.i[e];if(g.gM(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},t2=function(a,b,c,d,e){o2.call(this,e||null);
this.videoId=b;this.nG=d;this.B={};this.i=null;b=c||g.cp(a).hl||"";b=b.split("_").join("-");this.u=g.ep(a,{hl:b})},u2=function(a){if(!hIa.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(iIa,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.substr(1),16);return[a>>16,a>>8&255,a&255]},v2=function(a,b,c,d,e,f){var h={};
g.Qa(h,b);g.Qa(h,a.params);g.Qa(h,c);var l={};g.Qa(l,b.Wc);a.params.Wc&&g.Qa(l,a.params.Wc);g.Qa(l,c.Wc);h.Wc=l;g.V.call(this,{D:"div",K:"caption-window",U:{id:"caption-window-"+a.id,dir:1===h.xf?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:h.lang},S:[{D:"span",K:"captions-text",U:{style:"word-wrap: normal; display: block;"}}]});this.C=[];this.ma=!1;this.l=a;this.xa=this.ra=null;this.playerWidth=e;this.playerHeight=f;this.G=null;this.maxWidth=.96*e;this.La=.96*f;this.i=h;this.kb=c;this.ya=
b;this.B=this.Ba("captions-text");this.Za=""!==this.B.style.getPropertyValue("box-decoration-break")||""!==this.B.style.getPropertyValue("-webkit-box-decoration-break");this.Ea=d/360*16;this.type=0;this.Na=this.Ea*jIa(l);a=new g.qu(this.element,!0);g.G(this,a);a.subscribe("dragstart",this.tL,this);a.subscribe("dragmove",this.sL,this);a.subscribe("dragend",this.rL,this);this.Xa=this.Ta=0;b="";this.i.windowOpacity&&(a=u2(this.i.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.i.windowOpacity+
")");a={"background-color":b,display:!1===this.i.isVisible?"none":"","text-align":kIa[this.i.textAlign]};this.Za&&(a["border-radius"]=b?this.Na/8+"px":"");if(this.u=2===this.l.params.xf||3===this.l.params.xf)b=this.element,c="vertical-rl",1===this.i.rC&&(c="vertical-lr"),g.ye&&(c="vertical-lr"===c?"tb-lr":"tb-rl"),g.lg(b,"-o-writing-mode",c),g.lg(b,"-webkit-writing-mode",c),g.lg(b,"writing-mode",c),g.lg(b,"text-orientation","upright"),g.K(b,"ytp-vertical-caption"),3===this.l.params.xf&&(g.lg(b,"text-orientation",
""),g.lg(b,"transform","rotate(180deg)"));g.lg(this.element,a);switch(this.i.Bh){case 0:case 1:case 2:g.K(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.K(this.element,"ytp-caption-window-bottom")}},jIa=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},lIa=function(a,b){var c={},d=b.background?b.background:a.i.Wc.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.i.Wc.backgroundOpacity;d=u2(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Za&&(c["box-decoration-break"]="clone",c["border-radius"]=a.Na/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.Ea*jIa(b)+"px";d=1;e=b.color||a.i.Wc.color;if(b.color||null!=b.textOpacity)e=u2(e),d=null==b.textOpacity?a.i.Wc.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=
e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.sz&&(h=e=b.sz);var l=a.Ea/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),r=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=r;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+n+"px "+
e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.zq()?'"Carrois Gothic SC", sans-serif-smallcaps':
'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.i.Wc.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.Ci&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]="underline");
b.WN&&(c.visibility="hidden");1===b.jG&&a.u&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.hE||g.Is,3===a.l.params.xf?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.Ui||2===b.Ui||3===b.Ui||4===b.Ui||5===b.Ui)if(g.hE)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.Ui){case 4:case 3:c["text-emphasis-position"]="under left";
c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},mIa=function(a){a.G=g.Fe("SPAN");
g.lg(a.G,{display:"block"});g.K(a.G,"caption-visual-line");a.B.appendChild(a.G)},nIa=function(a,b){var c=g.Fe("SPAN");
g.lg(c,{display:"inline-block","white-space":"pre-wrap"});g.lg(c,lIa(a,b));c.classList.add("ytp-caption-segment");a.G.appendChild(c);c.previousElementSibling&&(g.lg(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.lg(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},oIa=function(a,b,c){a.ma=a.ma||!!c;
var d={};g.Qa(d,a.i.Wc);g.Qa(d,c||b.i);g.Qa(d,a.kb.Wc);(c=!a.G)&&mIa(a);for(var e=a.ra&&a.xa&&g.Sb(d,a.xa)?a.ra:nIa(a,d),f="string"===typeof b.text,h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=0<l||!b.append,n=h[l];m&&!c?(mIa(a),e=nIa(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.Ge(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.hE||!g.pg(n.children[2],"text-emphasis")||(m=a.u?"padding-right":"padding-top",g.pg(n.children[2],"text-emphasis-position")&&(m=a.u?"padding-left":"padding-bottom"),
g.Ae?g.lg(e,m,"1em"):g.lg(e,m,"0.5em")))}a.xa=d;a.ra=e;a.C.push(b)},w2=function(a,b,c,d,e,f,h){v2.call(this,a,b,c,d,e,f,h);
this.type=1},x2=function(a,b,c,d,e,f,h){v2.call(this,a,b,c,d,e,f,h);
this.type=2;this.J=[];this.X=this.L=this.Da=0;this.Y=NaN;this.Ya=0;this.ib=null;this.Fa=new g.J(this.TQ,433,this);g.K(this.element,"ytp-caption-window-rollup");g.G(this,this.Fa);g.lg(this.element,"overflow","hidden")},pIa=function(a,b){if(!b)return"";
a.u&&1!==a.l.params.rC&&(b*=-1);return"translate"+(a.u?"X":"Y")+"("+b+"px)"},qIa=function(a){a.J=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.l.params.dl,c=0,d=0,e=a.J.length-1;c<b&&-1<e;){var f=a.J[e];d+=a.u?f.offsetWidth:f.offsetHeight;c++;e--}a.J.length<b&&(d*=b/a.J.length);a.L=d;b=Math;c=b.max;isNaN(a.Y)&&((d=a.i.Jl)?(e=g.Fe("SPAN"),g.Re(e,"\u2013".repeat(d)),g.lg(e,lIa(a,a.i.Wc)),a.B.appendChild(e),a.Y=e.offsetWidth,a.B.removeChild(e)):a.Y=0);d=a.B;a.X=c.call(b,a.Y,a.Ya,(a.u?d.offsetHeight:d.offsetWidth)+1)},rIa=function(a,b){qIa(a);
var c=a.J.reduce(function(e,f){return(a.u?f.offsetWidth:f.offsetHeight)+e},0);
c=a.L-c;if(c!==a.Da){var d=0<c&&0===a.Da;b||isNaN(c)||d||(g.K(a.element,"ytp-rollup-mode"),g.ln(a.Fa));g.lg(a.B,"transform",pIa(a,c));a.Da=c}qIa(a)},y2=function(a,b,c,d,e,f,h){f=void 0===f?!1:f;
h=void 0===h?null:h;g.Xv.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.i=h},z2=function(a,b,c,d,e){g.Xv.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.i=[]},sIa=function(a){var b="_"+A2++;
return new z2(0,0x8000000000000,0,b,a)},uIa=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(1===m.Gd){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[p.getAttribute("p")];l=tIa(l.textContent,n.textContent,p.textContent,f.textContent,h);return new y2(a,b,e,c,l,d,m)}switch(m.Gd){case 9:case 10:m.Ui=1;break;case 11:m.Ui=2;break;case 12:m.Ui=3;break;case 13:m.Ui=4;break;case 14:m.Ui=5}return new y2(a,b,e,c,l.textContent||"",d,m)},tIa=function(a,b,c,d,e){var f=g.zq(),h=
f?g.Fe("DIV"):g.Fe("RUBY"),l=g.Fe("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.Fe("DIV"):g.Fe("RP");a.textContent=b;h.appendChild(a);b=f?g.Fe("DIV"):g.Fe("RT");b.textContent=c;h.appendChild(b);c=e.Gd;if(10===c||11===c||12===c||13===c||14===c)if(g.lg(b,"text-emphasis-style","filled circle"),g.lg(b,"text-emphasis-color","currentcolor"),g.lg(b,"webkit-text-emphasis","filled circle"),11===e.Gd||13===e.Gd)g.lg(b,"webkit-text-emphasis-position","under left"),g.lg(b,"text-emphasis-position","under left");c=!0;if(4===e.Gd||7===e.Gd||12===e.Gd||
14===e.Gd)g.lg(h,"ruby-position","over"),g.lg(h,"-webkit-ruby-position","before");else if(5===e.Gd||6===e.Gd||11===e.Gd||13===e.Gd)g.lg(h,"ruby-position","under"),g.lg(h,"-webkit-ruby-position","after"),c=!1;e=f?g.Fe("DIV"):g.Fe("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.lg(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.lg(f,"display","none"),f=f.nextElementSibling,g.lg(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.lg(h.lastElementChild,"display","none"),d?(g.lg(h,"padding-top","0.6em"),g.lg(f,"top","0")):(g.lg(h,"padding-bottom","0.6em"),g.lg(f,"bottom","0")));return h},B2=function(){g.F.apply(this,arguments)},C2=function(a){B2.call(this);
this.C=a;this.B={};this.V={};this.X={};this.G="_"+A2++;this.L={};this.u=this.i=null;this.J=!0},D2=function(a,b){a=a.getAttribute(b);
if(null!=a)return Number(a)},E2=function(a,b){a=a.getAttribute(b);
if(null!=a)return"1"===a},F2=function(a,b){a=D2(a,b);
return void 0!==a?a:null},H2=function(a,b){a=a.getAttribute(b);
if(null!=a)return G2.test(a),a},vIa=function(a,b){var c={},d=b.getAttribute("ws");
g.Qa(c,d?a.X[d]:a.C);a=F2(b,"mh");null!=a&&(c.yq=a);a=F2(b,"ju");null!=a&&(c.textAlign=a);a=F2(b,"pd");null!=a&&(c.xf=a);a=F2(b,"sd");null!=a&&(c.rC=a);a=H2(b,"wfc");null!=a&&(c.windowColor=a);b=D2(b,"wfo");void 0!==b&&(c.windowOpacity=b/255);return c},wIa=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Qa(c,a.V[d]);a=F2(b,"ap");null!=a&&(c.Bh=a);a=D2(b,"cc");null!=a&&(c.Jl=a);a=D2(b,"ah");null!=a&&(c.Fg=a);a=D2(b,"rc");null!=a&&(c.dl=a);b=D2(b,"av");null!=b&&(c.Vi=b);return c},xIa=function(a,b,c,d){var e={};
g.Qa(e,wIa(a,b));g.Qa(e,vIa(a,b));d?g.Sb(e,a.C)?(d=a.G,e=a.C):d="_"+A2++:d=b.getAttribute("id")||"_"+A2++;a=D2(b,"t")+c;b=D2(b,"d")||0x8000000000000;if(2===e.xf||3===e.xf)c=e.dl,e.dl=e.Jl,e.Jl=c;return new z2(a,b,0,d,e)},I2=function(a){B2.call(this);
this.G=a;this.i=new Map;this.B=new Map;this.C=new Map;this.u=new Map},J2=function(a){a=g.de(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},yIa=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.B.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.C.get(b.wsWinStyleId));a=b.rcRowCount;void 0!==a&&(f.dl=a);b=b.ccColCount;void 0!==b&&(f.Jl=b);if(2===f.xf||3===f.xf)b=f.dl,f.dl=f.Jl,f.Jl=b;return new z2(c,d,0,e,f)},L2=function(){this.u=this.time=this.mode=this.l=0;
this.B=new K2(this);this.C=new K2(this);this.i=[];this.clear()},AIa=function(a,b,c){if(255===a&&255===b||!a&&!b)return{En:a,
El:b,result:0};a=zIa[a];b=zIa[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.isValid()&&c.El===d;if(d)return{En:a,El:b,result:1}}else if(b&128&&1<=a&&31>=a)return{En:a,El:b,result:2};return{En:a,El:b,result:3}},CIa=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.u&&a.reset(),a.B.l.clear(),a.C.l.clear()):(a.u=0,BIa(a.B,b,c,d))},DIa=function(a,b){a.i.sort(function(e,f){var h=e.time-f.time;
return 0===h?e.order-f.order:h});
for(var c=g.q(a.i),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?CIa(a,d.YE,d.ZE,b):1===d.type&&a.l&496&&BIa(a.C,d.YE,d.ZE,b);a.i.length=0},M2=function(){this.type=0},N2=function(){this.state=this.El=this.En=0},EIa=function(){this.timestamp=this.i=0},O2=function(a){this.C=a;
this.u=[];this.i=this.l=this.row=0;this.style=new M2;for(a=this.B=0;15>=a;a++){this.u[a]=[];for(var b=0;32>=b;b++)this.u[a][b]=new EIa}},P2=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.C.time+0,f="",h="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var r=a.u[m][p];
if(0!==r.i){0===c&&(c=m,d=p);n=String.fromCharCode(r.i);var t=r.timestamp;t<e&&(e=t);r.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((0===r.i||32===p)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.B(c,d,e,l,f)}else for(d=c=0,f=e=a.C.time+0,h=1;15>=h;++h)for(l="",m=1;32>=m;++m)if(p=a.u[h][m],r=p.i,0!==r&&(0===c&&(c=h,d=m),n=String.fromCharCode(r),t=p.timestamp,t<=e&&(e=t),l+=n,p.reset()),32===m||0===r)l&&b.B(c,d,e,f,l),e=f,l="",d=c=0},JIa=function(a,b){switch(a){case 0:return FIa[(b&127)-32];
case 1:return GIa[b&15];case 2:return HIa[b&31];case 3:return IIa[b&31]}return 0},Q2=function(a){return a.u[a.row][a.l]},R2=function(a,b,c){2<=b&&1<a.l&&(--a.l,Q2(a).i=0);
var d=Q2(a);d.timestamp=a.C.time+0;d.i=JIa(b,c);32>a.l&&a.l++},KIa=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var h=a.u[b+e][f],l=a.u[c+e][f];
h.i=l.i;h.timestamp=l.timestamp}},S2=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.u[b+d][e].reset()},T2=function(a){a.row=0<a.i?a.i:1;
a.l=1;S2(a,0,15)},U2=function(a){this.u=a;
this.C=0;this.style=new M2;this.G=new O2(this.u);this.J=new O2(this.u);this.text=new O2(this.u);this.l=this.G;this.B=this.J;this.i=this.l},V2=function(a,b,c){var d=a.l,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.i||(P2(d,c),T2(a.l),T2(a.B),d.row=15,d.i=b,e=!0)}a.style.set(3);a.i=d;a.i.style=a.style;a.u.mode=1<<d.B;e?d.l=1:d.i!==b&&(d.i>b?(P2(d,c),S2(d,d.row-d.i,b)):d.row<b&&(b=d.i),d.i=b)},LIa=function(a){a.style.set(1);
a.i=a.B;a.i.i=0;a.i.style=a.style;a.u.mode=1<<a.i.B},MIa=function(a){a.style.set(4);
a.i=a.text;a.i.style=a.style;a.u.mode=1<<a.i.B},K2=function(a){this.i=a;
this.C=0;this.u=new U2(this.i);this.G=new U2(this.i);this.l=new N2;this.B=this.u},BIa=function(a,b,c,d){a.l.update();
b=AIa(b,c,a.l);switch(b.result){case 0:return;case 1:case 2:return}var e=b.En;c=b.El;if(32<=e||!e)a.i.mode&a.i.l&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.B.i,b&96&&R2(a,0,b),c&96&&R2(a,0,c),0!==b&&0!==c&&3===a.style.type&&P2(a,d));else if(e&16)a:if(!a.l.matches(e,c)&&(b=a.l,b.En=e,b.El=c,b.state=2,b=e&8?a.G:a.u,a.B=b,a.i.mode=1<<(a.C<<2)+(b.C<<1)+(4===b.style.type?1:0),(a.i.mode|1<<(a.C<<2)+(b.C<<1)+(4!==b.style.type?1:0))&a.i.l))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.i;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.i&&(d=c.i,d===c.row))break;var f=1+c.row-c.i,h=1+d-c.i;KIa(c,h,f,c.i);b=f;e=c.i;h<f?(f=h+e-f,0<f&&(b+=f,e-=f)):(f=f+e-h,0<f&&(e-=f));S2(c,b,e)}}c.row=d;c.l=a+1}else switch(e&7){case 1:switch(c&112){case 32:R2(b.i,0,32);break a;case 48:57===c?(d=b.i,Q2(d).i=0,32>d.l&&d.l++):R2(b.i,1,c&15)}break;case 2:c&32&&R2(b.i,2,c&31);break;case 3:c&32&&R2(b.i,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:LIa(b);
break;case 33:d=b.i;1<d.l&&(--d.l,Q2(d).i=0);break;case 36:d=b.i;b=Q2(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.u[a][c]===b){for(;32>=c;c++)d.u[a][c].reset();break}break;case 37:V2(b,2,d);break;case 38:V2(b,3,d);break;case 39:V2(b,4,d);break;case 40:R2(b.i,0,32);break;case 41:b.style.set(2);b.i=b.l;b.i.i=0;b.i.style=b.style;b.u.mode=1<<b.i.B;break;case 42:d=b.text;d.i=15;d.style.set(4);T2(d);MIa(b);break;case 43:MIa(b);break;case 44:a=b.l;switch(b.style.get()){case 1:case 2:case 3:P2(a,d)}S2(a,
0,15);break;case 45:b:{a=b.i;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.l=1;break b}case 3:}2>a.i&&(a.i=2,a.row<a.i&&(a.row=a.i));b=a.row-a.i+1;P2(a,d);KIa(a,b,b+1,a.i-1);S2(a,a.row,1)}break;case 46:S2(b.B,0,15);break;case 47:P2(b.l,d),b.B.updateTime(b.u.time+0),d=b.B,b.B=b.l,b.l=d,LIa(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.i,32<(d.l+=c&3)&&(d.l=32)}}},NIa=function(){},W2=function(a,b,c){this.trackData=a;
this.G=c;this.version=this.C=this.u=this.byteOffset=0;this.i=new DataView(this.trackData);this.l=[]},X2=function(a){var b=a.byteOffset;
a.byteOffset+=1;return a.i.getUint8(b)},Y2=function(a){var b=a.byteOffset;
a.byteOffset+=4;return a.i.getUint32(b)},Z2=function(a,b){B2.call(this);
this.u=a;this.B=b;this.track="CC3"===this.B.languageName?4:0;this.i=new L2;this.i.l=1<<this.track},$2=function(a){if("string"===typeof a)return!1;
a=new W2(a,8,0);return OIa(a)},OIa=function(a){if(!(a.byteOffset<a.i.byteLength)||1380139777!==Y2(a))return!1;
a.version=X2(a);if(1<a.version)return!1;X2(a);X2(a);X2(a);return!0},a3=function(){B2.call(this)},PIa=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.Ci=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var p=h.childNodes[n];if(3===p.nodeType)p=new y2(b,c,d,e.id,p.nodeValue,f||0<n,g.Pb(l)?void 0:l),m.push(p),e.i.push(p);else{var r={};g.Qa(r,l);PIa(a,b,c,d,e,!0,p,r,m)}}},b3=function(a){var b=a.split(":");
a=0;b=g.q(b);for(var c=b.next();!c.done;c=b.next())a=60*a+Number(c.value);return 1E3*a},QIa=function(a,b,c,d){d=Object.assign({yq:0},d);
return new z2(a,b,c,"_"+A2++,d)},c3=function(a){g.F.call(this);
this.l=a;this.i=null},RIa=function(a,b){if("string"===typeof b||$2(b))return b;
var c=new DataView(b);if(8>=c.byteLength||1718909296!==c.getUint32(4))return"";c=g.bz(c,0,1835295092);if(!c||!c.size)return"";a=a.l.Z("html5_fix_mdat_offset_killswitch")?b.slice(c.dataOffset,c.dataOffset+c.size):b.slice(c.dataOffset,c.offset+c.size);return g.Ze(new Uint8Array(a))},TIa=function(a){var b={};
if(a=l2(a))b.lang=a,SIa.test(a)&&(b.xf=1);return b},f3=function(a){g.fM.call(this,a);
var b=this;this.I=a;this.i=this.I.T();this.videoData=this.I.getVideoData();this.Ya=this.I.Wa();this.B={Wc:{}};this.C={Wc:{}};this.Y=[];this.V={};this.Da={};this.X=!1;this.Ta=g.Eoa(this.videoData,this.I);this.Za=!!this.videoData.captionTracks.length;this.ib=!!this.videoData.Rh;this.Ua="3"===this.i.controlsType;this.u=this.J=this.L=this.Ea=this.Na=null;this.Fa=new c3(this.i);this.l=null;this.xa=new g.VL(this);this.La=new g.V({D:"div",K:"ytp-caption-window-container",U:{id:"ytp-caption-window-container"}});
var c=null,d=g.qo("yt-html5-player-modules::subtitlesModuleData");d&&(c=new g.Sn(d));this.storage=c;c=a.jd();d=!(null===c||void 0===c||!c.Ut());this.Xa=!(null===c||void 0===c||!c.Vt());this.G=this.Ua&&d&&!this.Ta;this.ra=!this.G&&this.Ua&&this.Xa&&this.Ta;g.G(this,this.Fa);this.G?this.ya=this.ma=null:(this.ma=new g.gn(this.IC,void 0,this),g.G(this,this.ma),this.ya=new g.J(this.iS,2E3,this),g.G(this,this.ya));g.G(this,this.xa);this.i.Z("caption_window_container_killswitch")||g.TL(this.player,this.La.element,
4);g.G(this,this.La);this.G||this.xa.N(a,"resize",this.KC);this.xa.N(a,"onPlaybackAudioChange",this.hP);this.xa.N(a,g.$v("captions"),function(e){b.qd(e)});
this.xa.N(a,g.aw("captions"),function(e){b.qf(e)});
d3(this,e3(this,"display-settings")||{})},UIa=function(a){if(1===a.i.Da||1===a.videoData.qp||"alwayson"===g.qG(a.videoData,"yt:cc"))return!0;
if(2===a.i.Da){var b;g.gE(a.i)?b=(0,g.eM)():b=e3(a,"module-enabled");if(null!=b)return!!b}if(a.videoData.captionTracks.length)var c=a.player.getAudioTrack().l;b=i2(a.player.getAudioTrack(),j2(a.i));var d=g.qG(a.videoData,"yt:cc");if(void 0===g3(a)){if("CAPTIONS_INITIAL_STATE_ON_RECOMMENDED"===b)return d?"on"===d:!0;if("CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED"===b)return"on"===d}else return"on"===d;return"ON"===c||"on"===g.qG(a.videoData,"yt:cc")},h3=function(a,b){if(a.l&&(void 0===b||!b)||!a.videoData.captionTracks.length)return!1;
a=a.player.getAudioTrack();return!!a.i||"FORCED_ON"===a.l},g3=function(a){var b=void 0,c=g.wr(g.ur.getInstance(),65);
if(g.gE(a.i)&&null!=c){if(null!=(0,g.eM)())return!1;b=!c}return b},j3=function(a,b){if(a.u){if(a.J&&a.J.B)return a.J.B;
b||(b=a.ib?!1:a.Za?!1:!0);b=m2(a.u.l,b);for(var c=[a.videoData.captionsLanguagePreference,a.i.captionsLanguagePreference,g.qG(a.videoData,"yt:cc_default_lang")],d=0;d<c.length;d++)for(var e=0;e<b.length;e++)if(l2(b[e])===c[d])return b[e];return a.J&&a.J.u?a.J.u:(c=b.find(function(f){return f.isDefault}))?c:b[0]||i3(a)}return null},i3=function(a){return a.J&&a.J.i},k3=function(a){var b=i3(a);
return!!b&&a.l===b},VIa=function(a,b){var c=a.I.jd().je().textTracks;
a=a.l.toString();for(var d=0;d<c.length;d++){var e=c[d];e.id===a&&(b?"showing"!==e.mode&&(e.mode="showing"):"showing"===e.mode&&(e.mode="disabled"))}},m3=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.X=c,a.X&&(g.gE(a.i)?(0,g.A0)(!!b):l3(a,"module-enabled",!!b)));a.l=b;h3(a)&&(a.l=i3(a));a.load()},WIa=function(a,b){a.i.Z("caption_window_container_killswitch")?g.TL(a.player,b,4):a.La.element.appendChild(b)},XIa=function(a,b){var c=a.Ya.getVideoContentRect(!0).height;
if(!c)return null;var d=a.l?l2(a.l):null;d&&SIa.test(d)&&(b.params.xf=1);d=a.Ya.getPlayerSize();switch(null!=b.params.yq?b.params.yq:1<b.i.length?1:0){case 1:return new w2(b,a.B,a.C,c,d.width,d.height,a.i.experiments);case 2:return new x2(b,a.B,a.C,c,d.width,d.height,a.i.experiments);default:return new v2(b,a.B,a.C,c,d.width,d.height,a.i.experiments)}},d3=function(a,b,c){c=void 0===c?!1:c;
var d=n3.Wc;a.B={};g.Qa(a.B,n3);a.B.Wc={};g.Qa(a.B.Wc,d);a.C={Wc:{}};var e=b.backgroundOverride?a.C:a.B,f=b.background||d.background;G2.test(f);e.Wc.background=f;e=b.colorOverride?a.C:a.B;f=b.color||d.color;G2.test(f);e.Wc.color=f;e=b.windowColorOverride?a.C:a.B;f=b.windowColor||n3.windowColor;G2.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.C:a.B;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.Wc.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.C:a.B;f=b.fontSizeIncrement;null==
f&&(f=d.fontSizeIncrement);e.Wc.fontSizeIncrement=f;f=b.fontStyleOverride?a.C:a.B;e=b.fontStyle;null==e&&(e=d.bold&&d.Ci?3:d.bold?1:d.Ci?2:0);f=f.Wc;switch(e){case 1:f.bold=!0;delete f.Ci;break;case 2:delete f.bold;f.Ci=!0;break;case 3:f.bold=!0;f.Ci=!0;break;default:delete f.bold,delete f.Ci}e=b.textOpacityOverride?a.C:a.B;f=b.textOpacity;null==f&&(f=d.textOpacity);e.Wc.textOpacity=f;e=b.windowOpacityOverride?a.C:a.B;f=b.windowOpacity;null==f&&(f=n3.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?
a.C:a.B;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.Wc.charEdgeStyle=f;e=b.fontFamilyOverride?a.C:a.B;f=b.fontFamily;null==f&&(f=d.fontFamily);e.Wc.fontFamily=f;a.loaded&&a.KC();c&&l3(a,"display-settings",b)},ZIa=function(a,b){b&&!a.L?(b=sIa({xf:0,
lang:"en"}),a.L=[b,new y2(b.start,b.end-b.start,0,b.id,"Captions look like this")],a.player.xd(a.L)):!b&&a.L&&(YIa(a,a.L),a.L=null)},YIa=function(a,b){a.player.Nf(b);
g.zb(b,function(c){g.kb(this.Y,c)},a);
g.hn(a.ma)},e3=function(a,b){if(!a.storage)return null;
try{var c=a.storage.get(b)}catch(d){a.storage.remove(b)}return c},l3=function(a,b,c){if(a.storage)try{a.storage.set(b,c)}catch(d){}};
g.uM.prototype.Or=g.ca(23,function(){this.ea();for(var a=g.re(document,"track",void 0,this.i),b=0;b<a.length;b++)g.Je(a[b])});
g.tR.prototype.Or=g.ca(22,function(){this.i.Or()});
g.uM.prototype.Vt=g.ca(21,function(){return!(!this.i.textTracks||!this.i.textTracks.addEventListener)});
g.tR.prototype.Vt=g.ca(20,function(){return this.i.Vt()});
g.uM.prototype.Ut=g.ca(19,function(){return!!this.i.textTracks});
g.tR.prototype.Ut=g.ca(18,function(){return this.i.Ut()});
g.uM.prototype.Fr=g.ca(17,function(a){this.ea();for(var b=0;b<a.length;b++)this.i.appendChild(a[b])});
g.tR.prototype.Fr=g.ca(16,function(a){this.i.Fr(a)});
g.Iy.prototype.Iv=g.ca(1,function(a){return(a=this.ri(a))?a.l:0});
g.VA.prototype.Iv=g.ca(0,function(){return 0});
var SIa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,dIa={aa:"Afar",ab:"Abkhazian",ace:"Achinese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",ale:"Aleut",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",arp:"Arapaho",ars:"Najdi Arabic",arw:"Arawak",
as:"Assamese",asa:"Asu",ast:"Asturian",av:"Avaric",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bas:"Basaa",bax:"Bamun",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bez:"Bena",bfd:"Bafut",bg:"Bulgarian",bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bkm:"Kom",bla:"Siksika",bm:"Bambara",bn:"Bangla",bo:"Tibetan",br:"Breton",bra:"Braj",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",
bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",ckb_Arab:"Central Kurdish (Arabic)",co:"Corsican",cop:"Coptic",cr:"Cree",crh:"Crimean Turkish",cs:"Czech",csb:"Kashubian",
cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",
en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fulah",ff_Adlm:"Fulah (Adlam)",ff_Latn:"Fulah (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",
fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hil:"Hiligaynon",hit:"Hittite",
hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",
kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",
ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Lahnda",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lkt:"Lakota",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",
mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"Maori",mic:"Mi'kmaq",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian (Moldova)",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",
mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",
nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",
rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Sakha",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",
sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",
su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",
tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vi:"Vietnamese",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",
xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};g.v(o2,g.F);g.k=o2.prototype;g.k.jw=function(){};
g.k.lw=function(){};
g.k.ql=function(){};
g.k.hq=function(){return""};
g.k.pI=function(){return!1};
g.k.va=function(){this.ql();g.F.prototype.va.call(this)};
g.v(p2,o2);p2.prototype.jw=function(a,b,c){var d=this;this.Ha();b=this.hq(a,b);this.ql();this.i=g.wp(b,{format:"RAW",onSuccess:function(e){d.i=null;c(e.responseText,a)},
withCredentials:!0})};
p2.prototype.lw=function(a){if(this.audioTrack)for(var b=g.q(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())n2(this.l,c.value);a()};
p2.prototype.hq=function(a,b){var c=a.url,d={fmt:b};if("srv3"===b||"3"===b||"json3"===b)g.zq()?Object.assign(d,{xorb:2,xobt:1,xovt:1}):Object.assign(d,{xorb:2,xobt:3,xovt:3});a.translationLanguage&&(d.tlang=l2(a));return g.ep(c,d)};
p2.prototype.ql=function(){this.i&&this.i.abort()};
q2.prototype.contains=function(a){a=g.ub(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
q2.prototype.length=function(){return this.segments.length/2};
g.v(r2,g.F);g.k=r2.prototype;g.k.va=function(){g.F.prototype.va.call(this);this.l&&this.l.cancel()};
g.k.pD=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.Lc();var b=this.i;this.i=g.$a(this.X.dm(a).i);b!==this.i&&this.L&&this.L()};
g.k.reset=function(){this.B=new q2;this.l&&(this.l.cancel(),this.l=null)};
g.k.PG=function(){this.Ha();var a;if(a=null!=this.i)a=this.i,a=a.i.wl(a);!a||this.l||this.i&&30<this.i.startTime-this.player.getCurrentTime()||(a=this.i,a=a.i.er(a),a.i[0].duration?(this.B.contains(a.i[0].Ia)||cIa(this,a),this.i=g.$a(a.i)):!g.R(this.V.experiments,"force_caption_seek_for_live_killswitch")&&this.i&&this.i.B&&this.i.B+this.player.Lc()<this.player.getCurrentTime()&&this.seekTo(this.player.getCurrentTime()));this.J.start()};
g.v(s2,o2);g.k=s2.prototype;g.k.jw=function(a,b,c){var d=this;this.ql();b=fIa(this,a.getId());b||(b=a.languageCode,b=this.i.isManifestless?gIa(this,b,"386"):gIa(this,b));if(b){var e=1E3*(b.index.Iv(b.index.xi())-b.index.jf(b.index.xi()));this.u=new r2(new g.Coa,this.I,b,function(f,h){c(f,a,h,e)},this.G||g.OA(b.info),function(){d.u&&d.u.reset();
d.B=!0})}};
g.k.pI=function(){var a=this.B;this.B=!1;return a};
g.k.lw=function(a){var b=this.G?[new g.iF({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.iF({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.i.isManifestless?eIa(this,"386"):eIa(this);b=g.q(b);for(var c=b.next();!c.done;c=b.next())n2(this.l,c.value);a()};
g.k.ql=function(){this.u&&(this.u.dispose(),this.u=null)};
g.k.hq=function(){return""};
g.v(t2,o2);t2.prototype.jw=function(a,b,c){var d=this;this.Ha();b=this.hq(a,b);this.ql();this.i=g.wp(b,{format:"RAW",onSuccess:function(e){d.i=null;c(e.responseText,a)},
withCredentials:!0})};
t2.prototype.lw=function(a){var b=this,c=this.u,d={type:"list",tlangs:1,v:this.videoId,vssids:1};this.nG&&(d.asrs=1);c=g.ep(c,d);this.ql();this.i=g.wp(c,{format:"RAW",onSuccess:function(e){b.i=null;if((e=e.responseXML)&&e.firstChild){for(var f=e.getElementsByTagName("track"),h=0;h<f.length;h++){var l=f[h],m=l.getAttribute("lang_code"),n=l.getAttribute("lang_translated"),p=l.getAttribute("name"),r=l.getAttribute("kind"),t=l.getAttribute("id"),u="true"===l.getAttribute("lang_default"),x="true"===l.getAttribute("cantran");
l=l.getAttribute("vss_id");n2(b.l,new g.iF({languageCode:m,languageName:n,name:p,kind:r,id:t,is_servable:!0,is_translateable:x,vss_id:l,is_default:u}))}e=e.getElementsByTagName("target");f=e.length;for(h=0;h<f;h++)m={languageCode:e[h].getAttribute("lang_code"),languageName:e[h].getAttribute("lang_translated"),languageOriginal:e[h].getAttribute("lang_original"),id:e[h].getAttribute("id"),isDefault:"true"===e[h].getAttribute("lang_default")},b.B[m.languageCode]=m.languageName,b.C.push(m)}a()},
withCredentials:!0})};
t2.prototype.hq=function(a,b){var c=this.u;b={v:this.videoId,type:"track",lang:a.languageCode,name:a.getName(),kind:a.kind,fmt:b};a.translationLanguage&&(b.tlang=l2(a));return c=g.ep(c,b)};
t2.prototype.ql=function(){this.i&&this.i.abort()};
var G2=/^#(?:[0-9a-f]{3}){1,2}$/i,iIa=/#(.)(.)(.)/,hIa=/^#(?:[0-9a-f]{3}){1,2}$/i;var kIa=["left","right","center","justify"];g.v(v2,g.V);g.k=v2.prototype;g.k.tL=function(a,b){var c=g.zg(this.element,this.element.parentElement);this.Ta=a-c.x;this.Xa=b-c.y;g.K(this.element,"ytp-dragging")};
g.k.sL=function(a,b){var c=g.Bg(this.element);a=a-this.Ta-.02*this.playerWidth;var d=b-this.Xa-.02*this.playerHeight,e=(a+c.width/2)/this.maxWidth*3;e=Math.floor(g.de(e,0,2));var f=(d+c.height/2)/this.La*3;f=Math.floor(g.de(f,0,2));b=e+3*f;a=(a+e/2*c.width)/this.maxWidth;a=100*g.de(a,0,1);c=(d+f/2*c.height)/this.La;c=100*g.de(c,0,1);this.l.params.Bh=b;this.l.params.Vi=c;this.l.params.Fg=a;this.i.Bh=b;this.i.Vi=c;this.i.Fg=a;this.ya.Bh=b;this.ya.Vi=c;this.ya.Fg=a;this.MI()};
g.k.rL=function(){g.un(this.element,"ytp-dragging")};
g.k.MI=function(){this.Jq(this.C)};
g.k.Vb=function(){return this.type};
g.k.Jq=function(a){var b=Math.min(this.RF(),this.maxWidth),c=this.QF(),d="";3===this.l.params.xf&&(d="rotate(180deg)");g.lg(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.fz(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.i.Fg+2;d=this.i.Bh;switch(d){case 0:case 3:case 6:(b=this.i.Wc.fontSizeIncrement)&&0<b&&2!==this.i.xf&&3!==
this.i.xf&&(e=Math.max(e/(1+2*b),2));a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.B.offsetWidth;b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.i.Vi+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.lg(this.element,
a)};
g.k.fz=function(a){var b;for(b=0;b<a.length&&a[b]===this.C[b];b++);if(this.ma||this.C.length>b)b=0,this.ma=!1,this.C=[],this.G=this.xa=this.ra=null,g.He(this.B);for(;b<a.length;b++)oIa(this,a[b])};
g.k.RF=function(){return 0};
g.k.QF=function(){return 0};
g.k.toString=function(){return g.V.prototype.toString.call(this)};g.v(w2,v2);w2.prototype.fz=function(a){var b=this.l.i;v2.prototype.fz.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.i===e)var d=f;else{d={};g.Qa(d,c.i);g.Qa(d,$Ia);var e=c.i;var f=d}oIa(this,c,d)}};
var $Ia={WN:!0};g.v(x2,v2);g.k=x2.prototype;g.k.MI=function(){this.Fa.zg()};
g.k.TQ=function(){g.un(this.element,"ytp-rollup-mode");this.Jq(this.ib,!0)};
g.k.QF=function(){return this.u?this.X:this.L};
g.k.RF=function(){return this.u?this.L:this.X};
g.k.Jq=function(a,b){this.ib=a;if(this.l.params.dl){for(var c=0,d=0;d<this.C.length&&c<a.length;d++)this.C[d]===a[c]&&c++;0<c&&c<a.length&&(a=this.C.concat(a.slice(c)));this.Ya=this.X;this.L=this.X=0;v2.prototype.Jq.call(this,a);rIa(this,b)}v2.prototype.Jq.call(this,a)};g.v(y2,g.Xv);y2.prototype.toString=function(){return g.Xv.prototype.toString.call(this)};g.v(z2,g.Xv);z2.prototype.toString=function(){return g.Xv.prototype.toString.call(this)};
var A2=0;g.v(B2,g.F);B2.prototype.l=function(){return[]};
B2.prototype.reset=function(){};g.v(C2,B2);C2.prototype.reset=function(){this.L={};this.u=this.i=null;this.J=!0};
C2.prototype.l=function(a,b){a=a.firstChild;a.getAttribute("format");b=b||0;Number.isFinite(b);a=Array.from(a.childNodes);a=g.q(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value,1===c.nodeType)switch(c.tagName){case "head":var d=c;break;case "body":var e=c}if(d)for(d=Array.from(d.childNodes),d=g.q(d),a=d.next();!a.done;a=d.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "pen":c=a.getAttribute("id");var f=this.B,h={},l=a.getAttribute("p");l&&g.Qa(h,this.B[l]);l=E2(a,"b");null!=l&&(h.bold=
l);l=E2(a,"i");null!=l&&(h.Ci=l);l=E2(a,"u");null!=l&&(h.underline=l);l=F2(a,"et");null!=l&&(h.charEdgeStyle=l);l=F2(a,"of");null!=l&&(h.offset=l);l=H2(a,"bc");null!=l&&(h.background=l);l=H2(a,"ec");null!=l&&(h.sz=l);l=H2(a,"fc");null!=l&&(h.color=l);l=F2(a,"fs");null!=l&&0!==l&&(h.fontFamily=l);l=D2(a,"sz");void 0!==l&&(h.fontSizeIncrement=l/100-1);l=D2(a,"bo");void 0!==l&&(h.backgroundOpacity=l/255);l=D2(a,"fo");void 0!==l&&(h.textOpacity=l/255);l=F2(a,"rb");null!=l&&10!==l&&0!==l&&(h.Gd=10<l?l-
1:l);a=F2(a,"hg");null!=a&&(h.jG=a);f[c]=h;break;case "ws":c=a.getAttribute("id");this.X[c]=vIa(this,a);break;case "wp":c=a.getAttribute("id"),this.V[c]=wIa(this,a)}if(e){d=[];e=Array.from(e.childNodes);e=g.q(e);for(a=e.next();!a.done;a=e.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "w":this.i=xIa(this,a,b,!1);(a=this.L[this.i.id])&&a.end>this.i.start&&(a.end=this.i.start);this.L[this.i.id]=this.i;d.push(this.i);break;case "p":l=b;c=[];f=a.getAttribute("w")||this.G;h=!!E2(a,"a");l=(D2(a,
"t")||0)+l;var m=D2(a,"d")||5E3;h||(!this.J&&this.u&&this.u.windowId===f&&this.u.end>l&&(this.u.end=l),this.u&&"\n"===this.u.text&&(this.u.text=""));var n=h?6:5,p=a.getAttribute("p");p=p?this.B[p]:null;var r=Array.from(a.childNodes);r.length&&(this.J=null!=a.getAttribute("d"));for(var t=0;t<r.length;t++){var u=r[t],x=void 0;0<t&&(h=!0);var y=void 0;1===u.nodeType&&(y=u);if(y&&"s"===y.tagName){if((u=(u=y.getAttribute("p"))?this.B[u]:null)&&u.Gd&&(1===u.Gd?(u=r.slice(t,t+4),4===u.length&&(x=uIa(l,m,
f,h,n,u,this.B),t+=3)):x=uIa(l,m,f,h,n,[y],this.B)),!x){var B=y;x=l;y=m;u=f;var H=h,E=n,I=B.textContent?B.textContent:"",Q=B.getAttribute("p");Q=Q?this.B[Q]:null;B=D2(B,"t")||0;x=new y2(x+B,y-B,E,u,I,H,Q)}}else x=new y2(l,m,n,f,u.textContent||"",h,p);c.push(x);this.u=x}if(0<c.length)for(c[0].windowId===this.G&&(this.i=xIa(this,a,b,!0),d.push(this.i)),a=g.q(c),c=a.next();!c.done;c=a.next())c=c.value,c.windowId=this.i.id,this.i.i.push(c),d.push(c)}b=d}else b=[];return b};var aJa=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.v(I2,B2);I2.prototype.reset=function(){this.u.clear()};
I2.prototype.l=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens){a=0;for(var d=g.q(c.pens),e=d.next();!e.done;e=d.next()){e=e.value;var f={},h=e.pParentId;h&&Object.assign(f,this.i.get(h));e.bAttr&&(f.bold=!0);e.iAttr&&(f.Ci=!0);e.uAttr&&(f.underline=!0);h=e.ofOffset;null!=h&&(f.offset=h);void 0!==e.szPenSize&&(f.fontSizeIncrement=e.szPenSize/100-1);h=e.etEdgeType;null!=h&&(f.charEdgeStyle=h);void 0!==e.ecEdgeColor&&(f.sz=J2(e.ecEdgeColor));h=e.fsFontStyle;null!=h&&0!==h&&(f.fontFamily=
h);void 0!==e.fcForeColor&&(f.color=J2(e.fcForeColor));void 0!==e.foForeAlpha&&(f.textOpacity=e.foForeAlpha/255);void 0!==e.bcBackColor&&(f.background=J2(e.bcBackColor));void 0!==e.boBackAlpha&&(f.backgroundOpacity=e.boBackAlpha/255);(h=e.rbRuby)&&10!==h&&(f.Gd=10<h?h-1:h,f.Ui=aJa.get(f.Gd));e.hgHorizGroup&&(f.jG=e.hgHorizGroup);this.i.set(a++,f)}}if(c.wsWinStyles)for(a=0,d=g.q(c.wsWinStyles),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wsParentId)?Object.assign(f,this.C.get(h)):Object.assign(f,
this.G),void 0!==e.mhModeHint&&(f.yq=e.mhModeHint),void 0!==e.juJustifCode&&(f.textAlign=e.juJustifCode),void 0!==e.pdPrintDir&&(f.xf=e.pdPrintDir),void 0!==e.sdScrollDir&&(f.rC=e.sdScrollDir),void 0!==e.wfcWinFillColor&&(f.windowColor=J2(e.wfcWinFillColor)),void 0!==e.wfoWinFillAlpha&&(f.windowOpacity=e.wfoWinFillAlpha/255),this.C.set(a++,f);if(c.wpWinPositions)for(a=0,d=g.q(c.wpWinPositions),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wpParentId)&&Object.assign(f,this.B.get(h)),void 0!==e.ahHorPos&&
(f.Fg=e.ahHorPos),void 0!==e.apPoint&&(f.Bh=e.apPoint),void 0!==e.avVerPos&&(f.Vi=e.avVerPos),void 0!==e.ccCols&&(f.Jl=e.ccCols),void 0!==e.rcRows&&(f.dl=e.rcRows),this.B.set(a++,f);if(c.events){a=[];c=g.q(c.events);for(d=c.next();!d.done;d=c.next()){var l=d.value;d=(l.tStartMs||0)+b;e=l.dDurationMs||0;if(l.id)f=String(l.id),d=yIa(this,l,d,e,f),a.push(d),this.u.set(f,d);else{l.wWinId?f=l.wWinId.toString():(f="_"+A2++,h=yIa(this,l,d,e,f),a.push(h),this.u.set(f,h));0===e&&(e=5E3);h=this.u.get(f);var m=
!!l.aAppend,n=m?6:5,p=l.segs,r=null;l.pPenId&&(r=this.i.get(l.pPenId));for(l=0;l<p.length;l++){var t=p[l],u=t.utf8;if(u){var x=t.tOffsetMs||0,y=null;t.pPenId&&(y=this.i.get(t.pPenId));if(2===(null!=h.params.yq?h.params.yq:1<h.i.length?1:0)&&m&&"\n"===u)continue;if(t=y&&1===y.Gd)if(t=l,t+3>=p.length||!p[t+1].pPenId||!p[t+2].pPenId||!p[t+3].pPenId)t=!1;else{var B=p[t+1].pPenId;(B=this.i.get(B))&&B.Gd&&2===B.Gd?(B=p[t+2].pPenId,B=this.i.get(B),!B||!B.Gd||3>B.Gd?t=!1:(B=p[t+3].pPenId,t=(B=this.i.get(B))&&
B.Gd&&2===B.Gd?!0:!1)):t=!1}if(t){x=p[l+1].utf8;t=p[l+3].utf8;B=p[l+2].utf8;var H=this.i.get(p[l+2].pPenId);u=tIa(u,x,B,t,H);m=new y2(d,e,n,f,u,m,y);l+=3}else m=new y2(d+x,e-x,n,h.id,u,m,y||r);m&&(a.push(m),h.i.push(m))}m=!0}}}b=a}else b=[];return b};L2.prototype.clear=function(){this.u=this.time=this.mode=0;this.i=[];this.reset()};
L2.prototype.reset=function(){this.mode=0;this.B.reset(0);this.C.reset(1)};
var zIa=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];M2.prototype.set=function(a){this.type=a};
M2.prototype.get=function(){return this.type};
N2.prototype.clear=function(){this.state=0};
N2.prototype.update=function(){this.state=2===this.state?1:0};
N2.prototype.isValid=function(){return 0!==this.state};
N2.prototype.matches=function(a,b){return this.isValid()&&a===this.En&&b===this.El};
EIa.prototype.reset=function(){this.timestamp=this.i=0};
O2.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.u[b][c].timestamp=a};
O2.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.u[b][c];a=0===d.i?a+"_":a+String.fromCharCode(d.i)}a+="\n"}return a};
O2.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.u[b][c].reset();this.B=a;this.i=0;this.l=this.row=1};
var FIa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],GIa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],HIa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],IIa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];U2.prototype.reset=function(a,b){this.C=b;this.style.set(2);this.l=this.G;this.B=this.J;this.i=this.l;var c=(a<<2)+(b<<1);this.G.reset(c);this.J.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
K2.prototype.reset=function(a){this.C=a;this.l.clear();this.B=this.u;this.u.reset(a,0);this.G.reset(a,1)};NIa.prototype.B=function(){};g.v(W2,NIa);W2.prototype.B=function(a,b,c,d,e){if(c<d){var f="_"+A2++;c=c/1E3-this.G;d=d/1E3-this.G;a=new z2(c,d-c,5,f,{textAlign:0,Bh:0,Fg:2.5*b,Vi:5.33*a});e=new y2(c,d-c,5,f,e);this.l.push(a);this.l.push(e)}};
g.v(Z2,B2);Z2.prototype.l=function(a){a=new W2(a,a.byteLength,this.u);if(OIa(a)){for(;a.byteOffset<a.i.byteLength;)for(0===a.version?a.u=Y2(a)*(1E3/45):1===a.version&&(a.u=4294967296*Y2(a)+Y2(a)),a.C=X2(a);0<a.C;a.C--){var b=X2(a),c=X2(a),d=X2(a);b&4&&(b&3)===this.track&&(0===this.track||1===this.track)&&(b=this.i,b.i.push({time:a.u,type:this.track,YE:c,ZE:d,order:b.i.length}))}DIa(this.i,a);return a.l}return[]};
Z2.prototype.reset=function(){this.i.clear()};g.v(a3,B2);
a3.prototype.l=function(a,b){var c=[];a=a.split(bJa);for(var d=1;d<a.length;d++){var e=a[d],f=b;if(""!==e&&!cJa.test(e)){var h=o3.exec(e);if(h&&4<=h.length){var l=b3(h[1]),m=b3(h[2])-l;l+=f;var n=(h=h[3])?h.split(" "):[];h={};var p=null;var r="";var t=null,u="";n=g.q(n);for(var x=n.next();!x.done;x=n.next())if(x=x.value.split(":"),2===x.length){var y=x[1];switch(x[0]){case "line":x=y.split(",");x[0].endsWith("%")&&(p=x[0],h.Vi=Number.parseInt(p,10),2===x.length&&(r=x[1].trim()));break;case "position":x=
y.split(",");t=x[0];h.Fg=Number.parseInt(t,10);2===x.length&&(u=x[1].trim());break;case "align":switch(y){case "start":h.textAlign=0;break;case "middle":h.textAlign=2;break;case "end":h.textAlign=1}}}p||r||(r="end");if(!t)switch(h.textAlign){case 0:h.Fg=0;break;case 1:h.Fg=100;break;case 2:h.Fg=50}if(null!=h.textAlign){p=0;switch(r){case "center":p+=3;break;case "end":p+=6;break;default:p+=0}switch(u){case "line-left":p+=0;break;case "center":p+=1;break;case "line-right":p+=2;break;default:switch(h.textAlign){case 0:p+=
0;break;case 2:p+=1;break;case 1:p+=2}}r=0>p||8<p?7:p;h.Bh=r}e=e.substring(o3.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");u=h;h=e;e={};if(0>h.indexOf("<")&&0>h.indexOf("&"))f=QIa(l,m,5,u),m=new y2(l,m,5,f.id,h,!1,g.Pb(e)?void 0:e),c.push(f),c.push(m),f.i.push(m);else for(r=h.split(dJa),1===r.length?(h=5,u=QIa(l,m,h,u)):(p=h=6,u=Object.assign({Jl:32},u),u=new z2(l,m,p,"_"+A2++,u)),c.push(u),p=l,t=0;t<r.length;t++)n=r[t],0===t%2?(x=g.U_("<html>"+n+"</html>"),x.getElementsByTagName("parsererror").length?
(y=x.createElement("span"),y.appendChild(x.createTextNode(n))):y=x.firstChild,PIa(this,p,m-(p-l),h,u,0<t,y,e,c)):p=b3(n)+f}o3.lastIndex=0}}return c};
var cJa=/^NOTE/,bJa=/(?:\r\n|\r|\n){2,}/,o3=/^((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})[\t ]+--\x3e[\t ]+((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})(?:[\t ]*)(.*)(?:\r\n|\r|\n)/gm,dJa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.wR.Wv(a3,{l:"wvppt"});g.v(c3,g.F);c3.prototype.clear=function(){this.i&&this.i.dispose();this.i=null};
c3.prototype.reset=function(){this.i&&this.i.reset()};
c3.prototype.va=function(){g.F.prototype.va.call(this);this.clear()};var n3={windowColor:"#080808",windowOpacity:0,textAlign:2,Bh:7,Fg:50,Vi:100,Wc:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.v(f3,g.fM);g.k=f3.prototype;g.k.va=function(){if(this.G||this.ra){var a=this.I.jd();a&&!a.Ha()&&a.Or()}else ZIa(this,!1);g.fM.prototype.va.call(this)};
g.k.Wo=function(){if(this.Ua)return this.G||this.ra;var a=i2(this.player.getAudioTrack(),j2(this.i));return"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===a?!0:"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===a?h3(this):g3(this)||h3(this)?!0:UIa(this)};
g.k.load=function(){var a=this;g.fM.prototype.load.call(this);var b=!g.R(this.i.experiments,"web_player_captions_track_list_changed_killswitch");this.J=this.player.getAudioTrack();if(this.u)this.l&&(this.Fa.clear(),this.G?VIa(this,!0):3!==this.player.getPresentingPlayerType()&&this.u.jw(this.l,"json3",function(d,e,f,h){if(d){a.u.pI()&&(a.Y=[],a.I.Ue("captions"),g.hn(a.ma),a.Fa.reset());var l=a.Fa;f=f||0;h=h||0;if(l.l.Z("html5_disable_rawcc_killswitch")){if("string"!==typeof d){var m=new DataView(d);
8<=m.byteLength&&1718909296===m.getUint32(4)&&(m=g.bz(m,0,1835295092),d=l.l.Z("html5_fix_mdat_offset_killswitch")?d.slice(m.dataOffset,m.dataOffset+m.size):d.slice(m.dataOffset,m.offset+m.size),$2(d)||(d=g.Ze(new Uint8Array(d))))}}else d=RIa(l,d);if(d)try{if("string"!==typeof d){var n=d,p=f,r=h;if(!$2(n))throw Error("Invalid binary caption track data");l.i||(l.i=new Z2(r,e));var t=l.i.l(n,p)}else{if("WEBVTT"===d.substring(0,6))e=d,r=f,l.i||(l.i=new a3),p=l.i.l(e,r),.01>Math.random()&&g.Tu(Error("Deprecated subtitles format in web player: WebVTT")),
n=p;else b:{p=d;if("{"===p[0])try{l.i||(l.i=new I2(TIa(e)));n=l.i.l(p,f);break b}catch(E){g.Su(E);n=[];break b}r=g.U_(p);if(!r||!r.firstChild){var u=Error("Invalid caption track data");u.params=p;throw u;}if("timedtext"===r.firstChild.tagName){if(3===Number(r.firstChild.getAttribute("format"))){l.i||(l.i=new C2(TIa(e),l.l));n=l.i.l(r,f);break b}var x=Error("Unsupported subtitles format in web player (Format2)");x.params=p;throw x;}if("transcript"===r.firstChild.tagName){var y=Error("Unsupported subtitles format in web player (Format1)");
y.params=p;throw y;}var B=Error("Invalid caption track data");B.params=p;throw B;}t=n}var H=t}catch(E){g.Su(E),l.clear(),H=[]}else H=[];a.player.xd(H);!a.X||a.ra||k3(a)||g.PD(a.i)||g.FD(a.i)||(g.mn(a.ya),H=sIa({Bh:0,Fg:5,Vi:5,dl:2,textAlign:0,xf:0,lang:"en"}),a.Ea=[H],l=["Click "," for settings"],a.Na||(t=new g.ZJ(g.oK()),g.G(a,t),a.Na=t.element),t=H.end-H.start,(e=g.jF(a.l))&&a.Ea.push(new y2(H.start,t,0,H.id,e)),a.Ea.push(new y2(H.start,t,0,H.id,l[0]),new y2(H.start,t,0,H.id,a.Na,!0),new y2(H.start,
t,0,H.id,l[1],!0)),a.player.xd(a.Ea),g.ln(a.ya));!a.X||a.ra||k3(a)||(g.gE(a.i)?(0,g.A0)(!0):l3(a,"module-enabled",!0),a.J&&(a.J.B=a.l),a.player.hp());a.X=!1}}),!b||this.G||this.ra||k3(this)||this.player.Ma("captionschanged",k2(this.l))),b||(this.l&&!k3(this)?this.player.Ma("captionschanged",k2(this.l)):this.player.Ma("onCaptionsTrackListChanged"));
else{var c;this.Ta?c=new s2(this.videoData.i,this.player):this.Za?c=new p2(this.i,this.videoData,this.player.getAudioTrack()):c=new t2(this.videoData.Rh,this.videoData.videoId,this.videoData.captionsLanguagePreference||this.i.captionsLanguagePreference||g.qG(this.videoData,"yt:cc_default_lang")||this.i.xc,this.videoData.Ty,this.i);this.u=c;g.G(this,this.u);c.lw(function(){var d=i2(a.player.getAudioTrack(),j2(a.i)),e;"CAPTIONS_INITIAL_STATE_UNKNOWN"===d?g3(a)||a.X||UIa(a)?e=j3(a,a.X):h3(a)&&(e=i3(a)):
"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===d?e=j3(a,a.X):"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===d&&h3(a)&&(e=i3(a));if(a.G||a.ra){var f=m2(a.u.l,!0);d=[];for(var h=0;h<f.length;h++){var l=f[h],m=g.Fe("TRACK");m.setAttribute("kind","subtitles");m.setAttribute("label",g.jF(l));m.setAttribute("srclang",l2(l));m.setAttribute("id",l.toString());a.ra||m.setAttribute("src",a.u.hq(l,"vtt"));l===e&&m.setAttribute("default","1");d.push(m)}e=a.I.jd();e.Fr(d);e=e.je();a.Xa&&a.xa.N(e.textTracks,"change",a.xR)}else!a.l&&
e&&m3(a,e),a.player.Ma("onCaptionsTrackListChanged"),a.player.Ma("onApiChange")})}};
g.k.unload=function(){this.G&&this.l?VIa(this,!1):(this.ya&&g.mn(this.ya),this.player.Ue("captions"),this.Y=[],this.u&&this.u.ql(),this.Fa.clear(),this.L&&this.player.xd(this.L),this.KC());g.fM.prototype.unload.call(this);this.player.hp();this.player.Ma("captionschanged",{})};
g.k.create=function(){this.Wo()&&this.load()};
g.k.xR=function(){for(var a=this.I.jd().je().textTracks,b=null,c=0;c<a.length;c++)if("showing"===a[c].mode)a:{b=a[c].id;var d=m2(this.u.l,!0);for(var e=0;e<d.length;e++)if(d[e].toString()===b){b=d[e];break a}b=null}(this.loaded?this.l:null)!==b&&m3(this,b,!0)};
g.k.YS=function(){!this.l&&this.G||this.unload()};
g.k.qd=function(a){this.Y.push(a);g.hn(this.ma)};
g.k.qf=function(a){g.kb(this.Y,a);this.u instanceof s2&&this.u.G&&this.player.Nf([a]);g.hn(this.ma)};
g.k.cS=function(a){if(a instanceof z2){var b=this.V[a.id];b&&b.l!==a&&(b.dispose(),delete this.V[a.id],b=null);b||(b=XIa(this,a))&&(this.V[a.id]=b)}else b=a.windowId,this.Da[b]||(this.Da[b]=[]),this.Da[b].push(a)};
g.k.getCaptionWindowContainerId=function(){return this.La.element.id};
g.k.iS=function(){YIa(this,this.Ea);this.Ea=null};
g.k.IC=function(){var a=this;this.ma.stop();g.Qb(this.Da);this.Y.sort(g.Zv);var b=this.Y;if(this.L){var c=g.Ke(b,function(d){return-1===this.L.indexOf(d)},this);
c.length&&(b=c)}g.zb(b,this.cS,this);g.Bb(this.V,function(d,e){a.Da[e]?(d.element.parentNode||(d instanceof x2||d instanceof w2||g.Eb(a.V,function(f,h){h!==e&&f.l.params.Bh===d.l.params.Bh&&f.l.params.Fg===d.l.params.Fg&&f.l.params.Vi===d.l.params.Vi&&(f.dispose(),delete a.V[h]);return h===e},a),WIa(a,d.element)),d.Jq(a.Da[e])):(d.dispose(),delete a.V[e])},this)};
g.k.mS=function(){d3(this,{},!0);g.R(this.i.experiments,"web_player_disable_publish_captions_settings_changed_on_reset")||this.player.Ma("captionssettingschanged")};
g.k.wN=function(){var a=n3.Wc;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.Ci?3:a.bold?1:a.Ci?2:0,textOpacity:a.textOpacity,windowColor:n3.windowColor,windowOpacity:n3.windowOpacity};var b=e3(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.FJ=function(a,b){var c={};g.Qa(c,e3(this,"display-settings"));g.Qa(c,a);d3(this,c,b);this.player.Ma("captionssettingschanged")};
g.k.KC=function(){!this.G&&this.loaded&&(g.Bb(this.V,function(a,b){a.dispose();delete this.V[b]},this),this.IC())};
g.k.Ke=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.de(b,-2,4);this.FJ({fontSizeIncrement:c});return c;case "reload":b&&!this.G&&m3(this,this.l,!0);break;case "stickyLoading":void 0!==b&&this.i.u&&(g.gE(this.i)?(0,g.A0)(!!b):l3(this,"module-enabled",!!b));break;case "track":if(!this.u)return{};if(b){if(this.G)break;if(!g.Ma(b))break;if(g.Pb(b)){m3(this,null,!0);break}a=m2(this.u.l,!0);for(var d=0;d<a.length;d++){var e=a[d];e.languageCode!==b.languageCode||c&&e.languageName!==
b.languageName||(c=b.translationLanguage?ZHa(e,b.translationLanguage):e)}!c||c===this.l&&this.loaded||(b=(0,g.voa)(),a=l2(c),b.length&&a===b[b.length-1]||(b.push(a),(0,g.XFa)(b)),m3(this,c,!0))}else return this.loaded&&this.l&&!k3(this)?k2(this.l):{};return"";case "tracklist":return this.u?g.Pc(m2(this.u.l,!(!b||!b.includeAsr)),function(f){return k2(f)}):[];
case "translationLanguages":return this.u?this.u.C.map(function(f){return Object.assign({},f)}):[];
case "sampleSubtitles":this.G||void 0===b||ZIa(this,!!b)}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.i.u&&a.push("stickyLoading");return a};
g.k.tA=function(){var a=this.l;return a?{cc:a.vssId}:{}};
g.k.LS=function(){this.loaded&&this.l&&!k3(this)?(g.gE(this.i)?(0,g.A0)(!1):l3(this,"module-enabled",!1),this.unload(),h3(this,!0)&&m3(this,i3(this),!1)):m3(this,k3(this)||!this.l?j3(this,!0):this.l,!0)};
g.k.hP=function(){var a=k3(this);h3(this,a)?m3(this,this.player.getAudioTrack().i,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.Wo()&&(a?m3(this,j3(this),!1):this.load()))};
g.wR.Wv(f3,{IC:"smucd"});g.lM.captions=f3;})(_yt_player);
