(function(g){var window=this;'use strict';var fKa=function(a,b){return g.Mb(a,b)},gKa=function(a){if(a instanceof g.$i)return a;
if("function"==typeof a.uh)return a.uh(!1);if(g.La(a)){var b=0,c=new g.$i;c.next=function(){for(;;){if(b>=a.length)throw g.In;if(b in a)return a[b++];b++}};
return c}throw Error("Not implemented");},hKa=function(a,b,c){if(g.La(a))try{g.zb(a,b,c)}catch(d){if(d!==g.In)throw d;
}else{a=gKa(a);try{for(;;)b.call(c,a.next(),void 0,a)}catch(d){if(d!==g.In)throw d;}}},G4=function(a,b,c){a.l.set(b,c)},H4=function(a){G4(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^g.Ra()).toString(36));
return a},I4=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.bn(a.l,b,c)},iKa=function(a,b){var c=[];
hKa(b,function(d){try{var e=g.Yn.prototype.l.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.Xn(e)&&c.push(d)},a);
return c},jKa=function(a,b){b=iKa(a,b);
g.zb(b,function(c){g.Yn.prototype.remove.call(this,c)},a)},kKa=function(a){if(a.V){if(a.V.locationOverrideToken)return{locationOverrideToken:a.V.locationOverrideToken};
if(null!=a.V.latitudeE7&&null!=a.V.longitudeE7)return{latitudeE7:a.V.latitudeE7,longitudeE7:a.V.longitudeE7}}return null},lKa=function(a,b){g.fb(a,b)||a.push(b)},J4=function(a){var b=0,c;
for(c in a)b++;return b},mKa=function(a,b){b=b instanceof g.Cc?b:g.Jc(b,/^data:image\//i.test(b));
a.src=g.Ec(b)},nKa=function(a){try{return g.A.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},oKa=function(a){if(a.Cg&&"function"==typeof a.Cg)return a.Cg();
if("string"===typeof a)return a.split("");if(g.La(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Ib(a)},pKa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.La(a)||"string"===typeof a)g.zb(a,b,void 0);else{if(a.Fh&&"function"==typeof a.Fh)var c=a.Fh();else if(a.Cg&&"function"==typeof a.Cg)c=void 0;else if(g.La(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Kb(a);d=oKa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},qKa=function(a,b,c,d){var e=new g.Qm(null,void 0);
a&&g.Rm(e,a);b&&g.Sm(e,b);c&&g.Tm(e,c);d&&(e.J=d);return e},K4=function(){},L4=function(a,b){g.Sq[a]=!0;
var c=g.Qq();c&&c.publish.apply(c,arguments);g.Sq[a]=!1},M4=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Nm;a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",rKa(this,a.capabilities||""),sKa(this,a.experiments||""))},rKa=function(a,b){a.capabilities.clear();
g.Ke(b.split(","),g.Pa(fKa,tKa)).forEach(function(c){a.capabilities.add(c)})},sKa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},N4=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||"";this.idType=a.screenIdType||"normal"},O4=function(a,b){return!!b&&(a.id==b||a.uuid==b)},uKa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid,screenIdType:a.idType}},vKa=function(a){return new N4(a)},wKa=function(a){return Array.isArray(a)?g.Pc(a,vKa):[]},P4=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+((a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+",idType:"+a.idType+"}"):"null"},Q4=function(a){return Array.isArray(a)?"["+g.Pc(a,P4).join(",")+"]":"null"},R4=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,
function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},xKa=function(a){return g.Pc(a,function(b){return{key:b.id,
name:b.name}})},S4=function(a,b){return g.bb(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},T4=function(a,b){return g.bb(a,function(c){return O4(c,b)})},yKa=function(){var a=(0,g.lv)();
a&&jKa(a,a.i.uh(!0))},U4=function(){var a=g.ov("yt-remote-connected-devices")||[];
g.wb(a);return a},zKa=function(a){if(g.gb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return g.Pc(a,function(d,e){return 0==e?d:d.substring(c.length)})},AKa=function(a){g.nv("yt-remote-connected-devices",a,86400)},W4=function(){if(V4)return V4;
var a=g.ov("yt-remote-device-id");a||(a=R4(),g.nv("yt-remote-device-id",a,31536E3));for(var b=U4(),c=1,d=a;g.fb(b,d);)c++,d=a+"#"+c;return V4=d},X4=function(){var a=U4(),b=W4();
g.fb(a,b);g.rv()&&g.yb(a,b);a=zKa(a);if(g.gb(a))try{g.Ho("remote_sid")}catch(c){}else try{g.Fo("remote_sid",a.join(","),-1)}catch(c){}},BKa=function(){return g.ov("yt-remote-session-browser-channel")},CKa=function(){return g.ov("yt-remote-local-screens")||[]},DKa=function(){g.nv("yt-remote-lounge-token-expiration",!0,86400)},EKa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=g.Pc(CKa(),function(d){return d.loungeToken}),c=g.Pc(a,function(d){return d.loungeToken});
g.jh(c,function(d){return!g.fb(b,d)})&&DKa();
g.nv("yt-remote-local-screens",a,31536E3)},FKa=function(a,b){g.nv("yt-remote-session-browser-channel",a);
g.nv("yt-remote-session-screen-id",b);a=U4();b=W4();g.fb(a,b)||a.push(b);AKa(a);X4()},Y4=function(a){a||(g.qv("yt-remote-session-screen-id"),g.qv("yt-remote-session-video-id"));
X4();a=U4();g.kb(a,W4());AKa(a)},GKa=function(){if(!Z4){var a=g.qo();
a&&(Z4=new g.Sn(a))}},HKa=function(){GKa();
return Z4?!!Z4.get("yt-remote-use-staging-server"):!1},$4=function(){var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);
return a?parseInt(a[1],10):0},IKa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},JKa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},a5=function(a){a.length?KKa(a.shift(),function(){a5(a)}):b5()},LKa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},KKa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);g.jd(d,g.jg(a));(document.head||document.documentElement).appendChild(d)},MKa=function(){var a=$4(),b=[];
if(1<a){var c=a-1;b.push("//www.gstatic.com/eureka/clank/"+a+"/cast_sender.js");b.push("//www.gstatic.com/eureka/clank/"+c+"/cast_sender.js")}return b},b5=function(){var a=JKa();
a&&a(!1,"No cast extension found")},c5=function(){if(NKa){var a=2,b=JKa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;KKa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",b5,c)}},OKa=function(){c5();
var a=MKa();a.push("//www.gstatic.com/eureka/clank/cast_sender.js");a5(a)},QKa=function(){c5();
var a=MKa();a.push.apply(a,g.ma(PKa.map(LKa)));a.push("//www.gstatic.com/eureka/clank/cast_sender.js");a5(a)},d5=function(a,b,c){g.F.call(this);
this.G=null!=c?(0,g.C)(a,c):a;this.Hf=b;this.C=(0,g.C)(this.OL,this);this.i=!1;this.l=0;this.u=this.yb=null;this.B=[]},e5=function(a,b,c){g.F.call(this);
this.B=null!=c?a.bind(c):a;this.Hf=b;this.u=null;this.i=!1;this.l=0;this.yb=null},f5=function(a){a.yb=g.Lm(function(){a.yb=null;
a.i&&!a.l&&(a.i=!1,f5(a))},a.Hf);
var b=a.u;a.u=null;a.B.apply(null,b)},g5=function(a){if(g.A.JSON)try{return g.A.JSON.parse(a)}catch(b){}return nKa(a)},h5=function(){},i5=function(a,b){if("function"!==typeof a)throw Error("Fn must not be null and must be a function");
return g.A.setTimeout(function(){a()},b)},k5=function(a){j5.dispatchEvent(new RKa(j5,a))},RKa=function(a,b){g.Hl.call(this,"statevent",a);
this.stat=b},l5=function(){},SKa=function(){},UKa=function(a){return(a=TKa(a))?new ActiveXObject(a):new XMLHttpRequest},TKa=function(a){if(!a.l&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.l=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.l},m5=function(a,b,c,d){this.i=a;
this.l=b;this.L=c;this.J=d||1;this.C=45E3;this.B=new g.V_(this);this.u=new g.Km;this.u.setInterval(250)},WKa=function(a,b,c){a.Pq=1;
a.Fl=H4(b.clone());a.Po=c;a.G=!0;VKa(a,null)},n5=function(a,b,c,d,e){a.Pq=1;
a.Fl=H4(b.clone());a.Po=null;a.G=c;e&&(a.SI=!1);VKa(a,d)},VKa=function(a,b){a.Fq=Date.now();
o5(a);a.Jm=a.Fl.clone();I4(a.Jm,"t",a.J);a.ou=0;a.Ie=a.i.Hz(a.i.Pt()?b:null);0<a.Gy&&(a.Xw=new e5((0,g.C)(a.NJ,a,a.Ie),a.Gy));a.B.Oa(a.Ie,"readystatechange",a.dS);b=a.cn?g.Tb(a.cn):{};a.Po?(a.Lx="POST",b["Content-Type"]="application/x-www-form-urlencoded",a.Ie.send(a.Jm,a.Lx,a.Po,b)):(a.Lx="GET",a.SI&&!g.Ae&&(b.Connection="close"),a.Ie.send(a.Jm,a.Lx,null,b));a.i.Gi(1)},ZKa=function(a,b,c){for(var d=!0;!a.In&&a.ou<c.length;){var e=XKa(a,c);
if(e==p5){4==b&&(a.Al=4,k5(15),d=!1);break}else if(e==YKa){a.Al=4;k5(16);d=!1;break}else q5(a,e)}4==b&&0==c.length&&(a.Al=1,k5(17),d=!1);a.Ti=a.Ti&&d;d||(r5(a),s5(a))},XKa=function(a,b){var c=a.ou,d=b.indexOf("\n",c);
if(-1==d)return p5;c=Number(b.substring(c,d));if(isNaN(c))return YKa;d+=1;if(d+c>b.length)return p5;b=b.substr(d,c);a.ou=d+c;return b},aLa=function(a,b){a.Fq=Date.now();
o5(a);var c=b?window.location.hostname:"";a.Jm=a.Fl.clone();G4(a.Jm,"DOMAIN",c);G4(a.Jm,"t",a.J);try{a.Xi=new ActiveXObject("htmlfile")}catch(m){r5(a);a.Al=7;k5(22);s5(a);return}var d="<html><body>";if(b){var e="";for(b=0;b<c.length;b++){var f=c.charAt(b);if("<"==f)f=e+"\\x3c";else if(">"==f)f=e+"\\x3e";else{if(f in t5)f=t5[f];else if(f in $Ka)f=t5[f]=$Ka[f];else{var h=f.charCodeAt(0);if(31<h&&127>h)var l=f;else{if(256>h){if(l="\\x",16>h||256<h)l+="0"}else l="\\u",4096>h&&(l+="0");l+=h.toString(16).toUpperCase()}f=
t5[f]=l}f=e+f}e=f}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.fd(g.ec("b/12014412"),d+"</body></html>");a.Xi.open();a.Xi.write(g.bd(c));a.Xi.close();a.Xi.parentWindow.m=(0,g.C)(a.BR,a);a.Xi.parentWindow.d=(0,g.C)(a.eI,a,!0);a.Xi.parentWindow.rpcClose=(0,g.C)(a.eI,a,!1);c=a.Xi.createElement("DIV");a.Xi.parentWindow.document.body.appendChild(c);d=g.Ic(a.Jm.toString());d=g.qd(g.Ec(d));d=g.fd(g.ec("b/12014412"),'<iframe src="'+d+'"></iframe>');g.gd(c,d);a.i.Gi(1)},o5=function(a){a.PC=Date.now()+
a.C;
bLa(a,a.C)},bLa=function(a,b){if(null!=a.Uq)throw Error("WatchDog timer not null");
a.Uq=i5((0,g.C)(a.JR,a),b)},u5=function(a){a.Uq&&(g.A.clearTimeout(a.Uq),a.Uq=null)},s5=function(a){a.i.LD()||a.In||a.i.Fu(a)},r5=function(a){u5(a);
g.Fi(a.Xw);a.Xw=null;a.u.stop();g.PEa(a.B);if(a.Ie){var b=a.Ie;a.Ie=null;b.abort();b.dispose()}a.Xi&&(a.Xi=null)},q5=function(a,b){try{a.i.XH(a,b),a.i.Gi(4)}catch(c){}},dLa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;cLa(a,b,function(h){h?c(!0):g.A.setTimeout(function(){dLa(a,b,c,d,f)},f)})}},cLa=function(a,b,c){var d=new Image;
d.onload=function(){try{v5(d),c(!0)}catch(e){}};
d.onerror=function(){try{v5(d),c(!1)}catch(e){}};
d.onabort=function(){try{v5(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{v5(d),c(!1)}catch(e){}};
g.A.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
mKa(d,a)},v5=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},w5=function(a){g.am.call(this);
this.headers=new g.Nm;this.ra=a||null;this.B=!1;this.ma=this.i=null;this.Fa=this.V="";this.G=0;this.u="";this.C=this.ya=this.L=this.xa=!1;this.J=0;this.X=null;this.La="";this.Y=this.Da=!1},eLa=function(a){return g.ye&&g.be(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},fLa=function(a){return"content-type"==a.toLowerCase()},hLa=function(a,b){a.B=!1;
a.i&&(a.C=!0,a.i.abort(),a.C=!1);a.u=b;a.G=5;gLa(a);x5(a)},gLa=function(a){a.xa||(a.xa=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},jLa=function(a){if(a.B&&"undefined"!=typeof g.Z_)if(a.ma[1]&&4==y5(a)&&2==a.getStatus())z5(a,"Local request error detected and ignored");
else if(a.L&&4==y5(a))g.Lm(a.UH,0,a);else if(a.dispatchEvent("readystatechange"),a.isComplete()){z5(a,"Request complete");a.B=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.Ad(1,String(a.V));if(!f&&g.A.self&&g.A.self.location){var h=g.A.self.location.protocol;f=h.substr(0,h.length-1)}e=!iLa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.G=6;try{var l=2<y5(a)?a.i.statusText:""}catch(m){l=""}a.u=l+" ["+a.getStatus()+"]";gLa(a)}}finally{x5(a)}}},x5=function(a,b){if(a.i){kLa(a);
var c=a.i,d=a.ma[0]?g.Ia:null;a.i=null;a.ma=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},kLa=function(a){a.i&&a.Y&&(a.i.ontimeout=null);
a.X&&(g.A.clearTimeout(a.X),a.X=null)},y5=function(a){return a.i?a.i.readyState:0},A5=function(a){try{return a.i?a.i.responseText:""}catch(b){return""}},z5=function(a,b){return b+" ["+a.Fa+" "+a.V+" "+a.getStatus()+"]"},lLa=function(a){this.i=a;
this.l=new h5},mLa=function(a){var b=B5(a.i,a.Lr,"/mail/images/cleardot.gif");
H4(b);dLa(b.toString(),5E3,(0,g.C)(a.HM,a),3,2E3);a.Gi(1)},D5=function(a){var b=a.i.L;
if(null!=b)k5(5),b?(k5(11),C5(a.i,a,!1)):(k5(12),C5(a.i,a,!0));else if(a.Ng=new m5(a,void 0,void 0,void 0),a.Ng.cn=a.Hy,b=a.i,b=B5(b,b.Pt()?a.Ar:null,a.Iy),k5(5),!g.ye||g.ce(10))I4(b,"TYPE","xmlhttp"),n5(a.Ng,b,!1,a.Ar,!1);else{I4(b,"TYPE","html");var c=a.Ng;a=!!a.Ar;c.Pq=3;c.Fl=H4(b.clone());aLa(c,a)}},E5=function(a,b,c){this.eb=1;
this.i=[];this.u=[];this.B=new h5;this.J=a||null;this.L=null!=b?b:null;this.C=c||!1},nLa=function(a,b){this.i=a;
this.map=b;this.context=null},oLa=function(a,b,c,d){g.Hl.call(this,"timingevent",a);
this.size=b;this.Jt=d},pLa=function(a){g.Hl.call(this,"serverreachability",a)},sLa=function(a){qLa(a);
if(3==a.eb){var b=a.Zs++,c=a.ov.clone();G4(c,"SID",a.l);G4(c,"RID",b);G4(c,"TYPE","terminate");F5(a,c);b=new m5(a,a.l,b,void 0);b.Pq=2;b.Fl=H4(c.clone());mKa(new Image,b.Fl.toString());b.Fq=Date.now();o5(b)}rLa(a)},tLa=function(a){a.gN(1,0);
a.ov=B5(a,null,a.Jy);G5(a)},qLa=function(a){a.Kl&&(a.Kl.abort(),a.Kl=null);
a.Xd&&(a.Xd.cancel(),a.Xd=null);a.Bk&&(g.A.clearTimeout(a.Bk),a.Bk=null);H5(a);a.Ag&&(a.Ag.cancel(),a.Ag=null);a.Sl&&(g.A.clearTimeout(a.Sl),a.Sl=null)},uLa=function(a,b){if(0==a.eb)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new nLa(a.GO++,b));2!=a.eb&&3!=a.eb||G5(a)},vLa=function(a){var b=0;
a.Xd&&b++;a.Ag&&b++;return b},G5=function(a){a.Ag||a.Sl||(a.Sl=i5((0,g.C)(a.cI,a),0),a.Yp=0)},xLa=function(a,b){if(1==a.eb){if(!b){a.Zs=Math.floor(1E5*Math.random());
b=a.Zs++;var c=new m5(a,"",b,void 0);c.cn=a.rj;var d=I5(a),e=a.ov.clone();G4(e,"RID",b);G4(e,"CVER","1");F5(a,e);WKa(c,e,d);a.Ag=c;a.eb=2}}else 3==a.eb&&(b?wLa(a,b):0==a.i.length||a.Ag||wLa(a))},wLa=function(a,b){if(b)if(6<a.Jn){a.i=a.u.concat(a.i);
a.u.length=0;var c=a.Zs-1;b=I5(a)}else c=b.L,b=b.Po;else c=a.Zs++,b=I5(a);var d=a.ov.clone();G4(d,"SID",a.l);G4(d,"RID",c);G4(d,"AID",a.rq);F5(a,d);c=new m5(a,a.l,c,a.Yp+1);c.cn=a.rj;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Ag=c;WKa(c,d,b)},F5=function(a,b){a.Af&&(a=a.Af.JF())&&g.Bb(a,function(c,d){G4(b,d,c)})},I5=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Jn&&0<b){var d=a.i[0].i;c.push("ofs="+d)}else d=0;for(var e={},f=0;f<b;e={pp:e.pp},f++){e.pp=a.i[f].i;var h=a.i[f].map;e.pp=6>=a.Jn?f:e.pp-d;try{g.Bb(h,function(l){return function(m,n){c.push("req"+l.pp+"_"+n+"="+encodeURIComponent(m))}}(e))}catch(l){c.push("req"+e.pp+"_type="+encodeURIComponent("_badmap"))}}a.u=a.u.concat(a.i.splice(0,b));
return c.join("&")},yLa=function(a){a.Xd||a.Bk||(a.G=1,a.Bk=i5((0,g.C)(a.bI,a),0),a.Mp=0)},J5=function(a){if(a.Xd||a.Bk||3<=a.Mp)return!1;
a.G++;a.Bk=i5((0,g.C)(a.bI,a),zLa(a,a.Mp));a.Mp++;return!0},C5=function(a,b,c){a.Jx=c;
a.sj=b.pk;a.C||tLa(a)},H5=function(a){null!=a.Pn&&(g.A.clearTimeout(a.Pn),a.Pn=null)},zLa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},K5=function(a,b){if(2==b||9==b){var c=null;
a.Af&&(c=null);var d=(0,g.C)(a.IS,a);c||(c=new g.Qm("//www.google.com/images/cleardot.gif"),H4(c));cLa(c.toString(),1E4,d)}else k5(2);ALa(a,b)},ALa=function(a,b){a.eb=0;
a.Af&&a.Af.bF(b);rLa(a);qLa(a)},rLa=function(a){a.eb=0;
a.sj=-1;if(a.Af)if(0==a.u.length&&0==a.i.length)a.Af.rz();else{g.ob(a.u);var b=g.ob(a.i);a.u.length=0;a.i.length=0;a.Af.rz(b)}},B5=function(a,b,c){var d=g.Ym(c);
if(""!=d.i)b&&g.Sm(d,b+"."+d.i),g.Tm(d,d.u);else{var e=window.location;d=qKa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.ds&&g.Bb(a.ds,function(f,h){G4(d,h,f)});
G4(d,"VER",a.Jn);F5(a,d);return d},BLa=function(){},CLa=function(){this.i=[];
this.l=[]},DLa=function(a,b){this.action=a;
this.params=b||{}},L5=function(a,b){g.F.call(this);
this.i=new g.J(this.tR,0,this);g.G(this,this.i);this.Hf=5E3;this.l=0;if("function"===typeof a)b&&(a=(0,g.C)(a,b));else if(a&&"function"===typeof a.handleEvent)a=(0,g.C)(a.handleEvent,a);else throw Error("Invalid listener argument");this.u=a},M5=function(a,b,c,d,e){c=void 0===c?!1:c;
d=void 0===d?function(){return""}:d;
e=void 0===e?!1:e;this.ma=a;this.G=b;this.u=new g.Rn;this.l=new L5(this.oS,this);this.i=null;this.X=!1;this.C=null;this.V="";this.L=this.B=0;this.J=[];this.ra=c;this.Y=d;this.xa=e},ELa=function(a){return{firstTestResults:[""],
secondTestResults:!a.i.Jx,sessionId:a.i.l,arrayId:a.i.rq}},FLa=function(a,b){a.L=b||0;
a.l.stop();N5(a);a.i&&(3==a.i.getState()&&xLa(a.i),sLa(a.i));a.L=0},O5=function(a){return!!a.i&&3==a.i.getState()},N5=function(a){if(a.i){var b=a.Y(),c=a.i.rj||{};
b?c["x-youtube-lounge-xsrf-token"]=b:delete c["x-youtube-lounge-xsrf-token"];a.i.rj=c}},P5=function(a){this.port=this.domain="";
this.i="/api/lounge";this.l=!0;a=a||document.location.href;var b=Number(g.Ad(4,a))||"";b&&(this.port=":"+b);this.domain=g.Bd(a)||"";a=g.Vc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ac(a,"10.0")&&(this.l=!1))},Q5=function(a,b){var c=a.i;
a.l&&(c="https://"+a.domain+a.port+a.i);return g.Od(c+b,{})},R5=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Pa(a.B,d,!0),onError:g.Pa(a.u,e),onTimeout:g.Pa(a.C,e)};c&&(a.postParams=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.wp(b,a)},JLa=function(){var a=GLa;
HLa();S5.push(a);ILa()},T5=function(a,b){HLa();
var c=KLa(a,String(b));g.gb(S5)?LLa(c):(ILa(),g.zb(S5,function(d){d(c)}))},HLa=function(){S5||(S5=g.Ha("yt.mdx.remote.debug.handlers_")||[],g.Ga("yt.mdx.remote.debug.handlers_",S5,void 0))},LLa=function(a){var b=(U5+1)%50;
U5=b;V5[b]=a;W5||(W5=49==b)},ILa=function(){var a=S5;
if(V5[0]){var b=W5?U5:-1;do{b=(b+1)%50;var c=V5[b];g.zb(a,function(d){d(c)})}while(b!=U5);
V5=Array(50);U5=-1;W5=!1}},KLa=function(a,b){var c=(Date.now()-MLa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},X5=function(a){g.O.call(this);
this.G=a;this.screens=[]},NLa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c)return a=c.name,c.id=b.id||c.id,c.name=b.name,c.token=b.token,c.uuid=b.uuid||c.uuid,c.name!=a;a.screens.push(b);return!0},OLa=function(a,b){var c=a.screens.length!=b.length;
a.screens=g.Ke(a.screens,function(f){return!!S4(b,f)});
for(var d=0,e=b.length;d<e;d++)c=NLa(a,b[d])||c;return c},PLa=function(a,b){var c=a.screens.length;
a.screens=g.Ke(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},Y5=function(a,b,c,d,e){g.O.call(this);
this.u=a;this.J=b;this.B=c;this.G=d;this.C=e;this.l=0;this.i=null;this.yb=NaN},$5=function(a){X5.call(this,"LocalScreenService");
this.l=a;this.i=NaN;Z5(this);this.info("Initializing with "+Q4(this.screens))},QLa=function(a){if(a.screens.length){var b=g.Pc(a.screens,function(d){return d.id}),c=Q5(a.l,"/pairing/get_lounge_token_batch");
R5(a.l,c,{screen_ids:b.join(",")},(0,g.C)(a.DN,a),(0,g.C)(a.CN,a))}},Z5=function(a){if(g.Qo("deprecate_pair_servlet_enabled"))return OLa(a,[]);
var b=wKa(CKa());b=g.Ke(b,function(c){return!c.uuid});
return OLa(a,b)},a6=function(a,b){EKa(g.Pc(a.screens,uKa));
b&&DKa()},c6=function(a,b){g.O.call(this);
this.G=b;b=(b=g.ov("yt-remote-online-screen-ids")||"")?b.split(","):[];for(var c={},d=this.G(),e=0,f=d.length;e<f;++e){var h=d[e].id;c[h]=g.fb(b,h)}this.i=c;this.C=a;this.u=this.B=NaN;this.l=null;b6("Initialized with "+g.Cj(this.i))},d6=function(a,b,c){var d=Q5(a.C,"/pairing/get_screen_availability");
R5(a.C,d,{lounge_token:b.token},(0,g.C)(function(e){e=e.screens||[];for(var f=0,h=e.length;f<h;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.C)(function(){c(!1)},a))},e6=function(a,b){a:if(J4(b)!=J4(a.i))var c=!1;
else{c=g.Kb(b);for(var d=0,e=c.length;d<e;++d)if(!a.i[c[d]]){c=!1;break a}c=!0}c||(b6("Updated online screens: "+g.Cj(a.i)),a.i=b,a.W("screenChange"));RLa(a)},f6=function(a){isNaN(a.u)||g.rp(a.u);
a.u=g.pp((0,g.C)(a.PB,a),0<a.B&&a.B<g.Ra()?2E4:1E4)},b6=function(a){T5("OnlineScreenService",a)},SLa=function(a){var b={};
g.zb(a.G(),function(c){c.token?b[c.token]=c.id:this.Jd("Requesting availability of screen w/o lounge token.")});
return b},RLa=function(a){a=g.Kb(g.Cb(a.i,function(b){return b}));
g.wb(a);a.length?g.nv("yt-remote-online-screen-ids",a.join(","),60):g.qv("yt-remote-online-screen-ids")},g6=function(a,b){b=void 0===b?!1:b;
X5.call(this,"ScreenService");this.B=a;this.J=b;this.i=this.l=null;this.u=[];this.C={};TLa(this)},VLa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.C[b]);var h=a.Zg(),l=c?T4(h,c):null;c&&(a.J||l)||(l=T4(h,b));if(l){l.uuid=b;var m=h6(a,l);d6(a.i,m,function(n){e(n?m:null)})}else c?ULa(a,c,(0,g.C)(function(n){var p=h6(this,new N4({name:d,
screenId:c,loungeToken:n,dialId:b||""}));d6(this.i,p,function(r){e(r?p:null)})},a),f):e(null)},WLa=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},XLa=function(a,b,c){d6(a.i,b,c)},ULa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={postParams:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,h){f=h&&h.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.wp(Q5(a.B,"/pairing/get_lounge_token_batch"),e)},YLa=function(a){a.screens=a.l.Zg();
for(var b=g.Vb(a.C),c=0,d=a.screens.length;c<d;++c){var e=a.screens[c];e.uuid=b[e.id]||""}a.info("Updated manual screens: "+Q4(a.screens))},TLa=function(a){i6(a);
a.l=new $5(a.B);a.l.subscribe("screenChange",(0,g.C)(a.JN,a));YLa(a);a.J||(a.u=wKa(g.ov("yt-remote-automatic-screen-cache")||[]));i6(a);a.info("Initializing automatic screens: "+Q4(a.u));a.i=new c6(a.B,(0,g.C)(a.Zg,a,!0));a.i.subscribe("screenChange",(0,g.C)(function(){this.W("onlineScreenChange")},a))},h6=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=T4(a.u,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.u.push(b),a.J||ZLa(a));i6(a);a.C[b.uuid]=b.id;g.nv("yt-remote-device-id-map",a.C,31536E3);return b},ZLa=function(a){a=g.Ke(a.u,function(b){return"shortLived"!=b.idType});
g.nv("yt-remote-automatic-screen-cache",g.Pc(a,uKa))},i6=function(a){a.C=g.ov("yt-remote-device-id-map")||{}},j6=function(a,b,c){g.O.call(this);
this.xa=c;this.u=a;this.i=b;this.B=null},k6=function(a,b){a.B=b;
a.W("sessionScreen",a.B)},$La=function(a,b){a.B&&(a.B.token=b,h6(a.u,a.B));
a.W("sessionScreen",a.B)},l6=function(a,b){T5(a.xa,b)},m6=function(a,b,c){j6.call(this,a,b,"CastSession");
var d=this;this.ya=c;this.l=null;this.Y=(0,g.C)(this.TL,this);this.ra=(0,g.C)(this.NR,this);this.X=g.pp(function(){aMa(d,null)},12E4);
this.J=this.C=this.G=this.L=0;this.ma=!1;this.V="unknown"},n6=function(a,b){g.rp(a.J);
a.J=0;0==b?bMa(a):a.J=g.pp(function(){bMa(a)},b)},bMa=function(a){cMa(a,"getLoungeToken");
g.rp(a.C);a.C=g.pp(function(){dMa(a,null)},3E4)},cMa=function(a,b){a.info("sendYoutubeMessage_: "+b+" "+g.Cj(void 0));
var c={};c.type=b;a.l?a.l.sendMessage("urn:x-cast:com.google.youtube.mdx",c,g.Ia,(0,g.C)(function(){l6(this,"Failed to send message: "+b+".")},a)):l6(a,"Sending yt message without session: "+g.Cj(c))},o6=function(a,b){b?(a.info("onConnectedScreenId_: Received screenId: "+b),a.getScreen()&&a.getScreen().id==b||a.YF(b,function(c){k6(a,c)},function(){return a.eg()},5)):a.eg(Error("Waiting for session status timed out."))},fMa=function(a,b,c){a.info("onConnectedScreenData_: Received screenData: "+JSON.stringify(b));
var d=new N4(b);eMa(a,d,function(e){e?(a.ma=!0,h6(a.u,d),k6(a,d),a.V="unknown",n6(a,c)):(g.Vo(Error("CastSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online.")),a.eg())},5)},aMa=function(a,b){g.rp(a.X);
a.X=0;b?a.ya.enableCastLoungeToken&&b.loungeToken?b.deviceId?a.getScreen()&&a.getScreen().uuid==b.deviceId||(b.loungeTokenRefreshIntervalMs?fMa(a,{name:a.i.friendlyName,screenId:b.screenId,loungeToken:b.loungeToken,dialId:b.deviceId,screenIdType:"shortLived"},b.loungeTokenRefreshIntervalMs):(g.Vo(Error("No loungeTokenRefreshIntervalMs presents in mdxSessionStatusData: "+JSON.stringify(b)+".")),o6(a,b.screenId))):(g.Vo(Error("No device id presents in mdxSessionStatusData: "+JSON.stringify(b)+".")),
o6(a,b.screenId)):o6(a,b.screenId):a.eg(Error("Waiting for session status timed out."))},dMa=function(a,b){g.rp(a.C);
a.C=0;var c=null;if(b)if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";else c="noLoungeTokenResponse";c?(a.info("Did not receive a new lounge token in onLoungeToken_ with data: "+(JSON.stringify(b)+", error: "+c)),a.V=c,n6(a,3E4)):($La(a,b.loungeToken),a.ma=!1,a.V="unknown",n6(a,b.loungeTokenRefreshIntervalMs))},eMa=function(a,b,c,d){g.rp(a.G);
a.G=0;XLa(a.u,b,function(e){e||0>d?c(e):a.G=g.pp(function(){eMa(a,b,c,d-1)},300)})},gMa=function(a){g.rp(a.L);
a.L=0;g.rp(a.G);a.G=0;g.rp(a.X);a.X=0;g.rp(a.C);a.C=0;g.rp(a.J);a.J=0},p6=function(a,b,c,d){j6.call(this,a,b,"DialSession");
this.Da=d;this.l=this.L=null;this.ra="";this.Fa=c;this.Ea=null;this.X=g.Ia;this.V=NaN;this.ya=(0,g.C)(this.UL,this);this.C=g.Ia;this.J=this.G=0;this.Y=!1;this.ma="unknown"},q6=function(a){var b;
return!!(a.Da.enableDialLoungeToken&&(null==(b=a.l)?0:b.getDialAppInfo))},hMa=function(a){a.C=a.u.ND(a.ra,a.i.label,a.i.friendlyName,q6(a),function(b,c){a.C=g.Ia;
a.Y=!0;k6(a,b);"shortLived"==b.idType&&0<c&&r6(a,c)},function(b){a.C=g.Ia;
a.eg(b)})},iMa=function(a){var b={};
b.pairingCode=a.ra;b.theme=a.Fa;HKa()&&(b.env_useStageMdx=1);return g.Md(b)},s6=function(a){return new Promise(function(b){a.ra=R4();
if(a.Ea){var c=new chrome.cast.DialLaunchResponse(!0,iMa(a));b(c);hMa(a)}else a.X=function(){g.rp(a.V);a.X=function(){};
a.V=NaN;var d=new chrome.cast.DialLaunchResponse(!0,iMa(a));b(d);hMa(a)},a.V=g.pp(function(){a.X()},100)})},kMa=function(a,b,c){a.info("initOnConnectedScreenDataPromise_: Received screenData: "+JSON.stringify(b));
var d=new N4(b);return(new Promise(function(e){jMa(a,d,function(f){f?(a.Y=!0,h6(a.u,d),k6(a,d),r6(a,c)):g.Vo(Error("DialSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online."));e(f)},5)})).then(function(e){return e?new chrome.cast.DialLaunchResponse(!1):s6(a)})},lMa=function(a,b){var c=a.L.receiver.label,d=a.i.friendlyName;
return(new Promise(function(e){VLa(a.u,c,b,d,function(f){f&&f.token&&k6(a,f);e(f)},function(f){l6(a,"Failed to get DIAL screen: "+f);
e(null)})})).then(function(e){return e&&e.token?new chrome.cast.DialLaunchResponse(!1):s6(a)})},jMa=function(a,b,c,d){g.rp(a.G);
a.G=0;XLa(a.u,b,function(e){e||0>d?c(e):a.G=g.pp(function(){jMa(a,b,c,d-1)},300)})},r6=function(a,b){a.info("getDialAppInfoWithTimeout_ "+b);
q6(a)&&(g.rp(a.J),a.J=0,0==b?mMa(a):a.J=g.pp(function(){mMa(a)},b))},mMa=function(a){q6(a)&&a.l.getDialAppInfo(function(b){a.info("getDialAppInfo dialLaunchData: "+JSON.stringify(b));
b=b.extraData||{};var c=null;if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";c?(a.ma=c,r6(a,3E4)):(a.Y=!1,a.ma="unknown",$La(a,b.loungeToken),r6(a,b.loungeTokenRefreshIntervalMs))},function(b){a.info("getDialAppInfo error: "+b);
a.ma="noLoungeTokenResponse";r6(a,3E4)})},nMa=function(a){g.rp(a.G);
a.G=0;g.rp(a.J);a.J=0;a.C();a.C=function(){};
g.rp(a.V)},t6=function(a,b){j6.call(this,a,b,"ManualSession");
this.l=g.pp((0,g.C)(this.tq,this,null),150)},u6=function(a,b){g.O.call(this);
this.B=b;this.l=a;this.L=b.appId||"233637DE";this.C=b.theme||"cl";this.V=b.disableCastApi||!1;this.i=null;this.J=!1;this.u=[];this.G=(0,g.C)(this.JQ,this)},oMa=function(a,b){return b?g.bb(a.u,function(c){return O4(b,c.label)},a):null},v6=function(a){T5("Controller",a)},GLa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},w6=function(a){return a.J||!!a.u.length||!!a.i},x6=function(a,b,c){b!=a.i&&(g.Fi(a.i),(a.i=b)?(c?a.W("yt-remote-cast2-receiver-resumed",
b.i):a.W("yt-remote-cast2-receiver-selected",b.i),b.subscribe("sessionScreen",(0,g.C)(a.aI,a,b)),b.getScreen()?a.W("yt-remote-cast2-session-change",b.getScreen()):c&&a.i.tq(null)):a.W("yt-remote-cast2-session-change",null))},pMa=function(a){var b=a.l.MD(),c=a.i&&a.i.i;
a=g.Pc(b,function(d){c&&O4(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=oMa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},uMa=function(a,b,c,d){d.disableCastApi?y6("Cannot initialize because disabled by Mdx config."):qMa()?rMa(b,d)&&(z6(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?sMa(a,c):(window.__onGCastApiAvailable=function(e,f){e?sMa(a,c):(A6("Failed to load cast API: "+f),B6(!1),z6(!1),g.qv("yt-remote-cast-available"),g.qv("yt-remote-cast-receiver"),
tMa(),c(!1))},d.loadCastApiSetupScript?g.tv("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?60<=$4()&&OKa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?b5():89<=$4()?QKa():(c5(),a5(PKa.map(LKa))))):y6("Cannot initialize because not running Chrome")},tMa=function(){y6("dispose");
var a=C6();a&&a.dispose();g.Ga("yt.mdx.remote.cloudview.instance_",null,void 0);vMa(!1);g.Vq(D6);D6.length=0},E6=function(){return!!g.ov("yt-remote-cast-installed")},wMa=function(){var a=g.ov("yt-remote-cast-receiver");
return a?a.friendlyName:null},xMa=function(){y6("clearCurrentReceiver");
g.qv("yt-remote-cast-receiver")},yMa=function(){return E6()?C6()?C6().getCastSession():(A6("getCastSelector: Cast is not initialized."),null):(A6("getCastSelector: Cast API is not installed!"),null)},G6=function(){E6()?C6()?F6()?(y6("Requesting cast selector."),C6().requestSession()):(y6("Wait for cast API to be ready to request the session."),D6.push(g.Uq("yt-remote-cast2-api-ready",G6))):A6("requestCastSelector: Cast is not initialized."):A6("requestCastSelector: Cast API is not installed!")},H6=
function(a,b){F6()?C6().setConnectedScreenStatus(a,b):A6("setConnectedScreenStatus called before ready.")},qMa=function(){var a=0<=g.Vc.search(/ (CrMo|Chrome|CriOS)\//);
return g.pB||a},zMa=function(a,b){C6().init(a,b)},rMa=function(a,b){var c=!1;
C6()||(a=new u6(a,b),a.subscribe("yt-remote-cast2-availability-change",function(d){g.nv("yt-remote-cast-available",d);L4("yt-remote-cast2-availability-change",d)}),a.subscribe("yt-remote-cast2-receiver-selected",function(d){y6("onReceiverSelected: "+d.friendlyName);
g.nv("yt-remote-cast-receiver",d);L4("yt-remote-cast2-receiver-selected",d)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(d){y6("onReceiverResumed: "+d.friendlyName);
g.nv("yt-remote-cast-receiver",d);L4("yt-remote-cast2-receiver-resumed",d)}),a.subscribe("yt-remote-cast2-session-change",function(d){y6("onSessionChange: "+P4(d));
d||g.qv("yt-remote-cast-receiver");L4("yt-remote-cast2-session-change",d)}),g.Ga("yt.mdx.remote.cloudview.instance_",a,void 0),c=!0);
y6("cloudview.createSingleton_: "+c);return c},C6=function(){return g.Ha("yt.mdx.remote.cloudview.instance_")},sMa=function(a,b){B6(!0);
z6(!1);zMa(a,function(c){c?(vMa(!0),g.Wq("yt-remote-cast2-api-ready")):(A6("Failed to initialize cast API."),B6(!1),g.qv("yt-remote-cast-available"),g.qv("yt-remote-cast-receiver"),tMa());b(c)})},y6=function(a){T5("cloudview",a)},A6=function(a){T5("cloudview",a)},B6=function(a){y6("setCastInstalled_ "+a);
g.nv("yt-remote-cast-installed",a)},F6=function(){return!!g.Ha("yt.mdx.remote.cloudview.apiReady_")},vMa=function(a){y6("setApiReady_ "+a);
g.Ga("yt.mdx.remote.cloudview.apiReady_",a,void 0)},z6=function(a){g.Ga("yt.mdx.remote.cloudview.initializing_",a,void 0)},I6=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.G=this.J=0;this.trackData=null;this.hasNext=this.Gj=!1;this.L=this.C=this.i=this.B=0;this.u=NaN;this.l=!1;this.reset(a)},J6=function(a){a.audioTrackId=null;
a.trackData=null;a.playerState=-1;a.Gj=!1;a.hasNext=!1;a.J=0;a.G=g.Ra();a.B=0;a.i=0;a.C=0;a.L=0;a.u=NaN;a.l=!1},K6=function(a){return a.qc()?(g.Ra()-a.G)/1E3:0},L6=function(a,b){a.J=b;
a.G=g.Ra()},M6=function(a){switch(a.playerState){case 1:case 1081:return(g.Ra()-a.G)/1E3+a.J;
case -1E3:return 0}return a.J},N6=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&J6(a)},O6=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.Ub(a.trackData);b.hasPrevious=a.Gj;b.hasNext=a.hasNext;b.playerTime=a.J;b.playerTimeAt=a.G;b.seekableStart=a.B;b.seekableEnd=a.i;b.duration=a.C;b.loadedTime=a.L;b.liveIngestionTime=a.u;return b},Q6=function(a,b){g.O.call(this);
this.eb=0;this.u=a;this.C=[];this.B=new CLa;this.l=this.i=null;this.L=(0,g.C)(this.oP,this);this.G=(0,g.C)(this.jt,this);this.J=(0,g.C)(this.nP,this);this.V=(0,g.C)(this.vP,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.bC,this),AMa(this))):c=3;0!=c&&(b?this.bC(c):g.pp((0,g.C)(function(){this.bC(c)},this),0));
(a=yMa())&&P6(this,a);this.subscribe("yt-remote-cast2-session-change",this.V)},R6=function(a){return new I6(a.u.getPlayerContextData())},AMa=function(a){g.zb("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.C.push(this.u.subscribe(b,g.Pa(this.GQ,b),this))},a)},BMa=function(a){g.zb(a.C,function(b){this.u.unsubscribeByKey(b)},a);
a.C.length=0},S6=function(a){return 1==a.getState()},T6=function(a,b){var c=a.B;
50>c.i.length+c.l.length&&a.B.l.push(b)},V6=function(a,b,c){var d=R6(a);
L6(d,c);-1E3!=d.playerState&&(d.playerState=b);U6(a,d)},W6=function(a,b,c){a.u.sendMessage(b,c)},U6=function(a,b){BMa(a);
a.u.setPlayerContextData(O6(b));AMa(a)},P6=function(a,b){a.l&&(a.l.removeUpdateListener(a.L),a.l.removeMediaListener(a.G),a.jt(null));
a.l=b;a.l&&(T5("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.L),a.l.addMediaListener(a.G),a.l.media.length&&a.jt(a.l.media[0]))},CMa=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=R6(a);b.contentId!=d.videoId&&T5("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;L6(d,a.i.getEstimatedTime());U6(a,d)}else T5("CP","No cast media video. Ignoring state update.")},X6=function(a,b,c){return(0,g.C)(function(d){this.Jd("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Jd("Retrying "+b+" using MDx browser channel."),W6(this,b,c))},a)},Y6=function(a,b,c){g.O.call(this);
this.C=NaN;this.ma=!1;this.L=this.J=this.X=this.Y=NaN;this.V=[];this.B=this.G=this.u=this.dc=this.i=null;this.xa=a;this.V.push(g.Vp(window,"beforeunload",(0,g.C)(this.zN,this)));this.l=[];this.dc=new I6;this.ya=b.id;this.ra=b.idType;this.i=DMa(this,c);this.i.subscribe("handlerOpened",this.sP,this);this.i.subscribe("handlerClosed",this.pP,this);this.i.subscribe("handlerError",this.qP,this);this.i.subscribe("handlerMessage",this.rP,this);this.i.lx(b.token);this.subscribe("remoteQueueChange",function(){var d=
this.dc.videoId;g.rv()&&g.nv("yt-remote-session-video-id",d)},this)},Z6=function(a){T5("conn",a)},DMa=function(a,b){return new M5(Q5(a.xa,"/bc"),b,!1,function(){return a.RD()},"shortLived"==a.ra)},$6=function(a,b){a.W("proxyStateChange",b)},EMa=function(a){a.C=g.pp((0,g.C)(function(){Z6("Connecting timeout");
this.Up(1)},a),2E4)},a7=function(a){g.rp(a.C);
a.C=NaN},b7=function(a){g.rp(a.Y);
a.Y=NaN},FMa=function(a){c7(a);
a.X=g.pp((0,g.C)(function(){d7(this,"getNowPlaying")},a),2E4)},c7=function(a){g.rp(a.X);
a.X=NaN},HMa=function(a,b){b&&(a7(a),b7(a));
var c=O5(a.i)&&isNaN(a.C);b==c?b&&($6(a,1),d7(a,"getSubtitlesTrack")):b?(a.XF()&&a.dc.reset(),$6(a,1),d7(a,"getNowPlaying"),GMa(a)):a.Up(1)},IMa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.dc.videoId&&(g.Pb(b.params)?a.dc.trackData=null:a.dc.trackData=b.params,a.W("remotePlayerChange"))},JMa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.dc.listId=b.params.listId||a.dc.listId;N6(a.dc,c,d);a.W("remoteQueueChange")},LMa=function(a,b){b.params=b.params||{};
JMa(a,b);KMa(a,b);a.W("autoplayDismissed")},KMa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
L6(a.dc,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.dc.playerState&&(c=-1E3);a.dc.playerState=c;c=Number(b.params.loadedTime);a.dc.L=isNaN(c)?0:c;c=Number(b.params.duration);a.dc.C=isNaN(c)?0:c;c=a.dc;var d=Number(b.params.liveIngestionTime);c.u=d;c.l=isNaN(d)?!1:!0;c=a.dc;d=Number(b.params.seekableStartTime);b=Number(b.params.seekableEndTime);c.B=isNaN(d)?0:d;c.i=isNaN(b)?0:b;1==a.dc.playerState?FMa(a):c7(a);a.W("remotePlayerChange")},MMa=function(a,b){if(-1E3!=a.dc.playerState){var c=
1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.dc.playerState=c;b=parseInt(b.params.currentTime,10);L6(a.dc,isNaN(b)?0:b);a.W("remotePlayerChange")}},NMa=function(a,b){var c="true"==b.params.muted;
a.dc.volume=parseInt(b.params.volume,10);a.dc.muted=c;a.W("remotePlayerChange")},OMa=function(a,b){a.G=b.params.videoId;
a.W("nowAutoplaying",parseInt(b.params.timeout,10))},PMa=function(a,b){var c="true"==b.params.hasNext;
a.dc.Gj="true"==b.params.hasPrevious;a.dc.hasNext=c;a.W("previousNextChange")},GMa=function(a){g.rp(a.L);
a.L=g.pp((0,g.C)(a.Up,a,1),864E5)},d7=function(a,b,c){c?Z6("Sending: action="+b+", params="+g.Cj(c)):Z6("Sending: action="+b);
a.i.sendMessage(b,c)},e7=function(a){X5.call(this,"ScreenServiceProxy");
this.Gf=a;this.i=[];this.i.push(this.Gf.$_s("screenChange",(0,g.C)(this.YL,this)));this.i.push(this.Gf.$_s("onlineScreenChange",(0,g.C)(this.nQ,this)))},TMa=function(a,b){GKa();
if(!Z4||!Z4.get("yt-remote-disable-remote-module-for-dev")){b=g.M("MDX_CONFIG")||b;yKa();X4();f7||(f7=new P5(b?b.loungeApiHost:void 0),HKa()&&(f7.i="/api/loungedev"));g7||(g7=g.Ha("yt.mdx.remote.deferredProxies_")||[],g.Ga("yt.mdx.remote.deferredProxies_",g7,void 0));QMa();var c=h7();if(!c){var d=new g6(f7,b?b.disableAutomaticScreenCache||!1:!1);g.Ga("yt.mdx.remote.screenService_",d,void 0);c=h7();var e={};b&&(e={appId:b.appId,disableDial:b.disableDial,theme:b.theme,loadCastApiSetupScript:b.loadCastApiSetupScript,
disableCastApi:b.disableCastApi,enableDialLoungeToken:b.enableDialLoungeToken,enableCastLoungeToken:b.enableCastLoungeToken});uMa(a,d,function(f){f?i7()&&H6(i7(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){L4("yt-remote-receiver-availability-change")})},e)}b&&!g.Ha("yt.mdx.remote.initialized_")&&(g.Ga("yt.mdx.remote.initialized_",!0,void 0),j7("Initializing: "+g.Cj(b)),k7.push(g.Uq("yt-remote-cast2-availability-change",function(){L4("yt-remote-receiver-availability-change")})),k7.push(g.Uq("yt-remote-cast2-receiver-selected",
function(){l7(null);
L4("yt-remote-auto-connect","cast-selector-receiver")})),k7.push(g.Uq("yt-remote-cast2-receiver-resumed",function(){L4("yt-remote-receiver-resumed","cast-selector-receiver")})),k7.push(g.Uq("yt-remote-cast2-session-change",RMa)),k7.push(g.Uq("yt-remote-connection-change",function(f){f?H6(i7(),"YouTube TV"):m7()||(H6(null,null),xMa())})),a=n7(),b.isAuto&&(a.id+="#dial"),e=b.capabilities||[],g.Qo("desktop_enable_autoplay")&&e.push("atp"),0<e.length&&(a.capabilities=e),a.name=b.device,a.app=b.app,(b=
b.theme)&&(a.theme=b),j7(" -- with channel params: "+g.Cj(a)),a?(g.nv("yt-remote-session-app",a.app),g.nv("yt-remote-session-name",a.name)):(g.qv("yt-remote-session-app"),g.qv("yt-remote-session-name")),g.Ga("yt.mdx.remote.channelParams_",a,void 0),c.start(),i7()||SMa())}},UMa=function(){var a=h7().Gf.$_gos();
var b=o7();b&&p7()&&(S4(a,b)||a.push(b));return xKa(a)},q7=function(){var a=VMa();
!a&&E6()&&wMa()&&(a={key:"cast-selector-receiver",name:wMa()});return a},VMa=function(){var a=UMa(),b=o7();
b||(b=m7());return g.bb(a,function(c){return b&&O4(b,c.key)?!0:!1})},o7=function(){var a=i7();
if(!a)return null;var b=h7().Zg();return T4(b,a)},RMa=function(a){j7("remote.onCastSessionChange_: "+P4(a));
if(a){var b=o7();if(b&&b.id==a.id){if(H6(b.id,"YouTube TV"),"shortLived"==a.idType&&(a=a.token))r7&&(r7.token=a),(b=p7())&&b.lx(a)}else b&&s7(),t7(a,1)}else p7()&&s7()},s7=function(){F6()?C6().stopSession():A6("stopSession called before API ready.");
var a=p7();a&&(a.disconnect(1),u7(null))},v7=function(){var a=p7();
return!!a&&3!=a.getProxyState()},j7=function(a){T5("remote",a)},h7=function(){if(!w7){var a=g.Ha("yt.mdx.remote.screenService_");
w7=a?new e7(a):null}return w7},i7=function(){return g.Ha("yt.mdx.remote.currentScreenId_")},WMa=function(a){g.Ga("yt.mdx.remote.currentScreenId_",a,void 0)},XMa=function(){return g.Ha("yt.mdx.remote.connectData_")},l7=function(a){g.Ga("yt.mdx.remote.connectData_",a,void 0)},p7=function(){return g.Ha("yt.mdx.remote.connection_")},u7=function(a){var b=p7();
l7(null);a||WMa("");g.Ga("yt.mdx.remote.connection_",a,void 0);g7&&(g.zb(g7,function(c){c(a)}),g7.length=0);
b&&!a?L4("yt-remote-connection-change",!1):!b&&a&&L4("yt-remote-connection-change",!0)},m7=function(){var a=g.rv();
if(!a)return null;var b=h7();if(!b)return null;b=b.Zg();return T4(b,a)},t7=function(a,b){i7();
o7()&&o7();x7?r7=a:(WMa(a.id),a=new Y6(f7,a,n7()),a.connect(b,XMa()),a.subscribe("beforeDisconnect",function(c){L4("yt-remote-before-disconnect",c)}),a.subscribe("beforeDispose",function(){p7()&&(p7(),u7(null))}),a.subscribe("browserChannelAuthError",function(){var c=o7();
c&&"shortLived"==c.idType&&(F6()?C6().handleBrowserChannelAuthError():A6("refreshLoungeToken called before API ready."))}),u7(a))},SMa=function(){var a=m7();
a?(j7("Resume connection to: "+P4(a)),t7(a,0)):(Y4(),xMa(),j7("Skipping connecting because no session screen found."))},QMa=function(){var a=n7();
if(g.Pb(a)){a=W4();var b=g.ov("yt-remote-session-name")||"",c=g.ov("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ga("yt.mdx.remote.channelParams_",a,void 0)}},n7=function(){return g.Ha("yt.mdx.remote.channelParams_")||{}},y7=function(a,b,c){g.F.call(this);
var d=this;this.l=a;this.I=b;this.Nb=c;this.events=new g.VL(this);this.X=this.events.N(this.I,"onVolumeChange",function(e){YMa(d,e)});
this.C=!1;this.suggestion=null;this.G=new g.fJ(64);this.i=new g.J(this.aJ,500,this);this.u=new g.J(this.bJ,1E3,this);this.L=new d5(this.bT,0,this);this.B={};this.V=new g.J(this.GJ,1E3,this);this.J=new e5(this.seekTo,1E3,this);this.Y=g.Ia;g.G(this,this.events);this.events.N(b,"onCaptionsTrackListChanged",this.YP);this.events.N(b,"captionschanged",this.lP);this.events.N(b,"captionssettingschanged",this.hJ);this.events.N(b,"videoplayerreset",this.Qw);this.events.N(b,"mdxautoplaycancel",function(){d.Nb.uF()});
a=this.Nb;a.Ha();a.subscribe("proxyStateChange",this.WH,this);a.subscribe("remotePlayerChange",this.ut,this);a.subscribe("remoteQueueChange",this.Qw,this);a.subscribe("previousNextChange",this.TH,this);a.subscribe("nowAutoplaying",this.NH,this);a.subscribe("autoplayDismissed",this.nH,this);g.G(this,this.i);g.G(this,this.u);g.G(this,this.L);g.G(this,this.V);g.G(this,this.J);this.hJ();this.Qw();this.ut()},YMa=function(a,b){if(z7(a)){a.Nb.unsubscribe("remotePlayerChange",a.ut,a);
var c=Math.round(b.volume);b=!!b.muted;var d=R6(a.Nb);if(c!==d.volume||b!==d.muted)a.Nb.setVolume(c,b),a.V.start();a.Nb.subscribe("remotePlayerChange",a.ut,a)}},ZMa=function(a){a.Tb(0);
a.i.stop();a.Kb(new g.fJ(64))},A7=function(a,b){if(z7(a)&&!a.C){var c=null;
b&&(c={style:a.I.getSubtitlesUserSettings()},g.Xb(c,b));a.Nb.QD(a.I.getVideoData(1).videoId,c);a.B=R6(a.Nb).trackData}},B7=function(a,b){var c=a.I.getPlaylist();
if(null===c||void 0===c?0:c.listId){var d=c.index;var e=c.listId.toString()}c=a.I.getVideoData(1);a.Nb.playVideo(c.videoId,b,d,e,c.playerParams,c.ya,kKa(c));a.Kb(new g.fJ(1))},$Ma=function(a,b){if(b){var c=a.I.getOption("captions","tracklist",{nG:1});
c&&c.length?(a.I.setOption("captions","track",b),a.C=!1):(a.I.loadModule("captions"),a.C=!0)}else a.I.setOption("captions","track",{})},z7=function(a){return R6(a.Nb).videoId===a.I.getVideoData(1).videoId},C7=function(){g.V.call(this,{D:"div",
K:"ytp-mdx-manual-pairing-popup-dialog",U:{role:"dialog"},S:[{D:"div",K:"ytp-mdx-manual-pairing-popup-dialog-inner-content",S:[{D:"div",K:"ytp-mdx-manual-pairing-popup-title",oa:"Connecting to your TV on web using a code will be going away soon"},{D:"div",K:"ytp-mdx-manual-pairing-popup-buttons",S:[{D:"button",Ca:["ytp-button","ytp-mdx-manual-pairing-popup-learn-more"],oa:"Learn more"},{D:"button",Ca:["ytp-button","ytp-mdx-manual-pairing-popup-ok"],oa:"OK"}]}]}]});this.i=new g.LK(this,250);this.learnMoreButton=
this.Ba("ytp-mdx-manual-pairing-popup-learn-more");this.okButton=this.Ba("ytp-mdx-manual-pairing-popup-ok");g.G(this,this.i);this.N(this.learnMoreButton,"click",this.l);this.N(this.okButton,"click",this.u)},D7=function(){g.V.call(this,{D:"div",
K:"ytp-mdx-popup-dialog",U:{role:"dialog"},S:[{D:"div",K:"ytp-mdx-popup-dialog-inner-content",S:[{D:"div",K:"ytp-mdx-popup-title",oa:"You're signed out"},{D:"div",K:"ytp-mdx-popup-description",oa:"Videos you watch may be added to the TV's watch history and influence TV recommendations. To avoid this, cancel and sign in to YouTube on your computer."},{D:"div",K:"ytp-mdx-privacy-popup-buttons",S:[{D:"button",Ca:["ytp-button","ytp-mdx-privacy-popup-cancel"],oa:"Cancel"},{D:"button",Ca:["ytp-button",
"ytp-mdx-privacy-popup-confirm"],oa:"Confirm"}]}]}]});this.i=new g.LK(this,250);this.cancelButton=this.Ba("ytp-mdx-privacy-popup-cancel");this.confirmButton=this.Ba("ytp-mdx-privacy-popup-confirm");g.G(this,this.i);this.N(this.cancelButton,"click",this.l);this.N(this.confirmButton,"click",this.u)},E7=function(a){g.V.call(this,{D:"div",
K:"ytp-remote",S:[{D:"div",K:"ytp-remote-display-status",S:[{D:"div",K:"ytp-remote-display-status-icon",S:[g.Lma()]},{D:"div",K:"ytp-remote-display-status-text",oa:"{{statustext}}"}]}]});this.api=a;this.i=new g.LK(this,250);g.G(this,this.i);this.N(a,"presentingplayerstatechange",this.l);aNa(this,a.rb())},aNa=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
b=g.U(b,128)?g.JH("Error on $RECEIVER_NAME",c):b.qc()||g.U(b,4)?g.JH("Playing on $RECEIVER_NAME",c):g.JH("Connected to $RECEIVER_NAME",c);a.Qa("statustext",b);a.i.show()}else a.i.hide()},F7=function(a,b){g.RO.call(this,"Play on",0,a,b);
this.I=a;this.Gm={};this.N(a,"onMdxReceiversChange",this.C);this.N(a,"presentingplayerstatechange",this.C);this.C()},G7=function(a){g.fM.call(this,a);
this.Di={key:R4(),name:"This computer"};this.wh=null;this.subscriptions=[];this.EB=this.Nb=null;this.Gm=[this.Di];this.Ml=this.Di;this.bd=new g.fJ(64);this.JG=0;this.Re=-1;this.xq=null;this.xt=this.nw=!1;this.bl=this.Eq=null;if(!g.FD(this.player.T())&&!g.GD(this.player.T())){a=this.player;var b=g.JL(a);b&&(b=b.em())&&(b=new F7(a,b),g.G(this,b));b=new E7(a);g.G(this,b);g.TL(a,b.element,4);this.Eq=new D7;g.G(this,this.Eq);g.TL(a,this.Eq.element,4);g.R(this.player.T().experiments,"pair_servlet_deprecation_warning_enabled")&&
!g.R(this.player.T().experiments,"deprecate_pair_servlet_enabled")&&(this.xq=new C7,g.G(this,this.xq),g.TL(a,this.xq.element,4));this.xt=!!m7();this.nw=!!g.ov("yt-remote-manual-pairing-warning-shown")}},H7=function(a){a.bl&&(a.player.removeEventListener("presentingplayerstatechange",a.bl),a.bl=null)},bNa=function(a,b,c){a.bd=c;
a.player.W("presentingplayerstatechange",new g.vH(c,b))},cNa=function(a,b,c){var d=!1;
1===b?d=!a.xt:2===b&&(d=!a.nw);d&&g.xH(c,8)&&(a.player.pauseVideo(),H7(a))},I7=function(a,b){if(b.key!==a.Ml.key)if(b.key===a.Di.key)s7();
else{if(a.xq&&!a.nw&&b!==a.Di&&"cast-selector-receiver"!==b.key&&g.aE(a.player.T()))dNa(a);else{var c;(c=!g.R(a.player.T().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.M("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.M("SESSION_INDEX")&&!g.M("LOGGED_IN")))||a.xt||!a.Eq);(c?0:g.aE(a.player.T())||g.eE(a.player.T()))&&eNa(a)}a.Ml=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&
g.R(a.player.T().experiments,"should_clear_video_data_on_player_cued_unstarted"))a=null;else{var f=a.player.getPlaylist();if(f){var h=[];for(var l=0;l<f.length;l++)h[l]=f.bb(l).videoId}else h=[e];f=a.player.getCurrentTime(1);a={videoIds:h,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.ya,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=kKa(c))&&(a.locationInfo=c)}j7("Connecting to: "+g.Cj(b));"cast-selector-receiver"==b.key?(l7(a||null),b=a||null,
F6()?C6().setLaunchParams(b):A6("setLaunchParams called before ready.")):!a&&v7()&&i7()==b.key?L4("yt-remote-connection-change",!0):(s7(),l7(a||null),a=h7().Zg(),(b=T4(a,b.key))&&t7(b,1))}},eNa=function(a){a.player.rb().qc()?a.player.pauseVideo():(a.bl=function(b){cNa(a,1,b)},a.player.addEventListener("presentingplayerstatechange",a.bl));
a.Eq&&a.Eq.Rc();p7()||(x7=!0)},dNa=function(a){a.player.rb().qc()?a.player.pauseVideo():(a.bl=function(b){cNa(a,2,b)},a.player.addEventListener("presentingplayerstatechange",a.bl));
a.xq&&a.xq.Rc();p7()||(x7=!0)},$Ka={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},t5={"'":"\\'"},fNa={},tKa={ZT:"atp",B3:"ska",t2:"que",z0:"mus",A3:"sus",TX:"dsp",M2:"seq",Y_:"mic",TW:"dpa",nU:"cds",x0:"mlm"},Z4,V4="",NKa=IKa("loadCastFramework")||IKa("loadCastApplicationFramework"),PKa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Sa(d5,g.F);g.k=d5.prototype;g.k.zg=function(a){this.B=arguments;this.i=!1;this.yb?this.u=g.Ra()+this.Hf:this.yb=g.Lm(this.C,this.Hf)};
g.k.stop=function(){this.yb&&(g.A.clearTimeout(this.yb),this.yb=null);this.u=null;this.i=!1;this.B=[]};
g.k.pause=function(){++this.l};
g.k.resume=function(){this.l&&(--this.l,!this.l&&this.i&&(this.i=!1,this.G.apply(null,this.B)))};
g.k.va=function(){this.stop();d5.Id.va.call(this)};
g.k.OL=function(){this.yb&&(g.A.clearTimeout(this.yb),this.yb=null);this.u?(this.yb=g.Lm(this.C,this.u-g.Ra()),this.u=null):this.l?this.i=!0:(this.i=!1,this.G.apply(null,this.B))};g.v(e5,g.F);g.k=e5.prototype;g.k.zg=function(a){this.u=arguments;this.yb||this.l?this.i=!0:f5(this)};
g.k.stop=function(){this.yb&&(g.A.clearTimeout(this.yb),this.yb=null,this.i=!1,this.u=null)};
g.k.pause=function(){this.l++};
g.k.resume=function(){this.l--;this.l||!this.i||this.yb||(this.i=!1,f5(this))};
g.k.va=function(){g.F.prototype.va.call(this);this.stop()};h5.prototype.stringify=function(a){return g.A.JSON.stringify(a,void 0)};
h5.prototype.parse=function(a){return g.A.JSON.parse(a,void 0)};var j5=new g.am;g.v(RKa,g.Hl);l5.prototype.i=null;l5.prototype.getOptions=function(){var a;(a=this.i)||(a={},TKa(this)&&(a[0]=!0,a[1]=!0),a=this.i=a);return a};var J7;g.Sa(SKa,l5);J7=new SKa;g.k=m5.prototype;g.k.cn=null;g.k.Ti=!1;g.k.Uq=null;g.k.PC=null;g.k.Fq=null;g.k.Pq=null;g.k.Fl=null;g.k.Jm=null;g.k.Po=null;g.k.Ie=null;g.k.ou=0;g.k.Xi=null;g.k.Lx=null;g.k.Al=null;g.k.zr=-1;g.k.SI=!0;g.k.In=!1;g.k.Gy=0;g.k.Xw=null;var YKa={},p5={};g.k=m5.prototype;g.k.setTimeout=function(a){this.C=a};
g.k.dS=function(a){a=a.target;var b=this.Xw;b&&3==y5(a)?b.zg():this.NJ(a)};
g.k.NJ=function(a){try{if(a==this.Ie)a:{var b=y5(this.Ie),c=this.Ie.G,d=this.Ie.getStatus();if(g.ye&&!g.ce(10)||g.Ae&&!g.be("420+")){if(4>b)break a}else if(3>b||3==b&&!g.og&&!A5(this.Ie))break a;this.In||4!=b||7==c||(8==c||0>=d?this.i.Gi(3):this.i.Gi(2));u5(this);var e=this.Ie.getStatus();this.zr=e;var f=A5(this.Ie);(this.Ti=200==e)?(4==b&&r5(this),this.G?(ZKa(this,b,f),g.og&&this.Ti&&3==b&&(this.B.Oa(this.u,"tick",this.YR),this.u.start())):q5(this,f),this.Ti&&!this.In&&(4==b?this.i.Fu(this):(this.Ti=
!1,o5(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.Al=3,k5(13)):(this.Al=0,k5(14)),r5(this),s5(this))}}catch(h){this.Ie&&A5(this.Ie)}finally{}};
g.k.YR=function(){var a=y5(this.Ie),b=A5(this.Ie);this.ou<b.length&&(u5(this),ZKa(this,a,b),this.Ti&&4!=a&&o5(this))};
g.k.BR=function(a){i5((0,g.C)(this.AR,this,a),0)};
g.k.AR=function(a){this.In||(u5(this),q5(this,a),o5(this))};
g.k.eI=function(a){i5((0,g.C)(this.zR,this,a),0)};
g.k.zR=function(a){this.In||(r5(this),this.Ti=a,this.i.Fu(this),this.i.Gi(4))};
g.k.cancel=function(){this.In=!0;r5(this)};
g.k.JR=function(){this.Uq=null;var a=Date.now();0<=a-this.PC?(2!=this.Pq&&this.i.Gi(3),r5(this),this.Al=2,k5(18),s5(this)):bLa(this,this.PC-a)};
g.k.getLastError=function(){return this.Al};g.Sa(w5,g.am);var iLa=/^https?$/i,gNa=["POST","PUT"];g.k=w5.prototype;
g.k.send=function(a,b,c,d){if(this.i)throw Error("[goog.net.XhrIo] Object is active with another request="+this.V+"; newUri="+a);b=b?b.toUpperCase():"GET";this.V=a;this.u="";this.G=0;this.Fa=b;this.xa=!1;this.B=!0;this.i=this.ra?UKa(this.ra):UKa(J7);this.ma=this.ra?this.ra.getOptions():J7.getOptions();this.i.onreadystatechange=(0,g.C)(this.UH,this);try{K4(z5(this,"Opening Xhr")),this.ya=!0,this.i.open(b,String(a),!0),this.ya=!1}catch(f){K4(z5(this,"Error opening Xhr: "+f.message));hLa(this,f);return}a=
c||"";var e=this.headers.clone();d&&pKa(d,function(f,h){e.set(h,f)});
d=g.bb(e.Fh(),fLa);c=g.A.FormData&&a instanceof g.A.FormData;!g.fb(gNa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,h){this.i.setRequestHeader(h,f)},this);
this.La&&(this.i.responseType=this.La);"withCredentials"in this.i&&this.i.withCredentials!==this.Da&&(this.i.withCredentials=this.Da);try{kLa(this),0<this.J&&(this.Y=eLa(this.i),K4(z5(this,"Will abort after "+this.J+"ms if incomplete, xhr2 "+this.Y)),this.Y?(this.i.timeout=this.J,this.i.ontimeout=(0,g.C)(this.KD,this)):this.X=g.Lm(this.KD,this.J,this)),K4(z5(this,"Sending request")),this.L=!0,this.i.send(a),this.L=!1}catch(f){K4(z5(this,"Send error: "+f.message)),hLa(this,f)}};
g.k.KD=function(){"undefined"!=typeof g.Z_&&this.i&&(this.u="Timed out after "+this.J+"ms, aborting",this.G=8,z5(this,this.u),this.dispatchEvent("timeout"),this.abort(8))};
g.k.abort=function(a){this.i&&this.B&&(z5(this,"Aborting"),this.B=!1,this.C=!0,this.i.abort(),this.C=!1,this.G=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),x5(this))};
g.k.va=function(){this.i&&(this.B&&(this.B=!1,this.C=!0,this.i.abort(),this.C=!1),x5(this,!0));w5.Id.va.call(this)};
g.k.UH=function(){this.Ha()||(this.ya||this.L||this.C?jLa(this):this.IQ())};
g.k.IQ=function(){jLa(this)};
g.k.isActive=function(){return!!this.i};
g.k.isComplete=function(){return 4==y5(this)};
g.k.getStatus=function(){try{return 2<y5(this)?this.i.status:-1}catch(a){return-1}};
g.k.getResponseHeader=function(a){if(this.i&&this.isComplete())return a=this.i.getResponseHeader(a),null===a?void 0:a};
g.k.getLastError=function(){return"string"===typeof this.u?this.u:String(this.u)};g.k=lLa.prototype;g.k.Hy=null;g.k.Ng=null;g.k.Yw=!1;g.k.cJ=null;g.k.hv=null;g.k.TA=null;g.k.Iy=null;g.k.eb=null;g.k.pk=-1;g.k.Ar=null;g.k.Lr=null;g.k.connect=function(a){this.Iy=a;a=B5(this.i,null,this.Iy);k5(3);this.cJ=Date.now();var b=this.i.J;null!=b?(this.Ar=b[0],(this.Lr=b[1])?(this.eb=1,mLa(this)):(this.eb=2,D5(this))):(I4(a,"MODE","init"),this.Ng=new m5(this,void 0,void 0,void 0),this.Ng.cn=this.Hy,n5(this.Ng,a,!1,null,!0),this.eb=0)};
g.k.HM=function(a){if(a)this.eb=2,D5(this);else{k5(4);var b=this.i;b.sj=b.Kl.pk;K5(b,9)}a&&this.Gi(2)};
g.k.Hz=function(a){return this.i.Hz(a)};
g.k.abort=function(){this.Ng&&(this.Ng.cancel(),this.Ng=null);this.pk=-1};
g.k.LD=function(){return!1};
g.k.XH=function(a,b){this.pk=a.zr;if(0==this.eb)if(b){try{var c=this.l.parse(b)}catch(d){a=this.i;a.sj=this.pk;K5(a,2);return}this.Ar=c[0];this.Lr=c[1]}else a=this.i,a.sj=this.pk,K5(a,2);else if(2==this.eb)if(this.Yw)k5(7),this.TA=Date.now();else if("11111"==b){if(k5(6),this.Yw=!0,this.hv=Date.now(),a=this.hv-this.cJ,!g.ye||g.ce(10)||500>a)this.pk=200,this.Ng.cancel(),k5(12),C5(this.i,this,!0)}else k5(8),this.hv=this.TA=Date.now(),this.Yw=!1};
g.k.Fu=function(){this.pk=this.Ng.zr;if(this.Ng.Ti)0==this.eb?this.Lr?(this.eb=1,mLa(this)):(this.eb=2,D5(this)):2==this.eb&&((!g.ye||g.ce(10)?!this.Yw:200>this.TA-this.hv)?(k5(11),C5(this.i,this,!1)):(k5(12),C5(this.i,this,!0)));else{0==this.eb?k5(9):2==this.eb&&k5(10);var a=this.i;this.Ng.getLastError();a.sj=this.pk;K5(a,2)}};
g.k.Pt=function(){return this.i.Pt()};
g.k.isActive=function(){return this.i.isActive()};
g.k.Gi=function(a){this.i.Gi(a)};g.k=E5.prototype;g.k.rj=null;g.k.ds=null;g.k.Ag=null;g.k.Xd=null;g.k.Jy=null;g.k.ov=null;g.k.PE=null;g.k.Gu=null;g.k.Zs=0;g.k.GO=0;g.k.Af=null;g.k.Sl=null;g.k.Bk=null;g.k.Pn=null;g.k.Kl=null;g.k.Jx=null;g.k.rq=-1;g.k.IG=-1;g.k.sj=-1;g.k.Yp=0;g.k.Mp=0;g.k.Jn=8;g.Sa(oLa,g.Hl);g.Sa(pLa,g.Hl);g.k=E5.prototype;g.k.connect=function(a,b,c,d,e){k5(0);this.Jy=b;this.ds=c||{};d&&void 0!==e&&(this.ds.OSID=d,this.ds.OAID=e);this.C?(i5((0,g.C)(this.hF,this,a),100),tLa(this)):this.hF(a)};
g.k.hF=function(a){this.Kl=new lLa(this);this.Kl.Hy=this.rj;this.Kl.l=this.B;this.Kl.connect(a)};
g.k.LD=function(){return 0==this.eb};
g.k.getState=function(){return this.eb};
g.k.cI=function(a){this.Sl=null;xLa(this,a)};
g.k.bI=function(){this.Bk=null;this.Xd=new m5(this,this.l,"rpc",this.G);this.Xd.cn=this.rj;this.Xd.Gy=0;var a=this.PE.clone();G4(a,"RID","rpc");G4(a,"SID",this.l);G4(a,"CI",this.Jx?"0":"1");G4(a,"AID",this.rq);F5(this,a);if(!g.ye||g.ce(10))G4(a,"TYPE","xmlhttp"),n5(this.Xd,a,!0,this.Gu,!1);else{G4(a,"TYPE","html");var b=this.Xd,c=!!this.Gu;b.Pq=3;b.Fl=H4(a.clone());aLa(b,c)}};
g.k.XH=function(a,b){if(0!=this.eb&&(this.Xd==a||this.Ag==a))if(this.sj=a.zr,this.Ag==a&&3==this.eb)if(7<this.Jn){try{var c=this.B.parse(b)}catch(d){c=null}if(Array.isArray(c)&&3==c.length)if(a=c,0==a[0])a:{if(!this.Bk){if(this.Xd)if(this.Xd.Fq+3E3<this.Ag.Fq)H5(this),this.Xd.cancel(),this.Xd=null;else break a;J5(this);k5(19)}}else this.IG=a[1],0<this.IG-this.rq&&37500>a[2]&&this.Jx&&0==this.Mp&&!this.Pn&&(this.Pn=i5((0,g.C)(this.iP,this),6E3));else K5(this,11)}else b!=fNa.IW.i&&K5(this,11);else if(this.Xd==
a&&H5(this),!g.pc(b))for(a=this.B.parse(b),b=0;b<a.length;b++)c=a[b],this.rq=c[0],c=c[1],2==this.eb?"c"==c[0]?(this.l=c[1],this.Gu=c[2],c=c[3],null!=c?this.Jn=c:this.Jn=6,this.eb=3,this.Af&&this.Af.dF(),this.PE=B5(this,this.Pt()?this.Gu:null,this.Jy),yLa(this)):"stop"==c[0]&&K5(this,7):3==this.eb&&("stop"==c[0]?K5(this,7):"noop"!=c[0]&&this.Af&&this.Af.cF(c),this.Mp=0)};
g.k.iP=function(){null!=this.Pn&&(this.Pn=null,this.Xd.cancel(),this.Xd=null,J5(this),k5(20))};
g.k.Fu=function(a){if(this.Xd==a){H5(this);this.Xd=null;var b=2}else if(this.Ag==a)this.Ag=null,b=1;else return;this.sj=a.zr;if(0!=this.eb)if(a.Ti)1==b?(b=j5,b.dispatchEvent(new oLa(b,a.Po?a.Po.length:0,Date.now()-a.Fq,this.Yp)),G5(this),this.u.length=0):yLa(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.sj)){if(d=1==b)this.Ag||this.Sl||1==this.eb||2<=this.Yp?d=!1:(this.Sl=i5((0,g.C)(this.cI,this,a),zLa(this,this.Yp)),this.Yp++,d=!0);d=!(d||2==b&&J5(this))}if(d)switch(c){case 1:K5(this,
5);break;case 4:K5(this,10);break;case 3:K5(this,6);break;case 7:K5(this,12);break;default:K5(this,2)}}};
g.k.gN=function(a){if(!g.fb(arguments,this.eb))throw Error("Unexpected channel state: "+this.eb);};
g.k.IS=function(a){a?k5(2):(k5(1),ALa(this,8))};
g.k.Hz=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new w5;a.Da=!1;return a};
g.k.isActive=function(){return!!this.Af&&this.Af.isActive(this)};
g.k.Gi=function(a){var b=j5;b.dispatchEvent(new pLa(b,a))};
g.k.Pt=function(){return!(!g.ye||g.ce(10))};
g.k=BLa.prototype;g.k.dF=function(){};
g.k.cF=function(){};
g.k.bF=function(){};
g.k.rz=function(){};
g.k.JF=function(){return{}};
g.k.isActive=function(){return!0};g.k=CLa.prototype;g.k.isEmpty=function(){return g.gb(this.i)&&g.gb(this.l)};
g.k.clear=function(){this.i=[];this.l=[]};
g.k.contains=function(a){return g.fb(this.i,a)||g.fb(this.l,a)};
g.k.remove=function(a){var b=this.i;var c=(0,g.UEa)(b,a);0<=c?(g.jb(b,c),b=!0):b=!1;return b||g.kb(this.l,a)};
g.k.Cg=function(){for(var a=[],b=this.i.length-1;0<=b;--b)a.push(this.i[b]);var c=this.l.length;for(b=0;b<c;++b)a.push(this.l[b]);return a};g.Sa(L5,g.F);g.k=L5.prototype;g.k.tR=function(){this.Hf=Math.min(3E5,2*this.Hf);this.u();this.l&&this.start()};
g.k.start=function(){var a=this.Hf+15E3*Math.random();g.ln(this.i,a);this.l=g.Ra()+a};
g.k.stop=function(){this.i.stop();this.l=0};
g.k.isActive=function(){return this.i.isActive()};
g.k.reset=function(){this.i.stop();this.Hf=5E3};g.Sa(M5,BLa);g.k=M5.prototype;g.k.subscribe=function(a,b,c){return this.u.subscribe(a,b,c)};
g.k.unsubscribe=function(a,b,c){return this.u.unsubscribe(a,b,c)};
g.k.Pf=function(a){return this.u.Pf(a)};
g.k.W=function(a,b){return this.u.W.apply(this.u,arguments)};
g.k.dispose=function(){this.X||(this.X=!0,g.Fi(this.u),FLa(this),g.Fi(this.l),this.l=null,this.Y=function(){return""})};
g.k.Ha=function(){return this.X};
g.k.connect=function(a,b,c){if(!this.i||2!=this.i.getState()){this.V="";this.l.stop();this.C=a||null;this.B=b||0;a=this.ma+"/test";b=this.ma+"/bind";var d=new E5(c?c.firstTestResults:null,c?c.secondTestResults:null,this.ra),e=this.i;e&&(e.Af=null);d.Af=this;this.i=d;N5(this);if(this.i){d=g.M("ID_TOKEN");var f=this.i.rj||{};d?f["x-youtube-identity-token"]=d:delete f["x-youtube-identity-token"];this.i.rj=f}e?(3!=e.getState()&&0==vLa(e)||e.getState(),this.i.connect(a,b,this.G,e.l,e.rq)):c?this.i.connect(a,
b,this.G,c.sessionId,c.arrayId):this.i.connect(a,b,this.G)}};
g.k.sendMessage=function(a,b){a={_sc:a};b&&g.Xb(a,b);this.l.isActive()||2==(this.i?this.i.getState():0)?this.J.push(a):O5(this)&&(N5(this),uLa(this.i,a))};
g.k.dF=function(){this.l.reset();this.C=null;this.B=0;if(this.J.length){var a=this.J;this.J=[];for(var b=0,c=a.length;b<c;++b)uLa(this.i,a[b])}this.W("handlerOpened")};
g.k.bF=function(a){var b=2==a&&401==this.i.sj;4==a||b||this.l.start();this.W("handlerError",a,b)};
g.k.rz=function(a){if(!this.l.isActive())this.W("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.J.push(d)}};
g.k.JF=function(){var a={v:2};this.V&&(a.gsessionid=this.V);0!=this.B&&(a.ui=""+this.B);0!=this.L&&(a.ui=""+this.L);this.C&&g.Xb(a,this.C);return a};
g.k.cF=function(a){"S"==a[0]?this.V=a[1]:"gracefulReconnect"==a[0]?(this.l.start(),sLa(this.i)):this.W("handlerMessage",new DLa(a[0],a[1]))};
g.k.lx=function(a){(this.G.loungeIdToken=a)||this.l.stop();if(this.xa&&this.i){var b=this.i.rj||{};a?b["X-YouTube-LoungeId-Token"]=a:delete b["X-YouTube-LoungeId-Token"];this.i.rj=b}};
g.k.oS=function(){this.l.isActive();0==vLa(this.i)&&this.connect(this.C,this.B)};P5.prototype.B=function(a,b,c,d){b?a(d):a({text:c.responseText})};
P5.prototype.u=function(a,b){a(Error("Request error: "+b.status))};
P5.prototype.C=function(a){a(Error("request timed out"))};var MLa=Date.now(),S5=null,V5=Array(50),U5=-1,W5=!1;g.Sa(X5,g.O);X5.prototype.Zg=function(){return this.screens};
X5.prototype.contains=function(a){return!!S4(this.screens,a)};
X5.prototype.get=function(a){return a?T4(this.screens,a):null};
X5.prototype.info=function(a){T5(this.G,a)};g.v(Y5,g.O);g.k=Y5.prototype;g.k.start=function(){!this.i&&isNaN(this.yb)&&this.mI()};
g.k.stop=function(){this.i&&(this.i.abort(),this.i=null);isNaN(this.yb)||(g.rp(this.yb),this.yb=NaN)};
g.k.va=function(){this.stop();g.O.prototype.va.call(this)};
g.k.mI=function(){this.yb=NaN;this.i=g.wp(Q5(this.u,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:this.J},timeout:5E3,onSuccess:(0,g.C)(this.QL,this),onError:(0,g.C)(this.PL,this),onTimeout:(0,g.C)(this.RL,this)})};
g.k.QL=function(a,b){this.i=null;a=b.screen||{};a.dialId=this.B;a.name=this.G;b=-1;this.C&&a.shortLivedLoungeToken&&a.shortLivedLoungeToken.value&&a.shortLivedLoungeToken.refreshIntervalMs&&(a.screenIdType="shortLived",a.loungeToken=a.shortLivedLoungeToken.value,b=a.shortLivedLoungeToken.refreshIntervalMs);this.W("pairingComplete",new N4(a),b)};
g.k.PL=function(a){this.i=null;a.status&&404==a.status?this.l>=hNa.length?this.W("pairingFailed",Error("DIAL polling timed out")):(a=hNa[this.l],this.yb=g.pp((0,g.C)(this.mI,this),a),this.l++):this.W("pairingFailed",Error("Server error "+a.status))};
g.k.RL=function(){this.i=null;this.W("pairingFailed",Error("Server not responding"))};
var hNa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Sa($5,X5);g.k=$5.prototype;g.k.start=function(){Z5(this)&&this.W("screenChange");!g.ov("yt-remote-lounge-token-expiration")&&QLa(this);g.rp(this.i);this.i=g.pp((0,g.C)(this.start,this),1E4)};
g.k.add=function(a,b){Z5(this);NLa(this,a);a6(this,!1);this.W("screenChange");b(a);a.token||QLa(this)};
g.k.remove=function(a,b){var c=Z5(this);PLa(this,a)&&(a6(this,!1),c=!0);b(a);c&&this.W("screenChange")};
g.k.Hx=function(a,b,c,d){var e=Z5(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,a6(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.W("screenChange")};
g.k.va=function(){g.rp(this.i);$5.Id.va.call(this)};
g.k.DN=function(a){Z5(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}a6(this,!b);b&&T5(this.G,"Missed "+b+" lounge tokens.")};
g.k.CN=function(a){T5(this.G,"Requesting lounge tokens failed: "+a)};g.v(c6,g.O);g.k=c6.prototype;g.k.start=function(){var a=parseInt(g.ov("yt-remote-fast-check-period")||"0",10);(this.B=g.Ra()-144E5<a?0:a)?f6(this):(this.B=g.Ra()+3E5,g.nv("yt-remote-fast-check-period",this.B),this.PB())};
g.k.isEmpty=function(){return g.Pb(this.i)};
g.k.update=function(){b6("Updating availability on schedule.");var a=this.G(),b=g.Cb(this.i,function(c,d){return c&&!!T4(a,d)},this);
e6(this,b)};
g.k.va=function(){g.rp(this.u);this.u=NaN;this.l&&(this.l.abort(),this.l=null);g.O.prototype.va.call(this)};
g.k.PB=function(){g.rp(this.u);this.u=NaN;this.l&&this.l.abort();var a=SLa(this);if(J4(a)){var b=Q5(this.C,"/pairing/get_screen_availability");this.l=R5(this.C,b,{lounge_token:g.Kb(a).join(",")},(0,g.C)(this.cR,this,a),(0,g.C)(this.bR,this))}else e6(this,{}),f6(this)};
g.k.cR=function(a,b){this.l=null;var c=g.Kb(SLa(this));if(g.xb(c,g.Kb(a))){b=b.screens||[];c={};for(var d=0,e=b.length;d<e;++d)c[a[b[d].loungeToken]]="online"==b[d].status;e6(this,c);f6(this)}else this.Jd("Changing Screen set during request."),this.PB()};
g.k.bR=function(a){this.Jd("Screen availability failed: "+a);this.l=null;f6(this)};
g.k.Jd=function(a){T5("OnlineScreenService",a)};g.Sa(g6,X5);g.k=g6.prototype;g.k.start=function(){this.l.start();this.i.start();this.screens.length&&(this.W("screenChange"),this.i.isEmpty()||this.W("onlineScreenChange"))};
g.k.add=function(a,b,c){this.l.add(a,b,c)};
g.k.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.k.Hx=function(a,b,c,d){this.l.contains(a)?this.l.Hx(a,b,c,d):(a="Updating name of unknown screen: "+a.name,T5(this.G,a),d(Error(a)))};
g.k.Zg=function(a){return a?this.screens:g.nb(this.screens,g.Ke(this.u,function(b){return!this.contains(b)},this))};
g.k.MD=function(){return g.Ke(this.Zg(!0),function(a){return!!this.i.i[a.id]},this)};
g.k.ND=function(a,b,c,d,e,f){var h=this;this.info("getDialScreenByPairingCode "+a+" / "+b);var l=new Y5(this.B,a,b,c,d);l.subscribe("pairingComplete",function(m,n){g.Fi(l);e(h6(h,m),n)});
l.subscribe("pairingFailed",function(m){g.Fi(l);f(m)});
l.start();return(0,g.C)(l.stop,l)};
g.k.SL=function(a,b,c,d){g.wp(Q5(this.B,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:a},timeout:5E3,onSuccess:(0,g.C)(function(e,f){e=new N4(f.screen||{});if(!e.name||WLa(this,e.name)){a:{f=e.name;for(var h=2,l=b(f,h);WLa(this,l);){h++;if(20<h)break a;l=b(f,h)}f=l}e.name=f}c(h6(this,e))},this),
onError:(0,g.C)(function(e){d(Error("pairing request failed: "+e.status))},this),
onTimeout:(0,g.C)(function(){d(Error("pairing request timed out."))},this)})};
g.k.va=function(){g.Fi(this.l);g.Fi(this.i);g6.Id.va.call(this)};
g.k.JN=function(){YLa(this);this.W("screenChange");this.i.update()};
g6.prototype.dispose=g6.prototype.dispose;g.Sa(j6,g.O);g.k=j6.prototype;g.k.getScreen=function(){return this.B};
g.k.eg=function(a){this.Ha()||(a&&l6(this,""+a),this.B=null,this.W("sessionScreen",null))};
g.k.info=function(a){T5(this.xa,a)};
g.k.OD=function(){return null};
g.k.ZB=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.C)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.C)(function(){l6(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.k.va=function(){this.ZB("");j6.Id.va.call(this)};g.v(m6,j6);g.k=m6.prototype;g.k.YB=function(a){if(this.l){if(this.l==a)return;l6(this,"Overriding cast session with new session object");gMa(this);this.ma=!1;this.V="unknown";this.l.removeUpdateListener(this.Y);this.l.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.ra)}this.l=a;this.l.addUpdateListener(this.Y);this.l.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.ra);cMa(this,"getMdxSessionStatus")};
g.k.tq=function(a){this.info("launchWithParams no-op for Cast: "+g.Cj(a))};
g.k.stop=function(){this.l?this.l.stop((0,g.C)(function(){this.eg()},this),(0,g.C)(function(){this.eg(Error("Failed to stop receiver app."))},this)):this.eg(Error("Stopping cast device without session."))};
g.k.ZB=function(){};
g.k.va=function(){this.info("disposeInternal");gMa(this);this.l&&(this.l.removeUpdateListener(this.Y),this.l.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.ra));this.l=null;j6.prototype.va.call(this)};
g.k.NR=function(a,b){if(!this.Ha())if(b)if(b=g5(b),g.Ma(b))switch(a=""+b.type,b=b.data||{},this.info("onYoutubeMessage_: "+a+" "+g.Cj(b)),a){case "mdxSessionStatus":aMa(this,b);break;case "loungeToken":dMa(this,b);break;default:l6(this,"Unknown youtube message: "+a)}else l6(this,"Unable to parse message.");else l6(this,"No data in message.")};
g.k.YF=function(a,b,c,d){g.rp(this.L);this.L=0;VLa(this.u,this.i.label,a,this.i.friendlyName,(0,g.C)(function(e){e?b(e):0<=d?(l6(this,"Screen "+a+" appears to be offline. "+d+" retries left."),this.L=g.pp((0,g.C)(this.YF,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.k.OD=function(){return this.l};
g.k.TL=function(a){this.Ha()||a||(l6(this,"Cast session died."),this.eg())};g.v(p6,j6);g.k=p6.prototype;g.k.YB=function(a){this.l=a;this.l.addUpdateListener(this.ya)};
g.k.tq=function(a){this.Ea=a;this.X()};
g.k.stop=function(){nMa(this);this.l?this.l.stop((0,g.C)(this.eg,this,null),(0,g.C)(this.eg,this,"Failed to stop DIAL device.")):this.eg()};
g.k.va=function(){nMa(this);this.l&&this.l.removeUpdateListener(this.ya);this.l=null;j6.prototype.va.call(this)};
g.k.UL=function(a){this.Ha()||a||(l6(this,"DIAL session died."),this.C(),this.C=g.Ia,this.eg())};g.v(t6,j6);t6.prototype.stop=function(){this.eg()};
t6.prototype.YB=function(){};
t6.prototype.tq=function(){g.rp(this.l);this.l=NaN;var a=T4(this.u.Zg(),this.i.label);a?k6(this,a):this.eg(Error("No such screen"))};
t6.prototype.va=function(){g.rp(this.l);this.l=NaN;j6.prototype.va.call(this)};g.v(u6,g.O);g.k=u6.prototype;
g.k.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.L);this.V||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED;a=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION;var e=(0,g.C)(this.MQ,this);c=new chrome.cast.ApiConfig(c,(0,g.C)(this.YH,this),e,d,a);c.customDialLaunchCallback=(0,g.C)(this.CP,this);chrome.cast.initialize(c,(0,g.C)(function(){this.Ha()||
(chrome.cast.addReceiverActionListener(this.G),JLa(),this.l.subscribe("onlineScreenChange",(0,g.C)(this.PD,this)),this.u=pMa(this),chrome.cast.setCustomReceivers(this.u,g.Ia,(0,g.C)(function(f){this.Jd("Failed to set initial custom receivers: "+g.Cj(f))},this)),this.W("yt-remote-cast2-availability-change",w6(this)),b(!0))},this),(0,g.C)(function(f){this.Jd("Failed to initialize API: "+g.Cj(f));
b(!1)},this))};
g.k.tS=function(a,b){v6("Setting connected screen ID: "+a+" -> "+b);if(this.i){var c=this.i.getScreen();if(!a||c&&c.id!=a)v6("Unsetting old screen status: "+this.i.i.friendlyName),x6(this,null)}if(a&&b){if(!this.i){c=T4(this.l.Zg(),a);if(!c){v6("setConnectedScreenStatus: Unknown screen.");return}if("shortLived"==c.idType){v6("setConnectedScreenStatus: Screen with id type to be short lived.");return}a=oMa(this,c);a||(v6("setConnectedScreenStatus: Connected receiver not custom..."),a=new chrome.cast.Receiver(c.uuid?
c.uuid:c.id,c.name),a.receiverType=chrome.cast.ReceiverType.CUSTOM,this.u.push(a),chrome.cast.setCustomReceivers(this.u,g.Ia,(0,g.C)(function(d){this.Jd("Failed to set initial custom receivers: "+g.Cj(d))},this)));
v6("setConnectedScreenStatus: new active receiver: "+a.friendlyName);x6(this,new t6(this.l,a),!0)}this.i.ZB(b)}else v6("setConnectedScreenStatus: no screen.")};
g.k.uS=function(a){this.Ha()?this.Jd("Setting connection data on disposed cast v2"):this.i?this.i.tq(a):this.Jd("Setting connection data without a session")};
g.k.WL=function(){this.Ha()?this.Jd("Stopping session on disposed cast v2"):this.i?(this.i.stop(),x6(this,null)):v6("Stopping non-existing session")};
g.k.requestSession=function(){chrome.cast.requestSession((0,g.C)(this.YH,this),(0,g.C)(this.fR,this))};
g.k.va=function(){this.l.unsubscribe("onlineScreenChange",(0,g.C)(this.PD,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.G);var a=GLa,b=g.Ha("yt.mdx.remote.debug.handlers_");g.kb(b||[],a);g.Fi(this.i);g.O.prototype.va.call(this)};
g.k.Jd=function(a){T5("Controller",a)};
g.k.aI=function(a,b){this.i==a&&(b||x6(this,null),this.W("yt-remote-cast2-session-change",b))};
g.k.JQ=function(a,b){if(!this.Ha())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),v6("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.i)if(this.i.i.label!=a.label)v6("onReceiverAction_: Stopping active receiver: "+this.i.i.friendlyName),this.i.stop();else{v6("onReceiverAction_: Casting to active receiver.");this.i.getScreen()&&this.W("yt-remote-cast2-session-change",this.i.getScreen());break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:x6(this,
new t6(this.l,a));break;case chrome.cast.ReceiverType.DIAL:x6(this,new p6(this.l,a,this.C,this.B));break;case chrome.cast.ReceiverType.CAST:x6(this,new m6(this.l,a,this.B));break;default:this.Jd("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.i&&this.i.i.label==a.label?this.i.stop():this.Jd("Stopping receiver w/o session: "+a.friendlyName)}else this.Jd("onReceiverAction_ called without receiver.")};
g.k.CP=function(a){if(this.Ha())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Jd("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.i?this.i.i:null;if(!c||c.label!=b.label)return this.Jd("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.i.getScreen())return v6("Reselecting dial screen."),
this.W("yt-remote-cast2-session-change",this.i.getScreen()),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Jd('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);x6(this,new p6(this.l,b,this.C,this.B))}b=this.i;b.L=a;b.L.appState==chrome.cast.DialAppState.RUNNING?(a=b.L.extraData||{},c=a.screenId||null,q6(b)&&a.loungeToken?a.loungeTokenRefreshIntervalMs?a=kMa(b,{name:b.i.friendlyName,screenId:a.screenId,loungeToken:a.loungeToken,dialId:b.L.receiver.label,
screenIdType:"shortLived"},a.loungeTokenRefreshIntervalMs):(g.Vo(Error("No loungeTokenRefreshIntervalMs presents in additionalData: "+JSON.stringify(a)+".")),a=lMa(b,c)):a=lMa(b,c)):a=s6(b);return a};
g.k.YH=function(a){if(!this.Ha()){v6("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.i)if(b.receiverType==chrome.cast.ReceiverType.CAST)v6("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),x6(this,new m6(this.l,b,this.B),!0);else{this.Jd("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.i.i,d=T4(this.l.Zg(),c.label);d&&O4(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(v6("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Fi(this.i),this.i=new m6(this.l,b,this.B),this.i.subscribe("sessionScreen",(0,g.C)(this.aI,this,this.i)),this.i.tq(null));this.i.YB(a)}}};
g.k.VL=function(){return this.i?this.i.OD():null};
g.k.fR=function(a){this.Ha()||(this.Jd("Failed to estabilish a session: "+g.Cj(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&x6(this,null))};
g.k.MQ=function(a){v6("Receiver availability updated: "+a);if(!this.Ha()){var b=w6(this);this.J=a==chrome.cast.ReceiverAvailability.AVAILABLE;w6(this)!=b&&this.W("yt-remote-cast2-availability-change",w6(this))}};
g.k.PD=function(){this.Ha()||(this.u=pMa(this),v6("Updating custom receivers: "+g.Cj(this.u)),chrome.cast.setCustomReceivers(this.u,g.Ia,(0,g.C)(function(){this.Jd("Failed to set custom receivers.")},this)),this.W("yt-remote-cast2-availability-change",w6(this)))};
u6.prototype.setLaunchParams=u6.prototype.uS;u6.prototype.setConnectedScreenStatus=u6.prototype.tS;u6.prototype.stopSession=u6.prototype.WL;u6.prototype.getCastSession=u6.prototype.VL;u6.prototype.requestSession=u6.prototype.requestSession;u6.prototype.init=u6.prototype.init;u6.prototype.dispose=u6.prototype.dispose;var D6=[];g.k=I6.prototype;
g.k.reset=function(a){this.listId="";this.index=-1;this.videoId="";J6(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.trackData=a.trackData,this.Gj=a.hasPrevious,this.hasNext=a.hasNext,this.J=a.playerTime,this.G=a.playerTimeAt,this.B=a.seekableStart,this.i=a.seekableEnd,this.C=a.duration,this.L=a.loadedTime,this.u=a.liveIngestionTime,this.l=
!isNaN(this.u))};
g.k.qc=function(){return 1==this.playerState};
g.k.isAdPlaying=function(){return 1081==this.playerState};
g.k.getDuration=function(){return this.l?this.C+K6(this):this.C};
g.k.clone=function(){return new I6(O6(this))};g.v(Q6,g.O);g.k=Q6.prototype;g.k.getState=function(){return this.eb};
g.k.play=function(){S6(this)?(this.i?this.i.play(null,g.Ia,X6(this,"play")):W6(this,"play"),V6(this,1,M6(R6(this))),this.W("remotePlayerChange")):T6(this,this.play)};
g.k.pause=function(){S6(this)?(this.i?this.i.pause(null,g.Ia,X6(this,"pause")):W6(this,"pause"),V6(this,2,M6(R6(this))),this.W("remotePlayerChange")):T6(this,this.pause)};
g.k.seekTo=function(a){if(S6(this)){if(this.i){var b=R6(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.qc()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ia,X6(this,"seekTo",{newTime:a}))}else W6(this,"seekTo",{newTime:a});V6(this,3,a);this.W("remotePlayerChange")}else T6(this,g.Pa(this.seekTo,a))};
g.k.stop=function(){if(S6(this)){this.i?this.i.stop(null,g.Ia,X6(this,"stopVideo")):W6(this,"stopVideo");var a=R6(this);a.index=-1;a.videoId="";J6(a);U6(this,a);this.W("remotePlayerChange")}else T6(this,this.stop)};
g.k.setVolume=function(a,b){if(S6(this)){var c=R6(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.C)(function(){T5("CP","set receiver volume: "+d)},this),(0,g.C)(function(){this.Jd("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.C)(function(){T5("CP","set receiver muted: "+b)},this),(0,g.C)(function(){this.Jd("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);W6(this,"setVolume",e)}c.muted=b;c.volume=a;U6(this,c)}else T6(this,g.Pa(this.setVolume,a,b))};
g.k.QD=function(a,b){if(S6(this)){var c=R6(this);a={videoId:a};b&&(c.trackData={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},a.style=g.Cj(b.style),g.Xb(a,c.trackData));W6(this,"setSubtitlesTrack",a);U6(this,c)}else T6(this,g.Pa(this.QD,a,b))};
g.k.setAudioTrack=function(a,b){S6(this)?(b=b.getLanguageInfo().getId(),W6(this,"setAudioTrack",{videoId:a,audioTrackId:b}),a=R6(this),a.audioTrackId=b,U6(this,a)):T6(this,g.Pa(this.setAudioTrack,a,b))};
g.k.playVideo=function(a,b,c,d,e,f,h){var l=R6(this);c=c||0;var m={videoId:a,currentIndex:c};N6(l,a,c);void 0!==b&&(L6(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=h&&(m.locationInfo=g.Cj(h));W6(this,"setPlaylist",m);d||U6(this,l)};
g.k.Tw=function(a,b){if(S6(this)){if(a&&b){var c=R6(this);N6(c,a,b);U6(this,c)}W6(this,"previous")}else T6(this,g.Pa(this.Tw,a,b))};
g.k.nextVideo=function(a,b){if(S6(this)){if(a&&b){var c=R6(this);N6(c,a,b);U6(this,c)}W6(this,"next")}else T6(this,g.Pa(this.nextVideo,a,b))};
g.k.uF=function(){S6(this)?W6(this,"dismissAutoplay"):T6(this,this.uF)};
g.k.dispose=function(){if(3!=this.eb){var a=this.eb;this.eb=3;this.W("proxyStateChange",a,this.eb)}g.O.prototype.dispose.call(this)};
g.k.va=function(){BMa(this);this.u=null;this.B.clear();P6(this,null);g.O.prototype.va.call(this)};
g.k.bC=function(a){if((a!=this.eb||2==a)&&3!=this.eb&&0!=a){var b=this.eb;this.eb=a;this.W("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)b=a=this.B,g.gb(b.i)&&(b.i=b.l,b.i.reverse(),b.l=[]),a.i.pop().apply(this);else 3==a&&this.dispose()}};
g.k.GQ=function(a,b){this.W(a,b)};
g.k.oP=function(a){if(!a)this.jt(null),P6(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=R6(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)T5("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,U6(this,b)}};
g.k.jt=function(a){T5("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.J);if(this.i=a)this.i.addUpdateListener(this.J),CMa(this),this.W("remotePlayerChange")};
g.k.nP=function(a){a?(CMa(this),this.W("remotePlayerChange")):this.jt(null)};
g.k.tC=function(){W6(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.k.vP=function(){var a=yMa();a&&P6(this,a)};
g.k.Jd=function(a){T5("CP",a)};g.v(Y6,g.O);g.k=Y6.prototype;
g.k.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,h=b.index,l={videoId:d},m=b.currentTime;b=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);b&&(l.locationInfo=b);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==h&&(l.currentIndex=h);c&&(this.dc.listId=c);this.dc.videoId=d;this.dc.index=h||0;this.dc.state=3;L6(this.dc,m);this.B="UNSUPPORTED";Z6("Connecting with setPlaylist and params: "+g.Cj(l));this.i.connect({method:"setPlaylist",
params:g.Cj(l)},a,BKa())}else Z6("Connecting without params"),this.i.connect({},a,BKa());EMa(this)};
g.k.lx=function(a){this.i.lx(a)};
g.k.dispose=function(){this.Ha()||(this.W("beforeDispose"),$6(this,3));g.O.prototype.dispose.call(this)};
g.k.va=function(){a7(this);c7(this);b7(this);g.rp(this.J);this.J=NaN;g.rp(this.L);this.L=NaN;this.u=null;g.Wp(this.V);this.V.length=0;this.i.dispose();g.O.prototype.va.call(this);this.B=this.G=this.l=this.dc=this.i=null};
g.k.zN=function(){this.Up(2)};
g.k.sP=function(){Z6("Channel opened");this.ma&&(this.ma=!1,b7(this),this.Y=g.pp((0,g.C)(function(){Z6("Timing out waiting for a screen.");this.Up(1)},this),15E3));
FKa(ELa(this.i),this.ya)};
g.k.pP=function(){Z6("Channel closed");isNaN(this.C)?Y4(!0):Y4();this.dispose()};
g.k.qP=function(a,b){Y4();isNaN(this.Ds())?(b&&"shortLived"==this.ra&&this.W("browserChannelAuthError",a),Z6("Channel error: "+a+" without reconnection"),this.dispose()):(this.ma=!0,Z6("Channel error: "+a+" with reconnection in "+this.Ds()+" ms"),$6(this,2))};
g.k.rP=function(a){a.params?Z6("Received: action="+a.action+", params="+g.Cj(a.params)):Z6("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g5(a.params.devices);this.l=g.Pc(a,function(c){return new M4(c)});
a=!!g.bb(this.l,function(c){return"LOUNGE_SCREEN"==c.type});
HMa(this,a);break;case "loungeScreenDisconnected":g.lb(this.l,function(c){return"LOUNGE_SCREEN"==c.type});
HMa(this,!1);break;case "remoteConnected":var b=new M4(g5(a.params.device));g.bb(this.l,function(c){return b?c.id==b.id:!1})||lKa(this.l,b);
break;case "remoteDisconnected":b=new M4(g5(a.params.device));g.lb(this.l,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":JMa(this,a);break;case "nowPlaying":LMa(this,a);break;case "onStateChange":KMa(this,a);break;case "onAdStateChange":MMa(this,a);break;case "onVolumeChanged":NMa(this,a);break;case "onSubtitlesTrackChanged":IMa(this,a);break;case "nowAutoplaying":OMa(this,a);break;case "autoplayDismissed":this.W("autoplayDismissed");break;case "autoplayUpNext":this.G=a.params.videoId||null;this.W("autoplayUpNext",this.G);break;case "onAutoplayModeChanged":this.B=
a.params.autoplayMode;this.W("autoplayModeChange",this.B);"DISABLED"==this.B&&this.W("autoplayDismissed");break;case "onHasPreviousNextChanged":PMa(this,a);break;case "requestAssistedSignIn":this.W("assistedSignInRequested",a.params.authCode);break;default:Z6("Unrecognized action: "+a.action)}};
g.k.kS=function(){if(this.u){var a=this.u;this.u=null;this.dc.videoId!=a&&d7(this,"getNowPlaying")}};
g.k.uN=function(){var a=3;this.Ha()||(a=0,isNaN(this.Ds())?O5(this.i)&&isNaN(this.C)&&(a=1):a=2);return a};
g.k.Up=function(a){Z6("Disconnecting with "+a);a7(this);this.W("beforeDisconnect",a);1==a&&Y4();FLa(this.i,a);this.dispose()};
g.k.sN=function(){var a=this.dc;this.u&&(a=this.dc.clone(),N6(a,this.u,a.index));return O6(a)};
g.k.vS=function(a){var b=new I6(a);b.videoId&&b.videoId!=this.dc.videoId&&(this.u=b.videoId,g.rp(this.J),this.J=g.pp((0,g.C)(this.kS,this),5E3));var c=[];this.dc.listId==b.listId&&this.dc.videoId==b.videoId&&this.dc.index==b.index||c.push("remoteQueueChange");this.dc.playerState==b.playerState&&this.dc.volume==b.volume&&this.dc.muted==b.muted&&M6(this.dc)==M6(b)&&g.Cj(this.dc.trackData)==g.Cj(b.trackData)||c.push("remotePlayerChange");this.dc.reset(a);g.zb(c,function(d){this.W(d)},this)};
g.k.XF=function(){var a=this.i.G.id,b=g.bb(this.l,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.k.Ds=function(){var a=this.i;return a.l.isActive()?a.l.l-g.Ra():NaN};
g.k.qN=function(){return this.B||"UNSUPPORTED"};
g.k.rN=function(){return this.G||""};
g.k.XL=function(){if(!isNaN(this.Ds())){var a=this.i.l;a.i.zg();a.start()}};
g.k.sS=function(a,b){d7(this,a,b);GMa(this)};
g.k.RD=function(){var a=g.Go("SID","")||"",b=g.Go("SAPISID","")||"",c=g.Go("__Secure-3PAPISID","")||"";if(!a&&!b&&!c)return"";a=g.uf(g.Ye(a),2);b=g.uf(g.Ye(b),2);c=g.uf(g.Ye(c),2);return g.uf(g.Ye(a+","+b+","+c),2)};
Y6.prototype.subscribe=Y6.prototype.subscribe;Y6.prototype.unsubscribeByKey=Y6.prototype.Pf;Y6.prototype.getProxyState=Y6.prototype.uN;Y6.prototype.disconnect=Y6.prototype.Up;Y6.prototype.getPlayerContextData=Y6.prototype.sN;Y6.prototype.setPlayerContextData=Y6.prototype.vS;Y6.prototype.getOtherConnectedRemoteId=Y6.prototype.XF;Y6.prototype.getReconnectTimeout=Y6.prototype.Ds;Y6.prototype.getAutoplayMode=Y6.prototype.qN;Y6.prototype.getAutoplayVideoId=Y6.prototype.rN;Y6.prototype.reconnect=Y6.prototype.XL;
Y6.prototype.sendMessage=Y6.prototype.sS;Y6.prototype.getXsrfToken=Y6.prototype.RD;g.v(e7,X5);g.k=e7.prototype;g.k.Zg=function(a){return this.Gf.$_gs(a)};
g.k.contains=function(a){return!!this.Gf.$_c(a)};
g.k.get=function(a){return this.Gf.$_g(a)};
g.k.start=function(){this.Gf.$_st()};
g.k.add=function(a,b,c){this.Gf.$_a(a,b,c)};
g.k.remove=function(a,b,c){this.Gf.$_r(a,b,c)};
g.k.Hx=function(a,b,c,d){this.Gf.$_un(a,b,c,d)};
g.k.va=function(){for(var a=0,b=this.i.length;a<b;++a)this.Gf.$_ubk(this.i[a]);this.i.length=0;this.Gf=null;X5.prototype.va.call(this)};
g.k.YL=function(){this.W("screenChange")};
g.k.nQ=function(){this.W("onlineScreenChange")};
g6.prototype.$_st=g6.prototype.start;g6.prototype.$_gspc=g6.prototype.SL;g6.prototype.$_gsppc=g6.prototype.ND;g6.prototype.$_c=g6.prototype.contains;g6.prototype.$_g=g6.prototype.get;g6.prototype.$_a=g6.prototype.add;g6.prototype.$_un=g6.prototype.Hx;g6.prototype.$_r=g6.prototype.remove;g6.prototype.$_gs=g6.prototype.Zg;g6.prototype.$_gos=g6.prototype.MD;g6.prototype.$_s=g6.prototype.subscribe;g6.prototype.$_ubk=g6.prototype.Pf;var r7=null,x7=!1,f7=null,g7=null,w7=null,k7=[];g.v(y7,g.F);g.k=y7.prototype;g.k.va=function(){g.F.prototype.va.call(this);this.i.stop();this.u.stop();this.L.stop();this.Y();var a=this.Nb;a.unsubscribe("proxyStateChange",this.WH,this);a.unsubscribe("remotePlayerChange",this.ut,this);a.unsubscribe("remoteQueueChange",this.Qw,this);a.unsubscribe("previousNextChange",this.TH,this);a.unsubscribe("nowAutoplaying",this.NH,this);a.unsubscribe("autoplayDismissed",this.nH,this);this.Nb=this.l=null};
g.k.SD=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.Nb.eb)if(z7(this)){if(!R6(this.Nb).isAdPlaying()||"control_seek"!==a)switch(a){case "control_toggle_play_pause":R6(this.Nb).qc()?this.Nb.pause():this.Nb.play();break;case "control_play":this.Nb.play();break;case "control_pause":this.Nb.pause();break;case "control_seek":this.J.zg(c[0],c[1]);break;case "control_subtitles_set_track":A7(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=
this.I.getCurrentTime();B7(this,0===c?void 0:c);break;case "control_seek":B7(this,c[0]);break;case "control_subtitles_set_track":A7(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}};
g.k.lP=function(a){this.L.zg(a)};
g.k.bT=function(a){this.SD("control_subtitles_set_track",g.Pb(a)?null:a)};
g.k.hJ=function(){var a=this.I.getOption("captions","track");g.Pb(a)||A7(this,a)};
g.k.Tb=function(a){this.l.Tb(a,this.I.getVideoData().lengthSeconds)};
g.k.YP=function(){g.Pb(this.B)||$Ma(this,this.B);this.C=!1};
g.k.WH=function(a,b){this.u.stop();2===b&&this.bJ()};
g.k.ut=function(){if(z7(this)){this.i.stop();var a=R6(this.Nb);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.l.Re=1;break;case 1082:case 1083:this.l.Re=0;break;default:this.l.Re=-1}switch(a.playerState){case 1081:case 1:this.Kb(new g.fJ(8));this.aJ();break;case 1085:case 3:this.Kb(new g.fJ(9));break;case 1083:case 0:this.Kb(new g.fJ(2));this.J.stop();this.Tb(this.I.getVideoData().lengthSeconds);break;case 1084:this.Kb(new g.fJ(4));break;case 2:this.Kb(new g.fJ(4));this.Tb(M6(a));
break;case -1:this.Kb(new g.fJ(64));break;case -1E3:this.Kb(new g.fJ(128,{errorCode:"mdx.remoteerror",errorMessage:"This video is not available for remote playback."}))}a=R6(this.Nb).trackData;var b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.B=a,$Ma(this,a));a=R6(this.Nb);-1===a.volume||Math.round(this.I.getVolume())===a.volume&&this.I.isMuted()===a.muted||this.V.isActive()||this.GJ()}else ZMa(this)};
g.k.TH=function(){this.I.W("mdxpreviousnextchange")};
g.k.Qw=function(){z7(this)||ZMa(this)};
g.k.NH=function(a){isNaN(a)||this.I.W("mdxnowautoplaying",a)};
g.k.nH=function(){this.I.W("mdxautoplaycanceled")};
g.k.setAudioTrack=function(a){z7(this)&&this.Nb.setAudioTrack(this.I.getVideoData(1).videoId,a)};
g.k.seekTo=function(a,b){-1===R6(this.Nb).playerState?B7(this,a):b&&this.Nb.seekTo(a)};
g.k.GJ=function(){var a=this;if(z7(this)){var b=R6(this.Nb);this.events.fc(this.X);b.muted?this.I.mute():this.I.unMute();this.I.setVolume(b.volume);this.X=this.events.N(this.I,"onVolumeChange",function(c){YMa(a,c)})}};
g.k.aJ=function(){this.i.stop();if(!this.Nb.Ha()){var a=R6(this.Nb);a.qc()&&this.Kb(new g.fJ(8));this.Tb(M6(a));this.i.start()}};
g.k.bJ=function(){this.u.stop();this.i.stop();var a=this.Nb.u.getReconnectTimeout();2==this.Nb.eb&&!isNaN(a)&&this.u.start()};
g.k.Kb=function(a){this.u.stop();var b=this.G;if(!g.kJ(b,a)){var c=g.U(a,2);c!==g.U(this.G,2)&&this.I.To(c);this.G=a;bNa(this.l,b,a)}};g.v(C7,g.V);C7.prototype.Rc=function(){this.i.show()};
C7.prototype.Ab=function(){this.i.hide()};
C7.prototype.l=function(){g.NI("https://support.google.com/youtube/answer/7640706")};
C7.prototype.u=function(){L4("mdx-manual-pairing-popup-ok");this.Ab()};g.v(D7,g.V);D7.prototype.Rc=function(){this.i.show()};
D7.prototype.Ab=function(){this.i.hide()};
D7.prototype.l=function(){L4("mdx-privacy-popup-cancel");this.Ab()};
D7.prototype.u=function(){L4("mdx-privacy-popup-confirm");this.Ab()};g.v(E7,g.V);E7.prototype.l=function(a){aNa(this,a.state)};g.v(F7,g.RO);F7.prototype.C=function(){var a=this.I.getOption("remote","receivers");a&&1<a.length&&!this.I.getOption("remote","quickCast")?(this.Gm=g.Ab(a,this.i,this),g.SO(this,g.Pc(a,this.i)),a=this.I.getOption("remote","currentReceiver"),a=this.i(a),this.options[a]&&this.ph(a),this.enable(!0)):this.enable(!1)};
F7.prototype.i=function(a){return a.key};
F7.prototype.gi=function(a){return"cast-selector-receiver"===a?"Cast...":this.Gm[a].name};
F7.prototype.Xe=function(a){g.RO.prototype.Xe.call(this,a);this.I.setOption("remote","currentReceiver",this.Gm[a]);this.wb.Ab()};g.v(G7,g.fM);g.k=G7.prototype;
g.k.create=function(){var a=this.player.T(),b=g.DD(a);a={device:"Desktop",app:"youtube-desktop",loadCastApiSetupScript:g.R(a.experiments,"mdx_load_cast_api_bootstrap_script"),enableDialLoungeToken:g.R(a.experiments,"enable_dial_short_lived_lounge_token"),enableCastLoungeToken:g.R(a.experiments,"enable_cast_short_lived_lounge_token")};TMa(b,a);this.subscriptions.push(g.Uq("yt-remote-before-disconnect",this.kP,this));this.subscriptions.push(g.Uq("yt-remote-connection-change",this.NQ,this));this.subscriptions.push(g.Uq("yt-remote-receiver-availability-change",
this.VH,this));this.subscriptions.push(g.Uq("yt-remote-auto-connect",this.LQ,this));this.subscriptions.push(g.Uq("yt-remote-receiver-resumed",this.KQ,this));this.subscriptions.push(g.Uq("mdx-privacy-popup-confirm",this.bS,this));this.subscriptions.push(g.Uq("mdx-privacy-popup-cancel",this.aS,this));this.subscriptions.push(g.Uq("mdx-manual-pairing-popup-ok",this.tO,this));this.VH()};
g.k.load=function(){this.player.cancelPlayback();g.fM.prototype.load.call(this);this.wh=new y7(this,this.player,this.Nb);var a=(a=XMa())?a.currentTime:0;var b=v7()?new Q6(p7(),void 0):null;0==a&&b&&(a=M6(R6(b)));0!==a&&this.Tb(a);bNa(this,this.bd,this.bd);this.player.bk(6)};
g.k.unload=function(){this.player.W("mdxautoplaycanceled");this.Ml=this.Di;g.Gi(this.wh,this.Nb);this.Nb=this.wh=null;g.fM.prototype.unload.call(this);this.player.bk(5);H7(this)};
g.k.va=function(){g.Vq(this.subscriptions);g.fM.prototype.va.call(this)};
g.k.Sj=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.wh.SD.apply(this.wh,[a].concat(g.ma(c)))};
g.k.getAdState=function(){return this.Re};
g.k.vN=function(){return this.loaded?this.wh.suggestion:null};
g.k.Gj=function(){return this.Nb?R6(this.Nb).Gj:!1};
g.k.hasNext=function(){return this.Nb?R6(this.Nb).hasNext:!1};
g.k.Tb=function(a,b){this.JG=a||0;this.player.W("progresssync",a,b)};
g.k.getCurrentTime=function(){return this.JG};
g.k.getProgressState=function(){var a=R6(this.Nb),b=this.player.getVideoData();return{allowSeeking:g.R(this.player.T().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.Qe():!a.isAdPlaying()&&this.player.Qe(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.l?a.u+K6(a):a.u,isAtLiveHead:1>=(a.l?a.i+K6(a):a.i)-this.getCurrentTime(),loaded:a.L,seekableEnd:a.l?a.i+K6(a):a.i,seekableStart:0<a.B?a.B+
K6(a):a.B}};
g.k.nextVideo=function(){this.Nb&&this.Nb.nextVideo()};
g.k.Tw=function(){this.Nb&&this.Nb.Tw()};
g.k.kP=function(a){1===a&&(this.EB=this.Nb?R6(this.Nb):null)};
g.k.NQ=function(){var a=v7()?new Q6(p7(),void 0):null;if(a){var b=this.Ml;this.loaded&&this.unload();this.Nb=a;this.EB=null;b.key!==this.Di.key&&(this.Ml=b,this.load())}else g.Fi(this.Nb),this.Nb=null,this.loaded&&(this.unload(),(a=this.EB)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,M6(a)));this.player.W("videodatachange","newdata",this.player.getVideoData(),3)};
g.k.VH=function(){var a=[this.Di],b=a.concat,c=UMa();E6()&&g.ov("yt-remote-cast-available")&&c.push({key:"cast-selector-receiver",name:"Cast..."});this.Gm=b.call(a,c);a=q7()||this.Di;I7(this,a);this.player.Ma("onMdxReceiversChange")};
g.k.LQ=function(){var a=q7();I7(this,a)};
g.k.KQ=function(){this.Ml=q7()};
g.k.bS=function(){this.xt=!0;H7(this);x7=!1;r7&&t7(r7,1);r7=null};
g.k.aS=function(){this.xt=!1;H7(this);I7(this,this.Di);this.Ml=this.Di;x7=!1;r7=null;this.player.playVideo()};
g.k.tO=function(){this.nw=!0;H7(this);g.nv("yt-remote-manual-pairing-warning-shown",!0,2592E3);x7=!1;r7&&t7(r7,1);r7=null};
g.k.Ke=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.Gm;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?G6():I7(this,b)),this.loaded?this.Ml:this.Di;case "quickCast":return 2===this.Gm.length&&"cast-selector-receiver"===this.Gm[1].key?(b&&G6(),!0):!1}};
g.k.tC=function(){this.Nb.tC()};
g.k.Uh=function(){return!1};
g.k.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.lM.remote=G7;})(_yt_player);
